### ISSUE TITLE
RuntimeError: unique is currently CPU-only, and lacks CUDA support. Pull requests welcome!

### ISSUE THREAD

**Issue by UMJCS** [eriklindernoren/PyTorch-YOLOv3#1]
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    detections = non_max_suppression(detections, 80, opt.conf_thres, opt.nms_thres)
  File "/PyTorch-YOLOv3/utils.py", line 73, in non_max_suppression
    for c in detections[:, -1].unique():
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 310, in unique
    sorted=sorted, return_inverse=return_inverse)
RuntimeError: unique is currently CPU-only and lacks CUDA support. Pull requests welcome!

It executes wrong as above, it seems CPU only? 
My environment is:
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
torch.__version__
'0.4.0'
4 TITanX GPU

**Comment by eriklindernoren** [comment]
Thanks. This is fixed in 472796e.
