### ISSUE TITLE
error whan training the model on new images

### ISSUE THREAD

**Issue by yoryory** [eriklindernoren/PyTorch-YOLOv3#100]
if you choose to load the pretrained model:
using model.load_weights(opt.weights_path)
instead using : model.apply(weights_init_normal)

i got that problem 

  File "<ipython-input-12-9cf8799df0aa>", line 7, in <module>
    loss = model(imgs, targets)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\user\Desktop\st\PyTorch_YOLOv3_master\models.py", line 259, in forward
    x, *losses = module[0](x, targets)

  File "C:\Users\user\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\user\Desktop\st\PyTorch_YOLOv3_master\models.py", line 176, in forward
    precision = float(nCorrect / nProposals)

ZeroDivisionError: division by zero

**Comment by erayyildiz** [comment]
I have also encountered this issue. Changing the line:
`precision = float(nCorrect / nProposals)` to
`precision = float(nCorrect / nProposals) if nProposals else 1` 
This solved the for me.

**Comment by packyan** [comment]
> Oh yes yo are right. if nProposals and nCorrect are both 0, the precision should be 1.
> I used yolov3.weights for pretrained weights since the architecture is proper. darknet53.conv.74 causes some tensor shape errors in my project. But I am not sure this is correct.

https://github.com/ultralytics/yolov3 
you can look up this repo, the author edited the model.py
load weights fuction so that it can load darknet53.conv.74 files in first epoch. But I
Didn’t test yet. Hope you can get some ideas from the repo. But I’m still confused why just use weight init normal can’t detect any objects, but if you load any weights instead of init normal, training some epochs the net can detect objects. Why ? 
Doctor please help😂😂

**Comment by erayyildiz** [comment]
Thank you very much. ´cutoff´ parameter of ´load_weights´ function makes possible to load weights from darknet53.conv.74 by loading weights for only layers between 0 and cutoff.

However, I could not achieve a good result yet. There should be another issue, maybe in data loader and bounding boxes (x, y, w, h). I am working on it.
