### ISSUE TITLE
training on images with no objects

### ISSUE THREAD

**Issue by meganlrowe97** [eriklindernoren/PyTorch-YOLOv3#101]
Is it possible to train yolov3 on images with no objects in them. How would you generate an annotation for this?

**Comment by nanfeng-dada** [comment]
the same question+1

**Comment by hellowangfeng** [comment]
the same question+1

**Comment by nishchaychawla** [comment]
the same question+1, Did anyone found the answer?

**Comment by songtao-ye** [comment]
the same question+1

**Comment by SmileJET** [comment]
the same question+1

**Comment by Flova** [comment]
It should be able to utilize negative samples now, but negative samples are often not really needed in object detection:
https://ai.stackexchange.com/questions/28371/how-to-add-negative-samples-for-object-detection
