### ISSUE TITLE
"tqdm" is missing in requirements.txt

### ISSUE THREAD

**Issue by valentinpy** [eriklindernoren/PyTorch-YOLOv3#102]
"tqdm" is missing in requirements.txt, required at least in test.py

**Comment by k4kuz0** [comment]
Hi ran into this problem as well, so bump to this.

Also, I believe the requirement `torch>=4.0` is wrong, as I get an error `AttributeError: 'Tensor' object has no attribute 'argsort'` when running `python3 detect.py --image_folder data/samples`, and it appears argsort is only available in torch 1.0.

**Comment by eriklindernoren** [comment]
Fixed. :+1:
