### ISSUE TITLE
Detection layer vs conv layer

### ISSUE THREAD

**Issue by AlexTS1980** [eriklindernoren/PyTorch-YOLOv3#104]
If my understanding is correct, the last layer in YOLO is a detection (yolo) layer that creates an NxN grid. I keep thinking of it, and I don't quite understand, why we can't use instead a conv layer with a 1x1 kernel and (say) 25 maps (20 classes + 4 bbox pars + 1 score) followed by a loss layer and let the network sort it out?

**Comment by eriklindernoren** [comment]
That sort of what's being done in the YOLO layer. The default model has three YOLO models that operates at different feature resolutions. An example of what the input shape at one of these layers can look like is `[8, 3 * 85, 13, 13]`, where `8` corresponds to the batch size, and `13` tells you that the YOLO network divides the image into a `13x13` grid, where for each of these we have `3x85` outputs. The three corresponds to our `3` anchors, and for each of these we have `85` outputs for class label, object confidence score, coordinates and shape of the bounding box.

**Comment by AlexTS1980** [comment]
Thanks, sorry for such a late reply.

Is it correct that one anchor=one prediction, so one 'cell' in a grid can predict at most 3 objects that have centroids in this 'cell'?
