### ISSUE TITLE
Heavy on cpu ?

### ISSUE THREAD

**Issue by Ownmarc** [eriklindernoren/PyTorch-YOLOv3#105]
Hello, is this normal that it requires so much from the cpu ? Is there a way to reduce cpu usage ?

**Comment by shipeizhen** [comment]
I met the same problem as you. Do you solve it?

**Comment by fourth-archive** [comment]
@Ownmarc this repository is multiGPU capable with a multithreaded dataloader. This should reduce your CPU usage!
https://github.com/ultralytics/yolov3

**Comment by eriklindernoren** [comment]
Hey @Ownmarc . There have been major changes made to the implementation in the past week or so. Could you try again with the current version and report your findings?
