### ISSUE TITLE
YOLOv3 Mobilenet VOC2007

### ISSUE THREAD

**Issue by Adamdad** [eriklindernoren/PyTorch-YOLOv3#109]
| Model name | InputSize | TrainSet | TestSet | mAP | 
| ----- | ------ | ------ | ------ | ----- | 
| [YOLOv3-Mobilenet](https://github.com/Adamdad/keras-YOLOv3-mobilenet) | 320x320 | VOC07+12 | VOC07 | 74.56% | 
| MobileNet-SSD | 300x300 | VOC07+12+coco | VOC07 | 72.7% |

**Comment by eriklindernoren** [comment]
Hi @Adamdad . Is this an issue?
