### ISSUE TITLE
How to output the results with the original size?

### ISSUE THREAD

**Issue by wukongeek** [eriklindernoren/PyTorch-YOLOv3#113]
The output in the detect.py are images resized and padded, and how to output the results with the original size?

**Comment by richipower** [comment]
hi @wukongeek i have the same question, did you manage to map the coordinates to the original img size?

**Comment by wukongeek** [comment]
> hi @wukongeek i have the same question, did you manage to map the coordinates to the original img size?

i tried, but failed.

**Comment by richipower** [comment]
i solved it using opencv like this:
cv2.rectangle(img, (x1, y1), (x1+box_w, y1+box_h), (0, 255, 0), 2)

**Comment by eriklindernoren** [comment]
@wukongeek You can see how this is done in `detect.py`.

**Comment by eriklindernoren** [comment]
@wukongeek See [`utils.rescale_boxes`](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/utils/utils.py#L36) and [how it's used](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/detect.py#L112) in `detect.py`.

**Comment by hongjianyuan** [comment]
I have used the original picture and used rescale_boxes, but what I draw is the picture after resize
