### ISSUE TITLE
Runtime error inside of Anaconda environment in Windows

### ISSUE THREAD

**Issue by mattboler** [eriklindernoren/PyTorch-YOLOv3#116]
Using the detector script produces:
RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase. This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module.

**Comment by ardeal** [comment]
I encountered the same issue that can be fixed by the same solution as you mentioned.
but I am  curious why the line if __name__=='__main__': is required?

**@**

**Comment by eriklindernoren** [comment]
Fixed! Pull the latest version and this should be solved.

**Comment by zxealous** [comment]
Which code should I add?    if __name__ == '__main__'
