### ISSUE TITLE
save weights error

### ISSUE THREAD

**Issue by NJUFlipped** [eriklindernoren/PyTorch-YOLOv3#12]
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    model.save_weights('%s/%d.weights' % (opt.checkpoint_dir, epoch))
  File "F:\cmp\VehicleDetection\PyTorch-YOLOv3\models.py", line 306, in save_weights
    self.header_info[3] = self.seen
  File "D:\software\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'seen'

**Comment by DeokyunKim** [comment]
I have same error.

**Comment by nationalflag** [comment]
You should load a pretrained weights such as yolov3.weights first in train.py.

**Comment by DeokyunKim** [comment]
@nationalflag  Could you write the code ? I didnt understand. thanks !

**Comment by nationalflag** [comment]
model = Darknet(opt.model_config_path)
model.apply(weights_init_normal)
model.load_weights(opt.weights_path)

Darknet.seen is assigned in load_weights

**Comment by eriklindernoren** [comment]
Hi, this is fixed in 6727086. You don't have to load pretrained weights to be able to save the weights of the model during training with this commit.

**Comment by poornimajd** [comment]
Hey can the  save darknet weights function in models.py be used to save the weights in pytorch format ,i.e with the extension .pt ,or how is that function used?
