### ISSUE TITLE
This implementation is very great. May you add a open-source license of it?

### ISSUE THREAD

**Issue by huhrichard** [eriklindernoren/PyTorch-YOLOv3#122]
My team has a project of object detection and people tracking, we found your implementation on PyTorch is very good. We are interested to employ your code in part of our project.

May you add a open-source license on it for us to credit your codes?
Thank you very much!

**Comment by fourth-archive** [comment]
The repo below comes with a GPL-3.0 open-source license.
https://github.com/ultralytics/yolov3

**Comment by ccerhan** [comment]
If you are already trained your model, I mean you already have weights and config file, you can use my [implementation](https://github.com/ccerhan/yolov3-detector). Training is not possible with this implementation, but it is fast and ready for real-time usage by importing the weights and config files.

**Comment by eriklindernoren** [comment]
Set license GPL-3.0

**Comment by kb1ooo** [comment]
Why GPL?  Especially when the intention of the original author of the algorithm is to allow people to do what they want with it.
