### ISSUE TITLE
anyone can train successfully?

### ISSUE THREAD

**Issue by mehrdadazizi72** [eriklindernoren/PyTorch-YOLOv3#123]
I try to train on open-image dataset with several diffrent ways but results are really bad.
model in detect.py, return negative anchors in some tries, or model detect nothing.
for example, I train only 2picture for 300 and 100 epoch to overfitting network but none of them detect anything.
something wrong with the train.py, anyone has an idea about this?

**Comment by estimoelmo** [comment]
2 images are not enough to train

**Comment by fourth-archive** [comment]
@estimoelmo one image is enough to train actually. See this tutorial:
https://github.com/ultralytics/yolov3/wiki/Example:-Train-Single-Image

**Comment by zhaowt61** [comment]
1 change the " ptr = 0" in the function "load_weights(self, weights_path):" to "ptr=5". Because they added header_info into the weights file, which makes the loading mismatched by 5 bits. This bug is hidden so deep!
2 remove "model.eval()" in "detect.py"

The above solutions worked perfectly for me.

**Comment by liujiang137** [comment]
> 1 change the " ptr = 0" in the function "load_weights(self, weights_path):" to "ptr=5". Because they added header_info into the weights file, which makes the loading mismatched by 5 bits. This bug is hidden so deep!
> 2 remove "model.eval()" in "detect.py"
> The above solutions worked perfectly for me.

HI，I run the Pre-training model on test.py on the coco dataset consistently outputs around 40mAP instead of the 57.9 or 58.2. Is there a reason why I cannot get this 57.9 or 58.2mAP output?  Now I am training my model and I want to know if the best result you got on this code has reached teh result of the paper. Thank you in advance for your reply.

**Comment by dljrichard** [comment]
> > 1 change the " ptr = 0" in the function "load_weights(self, weights_path):" to "ptr=5". Because they added header_info into the weights file, which makes the loading mismatched by 5 bits. This bug is hidden so deep!
> > 2 remove "model.eval()" in "detect.py"
> > The above solutions worked perfectly for me.
> 
> HI，I run the Pre-training model on test.py on the coco dataset consistently outputs around 40mAP instead of the 57.9 or 58.2. Is there a reason why I cannot get this 57.9 or 58.2mAP output? Now I am training my model and I want to know if the best result you got on this code has reached teh result of the paper. Thank you in advance for your reply.

I have the same prob. If run pretrained test.py directly, I got only approx 40.96 mAP, where two classes  (class 70 and 78) have zero AP. Please let me know if you have found the solution.

**Comment by fourth-archive** [comment]
@dljrichard @liujiang137 @zhaowt61 recommend this repository. 0.607 mAP using pycocotools on yolov3-spp.weights.
https://github.com/ultralytics/yolov3

<i></i> | [ultralytics/yolov3](https://github.com/ultralytics/yolov3) | [darknet](https://arxiv.org/abs/1804.02767) 
--- | --- | ---  
`YOLOv3 320` | 51.8 | 51.5  
`YOLOv3 416` | 55.4 | 55.3  
`YOLOv3 608` | 58.2 | 57.9  
`YOLOv3-spp 320` | 52.4 | -  
`YOLOv3-spp 416` | 56.5 | -  
`YOLOv3-spp 608` | 60.7 | 60.6  

``` bash
sudo rm -rf yolov3 && git clone https://github.com/ultralytics/yolov3
# bash yolov3/data/get_coco_dataset.sh
sudo rm -rf cocoapi && git clone https://github.com/cocodataset/cocoapi && cd cocoapi/PythonAPI && make && cd ../.. && cp -r cocoapi/PythonAPI/pycocotools yolov3
cd yolov3
 
python3 test.py --save-json --conf-thres 0.001 --img-size 608 --batch-size 16
Namespace(batch_size=16, cfg='cfg/yolov3.cfg', conf_thres=0.001, data_cfg='cfg/coco.data', img_size=608, iou_thres=0.5, nms_thres=0.5, save_json=True, weights='weights/yolov3.weights')
Using cuda _CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16130MB, multi_processor_count=80)
      Image      Total          P          R        mAP
Calculating mAP: 100%|█████████████████████████████████| 313/313 [08:54<00:00,  1.55s/it]
       5000       5000     0.0966      0.786      0.579
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.331
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.344
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.198
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.427
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.281
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.437
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.463
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.309
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.494
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.577
 
python3 test.py --weights weights/yolov3-spp.weights --cfg cfg/yolov3-spp.cfg --save-json --img-size 608 --batch-size 8
Namespace(batch_size=8, cfg='cfg/yolov3-spp.cfg', conf_thres=0.001, data_cfg='data/coco.data', img_size=608, iou_thres=0.5, nms_thres=0.5, save_json=True, weights='weights/yolov3-spp.weights')
Using cuda _CudaDeviceProperties(name='Tesla V100-SXM2-16GB', major=7, minor=0, total_memory=16130MB, multi_processor_count=80)
       Image      Total          P          R        mAP
Calculating mAP: 100%|█████████████████████████████████| 625/625 [07:01<00:00,  1.56it/s]
       5000       5000       0.12       0.81      0.611
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.366
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.607
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.386
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.207
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.391
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.485
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.296
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.464
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.494
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.331
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.517
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.618
```

**Comment by eriklindernoren** [comment]
Training should work ok now if you pull the latest version. That said there are still some training tricks and augmentations to be implemented. `ultralytics` version is a good option.
