### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [256, 256, 3, 3], expected input[1, 384, 26, 26] to have 256 channels, but got 384 channels instead？

### ISSUE THREAD

**Issue by cuixing158** [eriklindernoren/PyTorch-YOLOv3#124]
envs:   spyder+anaconda+windows+pytorch1.0
when i set yolov3-tiny.cfg and yolov3-tiny.weights path,  and run detect.py,it get an error?
RuntimeError: Given groups=1, weight of size [256, 256, 3, 3], expected input[1, 384, 26, 26] to have 256 channels, but got 384 channels instead?
debug: i == 21, this "x = module(x)" raise error,i don't how to modify,thks

**Comment by fourth-archive** [comment]
Try this:
```
git clone https://github.com/ultralytics/yolov3 
cd yolov3
python3 detect.py --cfg cfg/yolov3-tiny.cfg --weights weights/yolov3-tiny.weights 
```
![50374155-21427380-05ea-11e9-8d24-f1a4b2bac1ad](https://user-images.githubusercontent.com/47483425/53733307-ed54bb80-3e80-11e9-909e-0290f6612324.jpg)

**Comment by waelreda** [comment]
i got the same error .there is suggested solution for this i think here.
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/82
though it didnt work for me.

**Comment by fourth-archive** [comment]
Ah, but this is already fixed in the https://github.com/ultralytics/yolov3 repo since last year. You can see the solution implemented here:
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/82#issuecomment-449566083

**Comment by cuixing158** [comment]
> Ah, but this is already fixed in the https://github.com/ultralytics/yolov3 repo since last year. You can see the solution implemented here:
> [#82 (comment)](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/82#issuecomment-449566083)

thanks very much!
