### ISSUE TITLE
Why the pad is caculated like this?

### ISSUE THREAD

**Issue by Liumihan** [eriklindernoren/PyTorch-YOLOv3#129]
awsome work! but can you tell me?

In the file [models.py](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/models.py) and in the method *create_modules* , you calculate the pad like this`pad = (kernel_size - 1) // 2 if int(module_def["pad"]) else 0`, but why? Why not use the pad number in the cfg file?

Thanks for your reply!

**Comment by fnwkqwan** [comment]
maybe the pad=1 in the cfg file just represent the flag whether the net needs padding

**Comment by HIT-Owen** [comment]
if padding:
      pad = (kernel_size - 1) // 2
else:
      pad = 0
the pad is a mark but not the padding value

**Comment by Flova** [comment]
This code has been modified and is now outdated
