### ISSUE TITLE
cannot train loss all nan  batch =8  

### ISSUE THREAD

**Issue by hexiangquan** [eriklindernoren/PyTorch-YOLOv3#13]

**Comment by wangzhaolei** [comment]
my loss is all nan too :( ,who can tell me why?Thanks.
[Epoch 0/30, Batch 323/1313] [Losses: x nan, y nan, w nan, h nan, conf 0.755184, cls nan, total nan]
[Epoch 0/30, Batch 324/1313] [Losses: x nan, y nan, w nan, h nan, conf 0.760500, cls nan, total nan]
[Epoch 0/30, Batch 325/1313] [Losses: x nan, y nan, w nan, h nan, conf 0.755139, cls nan, total nan]
[Epoch 0/30, Batch 326/1313] [Losses: x nan, y nan, w nan, h nan, conf 0.757809, cls nan, total nan]

**Comment by eriklindernoren** [comment]
Hi, this problem is fixed in 6727086.
