### ISSUE TITLE
Slow Inference in Production

### ISSUE THREAD

**Issue by hoangtuanvu** [eriklindernoren/PyTorch-YOLOv3#132]
I tested the model on list of images on GTX 1080 Ti. The model achieved good speed. But I cannot use this model in production. Because Dataloader of Pytorch is slow. How can I speed up inference time in production? Thanks

**Comment by fourth-archive** [comment]
Recommend this repository. Has multiGPU and multithreaded dataloader. Also comes with a realtime YOLOv3 iOS app.
https://github.com/ultralytics/yolov3

<table style="width:100%">
  <tr><th><img src="https://user-images.githubusercontent.com/26833433/54523854-227d0580-4979-11e9-9801-26a3be239875.jpg" width="350"></th>
    <th><img src="https://storage.googleapis.com/ultralytics/logo/logoname1000.png" width="160">
  <br><br/>
  <p> <a href="https://itunes.apple.com/app/id1452689527">
  <img href="https://itunes.apple.com/app/id1452689527" src="https://user-images.githubusercontent.com/26833433/50044365-9b22ac00-0082-11e9-862f-e77aee7aa7b0.png" width="180"> 
  </a> </p></th> 
  </tr>
</table>

**Comment by hoangtuanvu** [comment]
@fourth-archive Thank you. Can you tell me more about inference time of both Yolov3 and Yolo-tinyv3?

**Comment by fourth-archive** [comment]
Well you can see right there on the iPhone screen can't you?

**Comment by eriklindernoren** [comment]
@hoangtuanvu I have switched to `lycon` for image processing instead of `pillow` which was previously used. `lycon` is supposed to be even faster than `opencv` according to their project web page https://github.com/ethereon/lycon. Feel free to try the latest version.
