### ISSUE TITLE
Low recall and precision values

### ISSUE THREAD

**Issue by akshaygadipatil** [eriklindernoren/PyTorch-YOLOv3#136]

**Comment by akshaygadipatil** [comment]
Hi @eriklindernoren ,

I am using this repo to train on my custom dataset. The training is in progress.
I used `python train.py`

I see that the recall and precision scores are low. 
Recall appears to increase be increasing, from 0.08 to 0.2/0.3, with the number of epochs., but the precision value is pretty low (0.004/0.006).

To doublecheck, I also started training on coco dataset on another GPU and there too, the case is similar.

Is this normal? 
I mean, is the repository helpful for training yolov3 or is the training pipeline code incomplete?
Please let me know as many people may (might have) encounter(ed) the same problem.

Thanks,
Akshay

**Comment by wrongbattery** [comment]
Yes, i encounter this problem, too. Even i train it for 30 epochs. It predicts nothing at testing. However, Darknet c model works well

**Comment by akshaygadipatil** [comment]
> Yes, i encounter this problem, too. Even i train it for 30 epochs. It predicts nothing at testing. However, Darknet c model works well

This repository doesn't work for customized training from scratch.
Best alternative resource is: [https://github.com/ultralytics/yolov3](url).
I tried it and it works very well.

**Comment by wrongbattery** [comment]
thanks @akshaygadipatil

**Comment by eriklindernoren** [comment]
Using the latest master version I can get the model to converge during training now. That said there are still some augmentation and other tricks to be implemented. `ultralytics` version is a good option!
