### ISSUE TITLE
No module named lycon

### ISSUE THREAD

**Issue by JerryZhuzq** [eriklindernoren/PyTorch-YOLOv3#138]
`Traceback (most recent call last):
  File "detect.py", line 5, in <module>
    from utils.datasets import *
  File "C:\pyTorch\git\PyTorch-YOLOv3\utils\datasets.py", line 5, in <module>
    import lycon
ModuleNotFoundError: No module named 'lycon'`

Hello! I tested your update version 3 hours ago and there is a bug in windows 10. Win10 cannot import lycon and this problem didn't exist in the older version. Could you fix it please. Thank you.

**Comment by eriklindernoren** [comment]
Try `pip3 install lycon`. If that does not immediately fix it you can find some instructions at https://github.com/ethereon/lycon.

**Comment by justein** [comment]
@eriklindernoren as above mentioned ，the lycon module could not install in my env ,which py3.5 + windows7 64 ,plz give some help, thx!

**Comment by eriklindernoren** [comment]
@justein `pip3 install lycon` didn't do it for you?

**Comment by QLMX** [comment]
the lycon can be replaced with other function packs?the lycon module could not install in my env

**Comment by justein** [comment]
@eriklindernoren  yes I certainly tried ,and has downgrade the py version to 2.x ,it works fine and thx!

**Comment by eriklindernoren** [comment]
@QLMX Yes, it could be replaced with `PIL.Image.open(path)` for loading images. For resizing you could use `torch.nn.functional.interpolate(img_tensor, size=self.img_size, mode="nearest")`.

**Comment by eriklindernoren** [comment]
We currently have two open issues on lycon, so I'll refer you to #142, and we can keep the discussion there.
