### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'img_dim'

### ISSUE THREAD

**Issue by superwenda** [eriklindernoren/PyTorch-YOLOv3#139]
Function forward defined like this:
`def forward(self, x, targets, img_dim)`
After I execute command `python3 test.py --weights_path weights/yolov3.weights --batch_size 4` error happened and program output:

> Namespace(batch_size=4, class_path='data/coco.names', conf_thres=0.001, data_config_path='config/coco.data', img_size=416, iou_thres=0.5, model_config_path='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Compute mAP...
Detecting objects:   0%|                               | 0/1250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    outputs = model(imgs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wenda/workspace/py/PyTorch-YOLOv3/models.py", line 273, in forward
    x = module(x, img_dim=img_dim)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'img_dim'

Anyone know the answer?

**Comment by graylevel255** [comment]
Even I'm getting the above error !

**Comment by eriklindernoren** [comment]
Sorry about that. It was fixed in fa1322a.
