### ISSUE TITLE
test with fewer classes

### ISSUE THREAD

**Issue by ShijianXu** [eriklindernoren/PyTorch-YOLOv3#143]
Hi, I have a question about testing. I want to test a set of labels which is a subset of the COCO labels. What's the correct way to map the labels? I mean, for example, my dataset only contains 2 classes (People and Car), what's their corresponding label numbers in COCO?

In the coco.names you provide, the correspondence is:

> Cls ------->Cls name in coco.names
people--->person(the first line)
car-------->car(the third line)

So, I give the label 0 and 2 for People and Car. 
The problem is, the average precision for `person` is very low(0.0156) while the average precision for `car` is high(0.717). But when I use `detect.py` to visualize the detection results, the person are detected quite well. So it's very strange to see such a low AP for person. 

Is my mapping correct?

**Comment by eriklindernoren** [comment]
I think you got the class map correctly, `{"person": 0, "car": 2}`. As for the AP of `person`, that number seems very low indeed. I'll take a look at it as soon as I have time. 👍

**Comment by ShijianXu** [comment]
thank you for your reply. really appreciate the code you provide

**Comment by stevenalexis** [comment]
@ShijianXu hi. I have same issue. Did you solved it!
