### ISSUE TITLE
mAP peoblem

### ISSUE THREAD

**Issue by ShijianXu** [eriklindernoren/PyTorch-YOLOv3#144]
Hi, can anyone show the detailed APs on COCO for each class?
Here is mine:

> Average Precisions:
+ Class '0' (person) - AP: 0.03568028324394441
+ Class '1' (bicycle) - AP: 0.46628557110013813
+ Class '2' (car) - AP: 0.6262486140135283
+ Class '3' (motorbike) - AP: 0.6542703126970679
+ Class '4' (aeroplane) - AP: 0.8204272937148677
+ Class '5' (bus) - AP: 0.826387668104636
+ Class '6' (train) - AP: 0.8117522643960229
+ Class '7' (truck) - AP: 0.4389599040481864
+ Class '8' (boat) - AP: 0.440388566932933
+ Class '9' (traffic light) - AP: 0.4651363971586642
+ Class '10' (fire hydrant) - AP: 0.8362798223951957
+ Class '11' (stop sign) - AP: 0.7728885264651689
+ Class '12' (parking meter) - AP: 0.5254057801073817
+ Class '13' (bench) - AP: 0.3537438228287043
+ Class '14' (bird) - AP: 0.45288757034012644
+ Class '15' (cat) - AP: 0.7746437724606435
+ Class '16' (dog) - AP: 0.7415899340050307
+ Class '17' (horse) - AP: 0.7702545769974758
+ Class '18' (sheep) - AP: 0.6166059547880655
+ Class '19' (cow) - AP: 0.5210266268413313
+ Class '20' (elephant) - AP: 0.8476261202936236
+ Class '21' (bear) - AP: 0.8054676029430057
+ Class '22' (zebra) - AP: 0.8267400194133763
+ Class '23' (giraffe) - AP: 0.8833330320079644
+ Class '24' (backpack) - AP: 0.3325045659578594
+ Class '25' (umbrella) - AP: 0.588602137895704
+ Class '26' (handbag) - AP: 0.21626906167062748
+ Class '27' (tie) - AP: 0.5254885688211799
+ Class '28' (suitcase) - AP: 0.5973159507793862
+ Class '29' (frisbee) - AP: 0.7556810247170026
+ Class '30' (skis) - AP: 0.41484346030555097
+ Class '31' (snowboard) - AP: 0.5436996806220652
+ Class '32' (sports ball) - AP: 0.5904236618137597
+ Class '33' (kite) - AP: 0.4567195794296096
+ Class '34' (baseball bat) - AP: 0.5096480611636788
+ Class '35' (baseball glove) - AP: 0.5058856660595228
+ Class '36' (skateboard) - AP: 0.7297978030035821
+ Class '37' (surfboard) - AP: 0.6667936065510727
+ Class '38' (tennis racket) - AP: 0.737448845181832
+ Class '39' (bottle) - AP: 0.4403383293775043
+ Class '40' (wine glass) - AP: 0.49237107134586083
+ Class '41' (cup) - AP: 0.5079673049474462
+ Class '42' (fork) - AP: 0.4469239739122669
+ Class '43' (knife) - AP: 0.25670747810180955
+ Class '44' (spoon) - AP: 0.23007598365520937
+ Class '45' (bowl) - AP: 0.5209473367557331
+ Class '46' (banana) - AP: 0.3353436415731313
+ Class '47' (apple) - AP: 0.21457335805479488
+ Class '48' (sandwich) - AP: 0.44477576162190613
+ Class '49' (orange) - AP: 0.2871533825334021
+ Class '50' (broccoli) - AP: 0.37158536893601457
+ Class '51' (carrot) - AP: 0.21335407421665042
+ Class '52' (hot dog) - AP: 0.3731154728196108
+ Class '53' (pizza) - AP: 0.578458703605767
+ Class '54' (donut) - AP: 0.4438781638988414
+ Class '55' (cake) - AP: 0.4944040777191342
+ Class '56' (chair) - AP: 0.4288324524192434
+ Class '57' (sofa) - AP: 0.5813972200030231
+ Class '58' (pottedplant) - AP: 0.46171317740828843
+ Class '59' (bed) - AP: 0.6704619117855745
+ Class '60' (diningtable) - AP: 0.4255212620946715
+ Class '61' (toilet) - AP: 0.8338698615789082
+ Class '62' (tvmonitor) - AP: 0.7530894705328256
+ Class '63' (laptop) - AP: 0.7181519248573878
+ Class '64' (mouse) - AP: 0.747460904097144
+ Class '65' (remote) - AP: 0.4553878536477043
+ Class '66' (keyboard) - AP: 0.6924056064750946
+ Class '67' (cell phone) - AP: 0.40966019483265814
+ Class '68' (microwave) - AP: 0.8157196612190764
+ Class '69' (oven) - AP: 0.521643678272177
+ Class '70' (toaster) - AP: 0.14534435261707987
+ Class '71' (sink) - AP: 0.5939301868731891
+ Class '72' (refrigerator) - AP: 0.7344214026352603
+ Class '73' (book) - AP: 0.16783610694347773
+ Class '74' (clock) - AP: 0.7465604793503379
+ Class '75' (vase) - AP: 0.5304917539460398
+ Class '76' (scissors) - AP: 0.3582611330575755
+ Class '77' (teddy bear) - AP: 0.6213975418869717
+ Class '78' (hair drier) - AP: 0.11363636363636365
+ Class '79' (toothbrush) - AP: 0.33315517576456294
mAP: 0.5374684358784905

However, the AP for `person` is quite low. Is that right?

**Comment by eriklindernoren** [comment]
@ShijianXu l'll update you about this in #143.
