### ISSUE TITLE
8 hours for testing if I do not load weights

### ISSUE THREAD

**Issue by yeshaokai** [eriklindernoren/PyTorch-YOLOv3#146]
For some reasons, If I commented out the load weights block in test.py, testing coco takes 8 hours. 
I tried to load the yolo weights and quantize the weights. However, I found that modifying the weights make the testing very slow(8 hours). Then I realized that simply not loading the weights makes the testing slow.

**Comment by eriklindernoren** [comment]
You will probably want to load some pretrained weights, if not you will get an extreme amount of predictions (since we set confidence threshold at `0.001`), and those will take an very long time to process when we do `non_max_suppression` and compute class APs.

**Comment by yeshaokai** [comment]
@eriklindernoren  you are right. Thanks!
