### ISSUE TITLE
Error if we set "compute_map=True"

### ISSUE THREAD

**Issue by ghimiredhikura** [eriklindernoren/PyTorch-YOLOv3#147]
Hello @eriklindernoren , 
Thank you for the wonderful work. 

I am training on coco dataset from scratch. But if I set compute_map=True, it gives following error. 
```
Traceback (most recent call last):
  File ".\train.py", line 156, in <module>
    targets[:, :, 1:] = xywh2xyxy(targets[:, :, 1:])
IndexError: too many indices for tensor of dimension 2
```
If I am not wrong, this should be fixed by replacing `targets[:, :, 1:] => targets[:, 1:]`

But after fixing this I got another error: 
```
File ".\train.py", line 159, in <module>
    statistics = get_batch_statistics(predictions, targets, iou_threshold=0.5)
  File "E:\3D-Object-Detection\PyTorch-YOLOv3\utils\utils.py", line 173, in get_batch_statistics
    if pred_label not in target_labels:
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'other'
```

Can you please take a look into it. 

Thanks.

**Comment by eriklindernoren** [comment]
Hi, I don't normally run training with `--compute_map` since it slows down training quite a bit. I think it might be better to have a test phase after each epoch where mAP is calculated on the validation set. I'll add that as soon as I have time.

**Comment by ghimiredhikura** [comment]
Yes, that will be much better. Thanks.

**Comment by timforby** [comment]
#150 addresses it

**Comment by eriklindernoren** [comment]
I have added an evaluation step after each epoch where mAP etc. is calculated on the validation set instead. I'm closing this one. If you have any problems with the new version feel free to create a new issue.
