### ISSUE TITLE
The bounding boxes on sample images are off.

### ISSUE THREAD

**Issue by EverWinter23** [eriklindernoren/PyTorch-YOLOv3#153]
First of, the folder name in detect.py should be changed from output->assets:
```
  plt.savefig("assets/%d.png" % (img_i), bbox_inches="tight", pad_inches=0.0)
```

And these are the images I obtained after running detect.py. All of them are off, but I uploaded just a select few.
![3](https://user-images.githubusercontent.com/21227016/57006190-6ad84600-6bfc-11e9-8cb4-74137b2cf65a.png)
![6](https://user-images.githubusercontent.com/21227016/57006191-6b70dc80-6bfc-11e9-8b0c-204c8d9b13fd.png)
![7](https://user-images.githubusercontent.com/21227016/57006192-6c097300-6bfc-11e9-9a91-e698b9f362bb.png)

**Comment by EverWinter23** [comment]
I also think that using only COCO to validate the model is really slow. A quick fix would be to support PASCAL VOC 2007 which is a much smaller data set and can demonstrate the correctness of the model in small amount of time.

Why not merge [Pull Request](https://github.com/eriklindernoren/PyTorch-YOLOv3/pull/50)?

**Comment by EverWinter23** [comment]
Problem with my notebook. Sorry.

**Comment by eriklindernoren** [comment]
That's strange, when I run `python3 detect.py` the bounding boxes are positioned correctly. Can you pull the latest version and try again? Regarding the `assets` folder that's where I keep images that I use in the README, so I prefer to not mix those with the images produced by `detect.py`.

**Comment by eriklindernoren** [comment]
I prefer to have a separate folder for images produced by `detect.py`. The `assets` folder is reserved for image samples used in the README and I'd like not to mix those with images from `detect.py`.

**Comment by pxg0507** [comment]
hi I have the same problem with you how you fix it?
