### ISSUE TITLE
errors in yolo layer

### ISSUE THREAD

**Issue by chenbohua3** [eriklindernoren/PyTorch-YOLOv3#160]
in here https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/6442556dba137eba36ab967d94cf23e81a2c1519/utils/utils.py#L306
the results of `anchor_ious > ignore_thres` will be a tensor that contains either 0 or 1, but this is not indexes to the anchors whose IOU towards label bboxes lower than the thresh. As a result, the` noobj_mask` will be wrongly updated.

**Comment by chenbohua3** [comment]
I have checked this is

**Comment by dreamlxt17** [comment]
> I have checked that this is caused by the tensor type.

hello, I wonder how you fixed this bug?
