### ISSUE TITLE
No object scale idea

### ISSUE THREAD

**Issue by gurkirt** [eriklindernoren/PyTorch-YOLOv3#161]
First thing first, thank you very much for providing such a clean and readable implementation. 

May I ask what is the reason for using such a high scale for no object loss in https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/models.py#L118?

**Comment by developer0hye** [comment]
Do you find the reason?

**Comment by gurkirt** [comment]
no

**Comment by developer0hye** [comment]
have a good day

**Comment by developer0hye** [comment]
I trained and tested on my dataset after changing two weights, obj_scale and noobj_scale.

self.obj_scale = 10
self.noobj_scale = 1

But, I had a bad result...

I hope it helps you

**Comment by ujsyehao** [comment]
you can refer to #295

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
