### ISSUE TITLE
OSError: image file is truncated (7 bytes not processed)

### ISSUE THREAD

**Issue by ghimiredhikura** [eriklindernoren/PyTorch-YOLOv3#162]
It seems there is still some problem with Image loader. 
```
 File "...\PyTorch-YOLOv3\utils\datasets.py", line 86, in __getitem__
    img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
  File "C:\ProgramData\Anaconda3\envs\ghimire\lib\site-packages\PIL\Image.py", line 899, in convert
    self.load()
  File "C:\ProgramData\Anaconda3\envs\ghimire\lib\site-packages\PIL\ImageFile.py", line 236, in load
    len(b))
OSError: image file is truncated (7 bytes not processed)
```
Therefore i'm using cv2 image loader.

**Comment by chuong** [comment]
It's probably you installed Pillow instead of PIL. Try adding these to `datasets.py` file at line 14:

`from PIL import ImageFile`
`ImageFile.LOAD_TRUNCATED_IMAGES = True`

**Comment by ghimiredhikura** [comment]
> It's probably you installed Pillow instead of PIL. Try adding these to `datasets.py` file at line 14:
> 
> `from PIL import ImageFile`
> `ImageFile.LOAD_TRUNCATED_IMAGES = True`

@chuong , Solved

Thank you

**Comment by Donkee** [comment]
The method about `ImageFile.LOAD_TRUNCATED_IMAGES = True` is not useful for me, so I change the code `img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))` to:
`img = transforms.ToTensor()(cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB))`
And it works.

**Comment by Donkee** [comment]
The method about:
```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
is ineffective to me, so I change the code:
`img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))`
to this:
`img = transforms.ToTensor()(cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB))`
and it works.

**Comment by yosunpeng** [comment]
Thinks!

**Comment by kyrie2to11** [comment]
> The method about:
> 
> ```
> from PIL import ImageFile
> ImageFile.LOAD_TRUNCATED_IMAGES = True
> ```
> 
> is ineffective to me, so I change the code: `img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))` to this: `img = transforms.ToTensor()(cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB))` and it works.

This method helps resolve the tricky issue I was facing when using "Image.open()" for image loading. Thank U!

**Comment by Isaac-olu** [comment]
@chuong 
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

This method helped with u2net train.py as well

**Comment by nutsintheshell** [comment]
I see the source code of it, I found users can change LOAD_TRUNCATED_IMAGES. but I don't know why user can change it.
