### ISSUE TITLE
python version ?

### ISSUE THREAD

**Issue by riyaj8888** [eriklindernoren/PyTorch-YOLOv3#165]
which version of python is used in this repo?
f-string error come when i used python 3.5.2 and when i switched to python=3.6.8  i am getting terminatables error...

**Comment by yyx1107** [comment]
> which version of python is used in this repo?
> f-string error come when i used python 3.5.2 and when i switched to python=3.6.8 i am getting terminatables error...

I use python3.6

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.

**Comment by Flova** [comment]
I use python3.8 and 3.9 btw
