### ISSUE TITLE
training yolov3 on coco

### ISSUE THREAD

**Issue by AriesJin** [eriklindernoren/PyTorch-YOLOv3#169]
i training yolov3  on coco, but it is difficult to convergence. About 67 epoch, the map only 0.2.
why? i also use darknet53.conv.74 as the pretrain model and the batchsize is 8

**Comment by ghimiredhikura** [comment]
@AriesJin, @eriklindernoren 

Same here, I trained for 60 epochs, however I didn't used pretrained weights `darknet53.conv.74`, trained from scratch. But he map is only around 18%. 
![image](https://user-images.githubusercontent.com/24696403/57591487-9cda9800-756c-11e9-95da-6436277beea1.png)

It looks like detection have no problem, but classification is not training well. Detection results in sample images are attached below. 
![dog](https://user-images.githubusercontent.com/24696403/57591644-723d0f00-756d-11e9-85c1-29f787c0dd4f.png)
![eagle](https://user-images.githubusercontent.com/24696403/57591651-7bc67700-756d-11e9-8ccf-3935cc108056.png)
![herd_of_horses](https://user-images.githubusercontent.com/24696403/57591663-854fdf00-756d-11e9-9116-6488c39c91c4.png)

![image](https://user-images.githubusercontent.com/24696403/57591666-884acf80-756d-11e9-9e8e-07502a367a4e.png)

**Comment by dagap** [comment]
Any progress on this? I am having the same issue with custom datasets.

**Comment by wojiaozhupengfei** [comment]
I am having the same issue with custom datasets, too.

**Comment by ardeal** [comment]
@AriesJin 
@ghimiredhikura 
@dagap 
@wojiaozhupengfei 


have you solved the problem?
Please see my issue #504
I am experiencing the same problem.
I just clone the code and prepare COCO. nothing is changed in the code. I have trained more than 150 epochs, but the mAP is around 0.28.

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by ardeal** [comment]
Hi All,

On older version(archive branch) of this repo, there might be problem.
on the latest version(master branch) of this repo. There is no problem. I did the following experiment on the latest version of this repo:
Based on the pre-trained model provided by the repo, I customize classes number to 4 following the instruction in the section: [Train Custom Data](https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data). My newly trained model worked correctly.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
