### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by fnwkqwan** [eriklindernoren/PyTorch-YOLOv3#170]
When I computed mAP in train stage, the loss would explode, why did that happened?

**Comment by smendozabarrera** [comment]
Hello, I found a problem with indices in the compute_loss function. The indices calculated for gi and gj are bigger on occasions than the pi0 tensor.

`
Reading labels: 100%|████████████████████████████████| 3000/3000 [00:00<00:00, 10808.02it/s]
               Class    Images   Targets         P         R       mAP        F1
Computing mAP:  44%|██████                                       | 82/188 [17:07<25:31, 14.45s/it]Traceback (most recent call last):
  File "train.py", line 366, in <module>
    multi_scale=opt.multi_scale,
  File "train.py", line 273, in train
    conf_thres=0.1)
  File "/home/jaalkab/Desktop/toolchest/src/P2019/SecurityDetector-RS/src/test.py", line 120, in test
    loss_i, _ = compute_loss(train_out, targets, model)
  File "/home/jaalkab/Desktop/toolchest/src/P2019/SecurityDetector-RS/src/utils/utils.py", line 324, in compute_loss
    pi = pi0[b, a, gj, gi]  # predictions closest to anchors
IndexError: index 15 is out of bounds for dimension 2 with size 10
`

`
:: pi0 DATA ::  <class 'torch.Tensor'> torch.Size([64, 3, 10, 13, 6])  /  64


         :: separated ::
         b =  torch.Size([69]) <class 'torch.Tensor'>
 tensor([ 0,  1,  2,  3,  3,  4,  6,  7,  8, 11, 11, 12, 13, 14, 15, 15, 16, 17, 18, 19, 19, 20, 20, 20, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])
         a =  torch.Size([69]) <class 'torch.Tensor'>
 tensor([2, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 1, 0, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
         gj =  torch.Size([69]) <class 'torch.Tensor'>
 tensor([ 6,  4,  5,  6,  3,  5,  5,  5,  5,  6,  3,  5,  6,  2,  6,  3,  3,  3,  2,  6,  3,  1,  2,  7,  7,  2,  4,  4,  3,  3,  4,  5,  7,  5,  1,  1,  4,  5, 15,  5,  6,  6,  5,  6,  5,  3,  4,  4,  5,  5,  4,  4,  4,  5,  4,  4,  4,  4,  4,  5,  4,  4,  4,  4,  4,  4,  4,  4,  5])
         gi =  torch.Size([69]) <class 'torch.Tensor'>
 tensor([ 6,  6,  8,  7,  4,  3,  6,  4,  6,  4,  7,  6,  4,  3,  4,  7,  5,  6,  5,  4,  7,  2,  8,  3,  9,  5,  4,  5,  6,  6,  7,  6,  7,  9,  2, 10,  6,  8, 37,  6, 10,  5,  4,  6,  5, 10,  6,  5,  6,  3,  9,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6])
`
What is the best way to correct this issue?

Best!

**Comment by Wing-Li-oceanwing** [comment]
I have the same problem

**Comment by PSlearner** [comment]
> I have the same problem

hi, have you figure out the reasons

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
