### ISSUE TITLE
Can the Chinese name be displayed when recognizing?such as“人”，“狗”,THX!

### ISSUE THREAD

**Issue by QQ2737499951** [eriklindernoren/PyTorch-YOLOv3#180]
Can the Chinese name be displayed when recognizing?such as“人”，“狗”,THX!

**Comment by QQ2737499951** [comment]
![222222](https://user-images.githubusercontent.com/33048209/57922410-45248f80-78d2-11e9-9cc7-96a4c421594c.png)
Now it's scrambling

**Comment by Atla11nTa** [comment]
add this in your code can solve it
from pylab import mpl
mpl.rcParams['font.sans-serif'] = ['FangSong']
mpl.rcParams['axes.unicode_minus'] = False

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
