### ISSUE TITLE
Non quadratic images

### ISSUE THREAD

**Issue by GeislerSimon** [eriklindernoren/PyTorch-YOLOv3#186]
Hi,

I was currently trying out this repo and started with some network I trained on darknet with non-quadratic images. Let's say 1024x2048 pixels. Using such a model I do not get any predictions at all. 

While digging a little bit into the code I found the parameter `img_size`. Why is this parameter necessary, since the height and width are also defined in the cfg file? Could somebody give me some pointers where I need to change the code to make things working on non-quadratic images?

Thank you!

**Comment by turboxin** [comment]
hi @GeislerSimon , did you solve this problem?

**Comment by GeislerSimon** [comment]
@turboxin I am not sure anymore. I believe I had some trouble, this is why I switched to this [YOLO implementation](https://github.com/ultralytics/yolov3)
