### ISSUE TITLE
Error in loading state_dict for Darknet

### ISSUE THREAD

**Issue by jun12311** [eriklindernoren/PyTorch-YOLOv3#188]
For some reason there are size mismatches from params from my checkpoint weights from custom data and the current model. 18 vs 255. Any ideas what could be causing this? Does it have to do with my images being png instead of jpg?

	`RuntimeError: Error(s) in loading state_dict for Darknet:`
	`size mismatch for module_list.81.conv_81.weight: copying a param with shape torch.Size([18, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 1024, 1, 1]).`
	`size mismatch for module_list.81.conv_81.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).`
	`size mismatch for module_list.93.conv_93.weight: copying a param with shape torch.Size([18, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 512, 1, 1]).`
	`size mismatch for module_list.93.conv_93.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).`
	`size mismatch for module_list.105.conv_105.weight: copying a param with shape torch.Size([18, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 256, 1, 1]).`
	`size mismatch for module_list.105.conv_105.bias: copying a param with shape torch.Size([18]) from checkpoint, the shape in current model is torch.Size([255]).`

**Comment by sgflower66** [comment]
Can you share your method?
When using the detect.py, I met the similar problem from my checkpoint weights from custom data and the current model. 
but 255 vs 153.
the detail information for config as follows:
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/245

**Comment by JeasonUESTC** [comment]
@sgflower66 Have you solved it? I meeting the same problem.
