### ISSUE TITLE
darknet ,pytorch weight

### ISSUE THREAD

**Issue by jalaldev1980** [eriklindernoren/PyTorch-YOLOv3#189]
Hi @eriklindernoren

I trained my database using darknet (Tiny Yolo v3) and I got the weight file. 
when I tried use the weight file using pytorch, the system is not detecting ? is there any advice ?

Thank you

**Comment by penglongluan** [comment]
@jalaldev1980 did you fixed the problem?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
