### ISSUE TITLE
FileNotFoundError in Windows OS

### ISSUE THREAD

**Issue by sourav164** [eriklindernoren/PyTorch-YOLOv3#192]
I am trying to evaluate the model on COCO test. The following codes -

    python test.py --weights_path weights/yolov3.weights

is generating the following errors -

        Namespace(batch_size=8, class_path='data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
        Compute mAP...
        Detecting objects:   0%|                                                                       | 0/625 [00:00<?, ?it/s]Traceback (most recent call last):
          File "test.py", line 98, in <module>
            batch_size=8,
          File "test.py", line 36, in evaluate
            for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
            for obj in iterable:
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
            return self._process_next_batch(batch)
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
            raise batch.exc_type(batch.exc_msg)
        FileNotFoundError: Traceback (most recent call last):
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
            samples = collate_fn([dataset[i] for i in batch_indices])
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
            samples = collate_fn([dataset[i] for i in batch_indices])
          File "C:\Dump\pt\PyTorch-YOLOv3\utils\datasets.py", line 86, in __getitem__
            img = transforms.ToTensor()(Image.open(img_path).convert('RGB'))
          File "C:\Users\SR\AppData\Local\Continuum\anaconda3\envs\yt\lib\site-packages\PIL\Image.py", line 2652, in open
            fp = builtins.open(filename, "rb")
        FileNotFoundError: [Errno 2] No such file or directory: '/c/Dump/pt/PyTorch-YOLOv3/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

The main issue seems to be the path structure of the Windows OS. Switching to Ubuntu can solve the problem?

    FileNotFoundError: [Errno 2] No such file or directory: '/c/Dump/pt/PyTorch-YOLOv3/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

**Comment by Invokar** [comment]
@sourav164  Hi，I meet the same problem. Have you solved it? although in ubuntu16.04，all are ok.

**Comment by sourav164** [comment]
@Invokar  I tried solve that and without any luck opted for Paperspace (ubuntu 18.04). Trained the model and no issue at all in the new OS.

**Comment by JSitter** [comment]
I'm trying to do the same thing on Ubuntu 18.04. I've followed the instructions given in the README, but still get the following error:
>> python3 test.py --weights_path weights/yolov3.weights
Namespace(batch_size=8, class_path='../data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Compute mAP...
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    batch_size=8,
  File "test.py", line 27, in evaluate
    dataset = ListDataset(path, img_size=img_size, augment=False, multiscale=False)
  File "/media/justin/Datasets/PyTorch-YOLOv3/utils/datasets.py", line 61, in __init__
    with open(list_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/5k.txt'

**Comment by fangbiyi** [comment]
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/312#issue-506344536

**Comment by incredible-john** [comment]
#312 really solved the problems for WINDOWS users

**Comment by ShenZheng2000** [comment]
> I'm trying to do the same thing on Ubuntu 18.04. I've followed the instructions given in the README, but still get the following error:
> 
> > > $> python3 test.py --weights_path weights/yolov3.weights
> > > Namespace(batch_size=8, class_path='../data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
> > > Compute mAP...
> > > Traceback (most recent call last):
> > > File "test.py", line 98, in 
> > > batch_size=8,
> > > File "test.py", line 27, in evaluate
> > > dataset = ListDataset(path, img_size=img_size, augment=False, multiscale=False)
> > > File "/media/justin/Datasets/PyTorch-YOLOv3/utils/datasets.py", line 61, in **init**
> > > with open(list_path, "r") as file:
> > > FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/5k.txt'

 Hi, have you solved this problem? I have the same one. Thanks in advance!
