### ISSUE TITLE
training with single imagee and single class

### ISSUE THREAD

**Issue by dagap** [eriklindernoren/PyTorch-YOLOv3#195]
I am using your custom data to do some training on 1080Ti. After a couple of epochs the training seems to halt. It looks almost like the system is hanging but I am not sure. How long does one epoch typically take with just one image and one class? I was assuming this should be really fast.

**Comment by Xiwang-pge** [comment]
I got the same issue. The machine was hanging out for quite a long time.

**Comment by dagap** [comment]
There is another issue opened about this #206

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
