### ISSUE TITLE
What have you assumed as the origin for image ? (Bottom left or top left)

### ISSUE THREAD

**Issue by andohuman** [eriklindernoren/PyTorch-YOLOv3#198]
I tried to infer from the train image you've provided in custom data but the y is 0.5 (exactly middle) so I don't know what you've assumed as origin.

**Comment by Invokar** [comment]
@andohuman x,y is center coordinate and scale to [0-1]

**Comment by andohuman** [comment]
> @andohuman x,y is center coordinate and scale to [0-1]

Yeah, but does y start from bottom or from the top ? I have annotated csvs where the y axis is like 0 to inf from top to bottom. So, i wanted to know what is the coordinate system being used for this project.

**Comment by jiteshm17** [comment]
If I have my bounding box coordinates as (xmin,ymin,xmax,ymax) , could you please mention how to convert them into the scale required for training Yolov3?
