### ISSUE TITLE
MAP

### ISSUE THREAD

**Issue by nationalflag** [eriklindernoren/PyTorch-YOLOv3#20]
The computation of MAP in test.py actually is precision.

**Comment by wangzhaolei** [comment]
the computation of map
in test.py actually is recall.

**Comment by nationalflag** [comment]
@wangzhaolei   Yes, you are right!

**Comment by xyutao** [comment]
The computation of mAP still seems incorrect. The right way is to compute AP for all instances of each object class separately, and then average AP score. But in the code the mAP is averaged for AP of each image. This would result in a much higher mAP score that the correct one.

**Comment by chijan-nh** [comment]
What is the precision envelope in `utils.utils.compute_ap` ?
If the precision is sorted, then the precision envelope `mpre` is a concatenated array of `np.max(precision)*np.ones(len(mpre)-1)` and `array([0])".
