### ISSUE TITLE
yolov3.weight and darknet53.conv.74 

### ISSUE THREAD

**Issue by qilong-zhang** [eriklindernoren/PyTorch-YOLOv3#201]
what's the difference? could anyone tell me, I'm a little confuse

**Comment by KtK99** [comment]
Other than this confusion over the difference, have you been able to run the test.py without any issues?

**Comment by david-macleod** [comment]
AFAIK darknet53.conv.74.weights contains the weights for the DarkNet network* originally trained for classification on the ImageNet dataset, which is used as the pre-trained feature extractor (backbone) for YOLOv3. To use this for detection the additional weights which are only present in the YOLOv3 network are randomly initialized prior to training.

yolov3.weights contains the weights for the full YOLOv3 network after being trained for detection on the COCO dataset (after being initialised with the darknet53.conv.74 weights).

*darknet53.conv.74.weights refers to the fact that only the weights for the convolutional layers are included, excluding the weights for the final fully connected layer which outputs the class probabilities for classification. There is a separate file called darknet53.weights which includes _all_ the weights.

**Comment by shouryasimha** [comment]
how does it affect the training?

**Comment by USNA2014** [comment]
@david-macleod I'm having issues using yolov3.weights that have been pretrained on the COCO dataset.  I don't want to use darknet53.conv.74.weights since they were pretrained on imagenet's dataset.  Using windows cmd and the correct paths in the below command line, the exe does not start training at all: darknet.exe detector train x64/data/obj.data x64/yolov3-openimages.cfg x64/yolov3-openimages.weights

**Comment by USNA2014** [comment]
If you used yolov3.weights, the model would not train.  I have solved the reason why.  Please check out the link: https://github.com/AlexeyAB/darknet/issues/5012#issuecomment-609596129

**Comment by tetsu-kikuchi** [comment]
We can see a clear explanation in the [web site](https://pjreddie.com/darknet/yolo/) of the original author: 
```
For training we use convolutional weights that are pre-trained on Imagenet. We use weights from the darknet53 model.
```
On the other hand, yolov3.weights is used in the web page to directly detect COCO 80 class objects, so it is a weights as a full COCO object detector.
