### ISSUE TITLE
Training Hangs on Detecting Objects

### ISSUE THREAD

**Issue by harpalsahota** [eriklindernoren/PyTorch-YOLOv3#206]
Training on a custom dataset with the following command:

> python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data --epochs 5 --batch_size 2 --n_cpu 2

Training proceeds for an epoch and then just hangs, see image below:

![Screen Shot 2019-06-14 at 11 13 18](https://user-images.githubusercontent.com/9675427/59502348-77a3b700-8e95-11e9-8482-2681174d9808.png)

Any idea what could be causing the training to hang?

**Comment by harpalsahota** [comment]
So I've isolated the issue to the `while` loop in the `non_max_suppression` method.

`while detections.size(0)` statement in my training never becomes false. Below is some output form the while loop:

```
torch.Size([3824, 7]) <---- detection.size()
torch.Size([3824]) <---- invalid.size()
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
torch.Size([3824])
torch.Size([3824, 7])
```
As you can see the number of invalid detections does not drop. Any idea how I can fix this?

**Comment by yyx1107** [comment]
> 
> 
> Training on a custom dataset with the following command:
> 
> > python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data --epochs 5 --batch_size 2 --n_cpu 2
> 
> Training proceeds for an epoch and then just hangs, see image below:
> 
> ![Screen Shot 2019-06-14 at 11 13 18](https://user-images.githubusercontent.com/9675427/59502348-77a3b700-8e95-11e9-8482-2681174d9808.png)
> 
> Any idea what could be causing the training to hang?

Maybe the path of your datasets is wrong.

**Comment by YangHangWu** [comment]
same problem anyone have already solved it?

**Comment by wojiaozhupengfei** [comment]
while detections.size(0):
            large_overlap = bbox_iou(detections[0, :4].unsqueeze(0), detections[:, :4]) > nms_thres 

            # https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/315
            if not any(large_overlap):
                detections = np.delete(detections, 0, 0)
                continue

            label_match = detections[0, -1] == detections[:, -1]

**Comment by YangHangWu** [comment]
![image](https://user-images.githubusercontent.com/39996866/69645694-8aa3ef80-10a1-11ea-817b-cd2c79dcf321.png)
still hang on this state any soluation?

**Comment by YangHangWu** [comment]
![image](https://user-images.githubusercontent.com/39996866/69645859-d060b800-10a1-11ea-9516-89781ab1ede6.png)
trying to print the size but it seems the program not even running in the while loop

**Comment by YangHangWu** [comment]
![image](https://user-images.githubusercontent.com/39996866/69646295-81675280-10a2-11ea-9c02-e899e4154710.png)
![image](https://user-images.githubusercontent.com/39996866/69646319-8b895100-10a2-11ea-8f9f-b0ad17c9c2be.png)

It seems like I stuck before the for loop because the batch_i didn't print out

**Comment by abhiagwl4262** [comment]
Should this issue be coming for all the users using this repo ?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
