### ISSUE TITLE
In ListDataset, collate_fn in utils/datasets.py , you're resizing the image. Aren't you also supposed to resize the bounding boxes ?

### ISSUE THREAD

**Issue by andohuman** [eriklindernoren/PyTorch-YOLOv3#207]

**Comment by SWHL** [comment]
I also have the same doubts about this issue.

**Comment by EddieEduardo** [comment]
I am also confused about the shape of targets in function collate_fn, it seems to be (batchsize, w, h) where it is used in the following part, but if I just read collate_fn , I think it would be a two dimensional tensor, can someone tell me if I'm wrong? Or should I add unsqueeze(0) at the end of each channel of targets?

**Comment by did85** [comment]
No need to resize because they are normalized between 0-1. Resizing image does not change xy or wh of the bboxes relative to the image.
