### ISSUE TITLE
an error when running get_coco_dataset.sh

### ISSUE THREAD

**Issue by Brizel** [eriklindernoren/PyTorch-YOLOv3#21]
when i try to run :

         sh  get_coco_dataset.sh

there comes an error:

         Syntax error: "(" unexpected

**Comment by eriklindernoren** [comment]
Not sure why this happens but `bash get_coco_dataset.sh` works for me. Can you try that command?

**Comment by Brizel** [comment]
thanks a lot . The problem has been perfectly solved.
