### ISSUE TITLE
Tensor size of the target

### ISSUE THREAD

**Issue by herleeyandi** [eriklindernoren/PyTorch-YOLOv3#214]
Hello @eriklindernoren thank you for your implementation. I need an explanation of this implementation work. I tried to adding a class from pretrained coco yolov3. I follow the step in official YOLO darknet implementation. I assume that this pytorch implementation is also taking (`.cfg` file for architecture and training, the `.data` files, and the `.name` files). I also change the filter number in .cfg file using the proper formula as the darknet implementation tell me.  I successfully run it in darknet implementation. However, when I move to this code I have a problem in `RuntimeError: CUDA error: device-side assert triggered` so  I have two questions.

1) What is the target size?
I try to print the input size and targets size then find that no batch dimension in the target size. what will happen if the batch is greater than 1? for example I have the gt file consist of 9 objects so my target size is 9x6 and should be 1x9x6 since I have only 1 batch. but I end up like only have 9x6 size.

2) Should I follow the YOLO ground truth format or raw format?
raw in here means is the real bounding boxes for example 
`[class, x1, y1, x2, y2] = [2 254 169 357 216]`
or the YOLO version like 
`[class, x, y, w,h] = [2 0.734375 0.46274038461538464 0.24759615384615385 0.11298076923076923]`
This point I assume you follow the YOLO format.

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
