### ISSUE TITLE
torch.filp(images, [-1])  expected flip dims axis >= 0

### ISSUE THREAD

**Issue by nobody-cheng** [eriklindernoren/PyTorch-YOLOv3#215]
augmentations.py  file
images = torch.flip(images, [-1])
RuntimeError:  expected flip dims axis >= 0, but got min flip dims=-1

fix: images = torch.flip(images, [0, 1]) ???

**Comment by yyyyykp** [comment]
> augmentations.py file
> images = torch.flip(images, [-1])
> RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1
> 
> fix: images = torch.flip(images, [0, 1]) ???

have u solved this promble？i got the same error.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
