### ISSUE TITLE
list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by OwlWisdom** [eriklindernoren/PyTorch-YOLOv3#216]
#test.py
def evaluate(model, path, iou_thres, conf_thres, nms_thres, img_size, batch_size):
    model.eval()

    # Get dataloader
    dataset = ListDataset(path, img_size=img_size, augment=False, multiscale=False)
    
    dataloader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, shuffle=False, num_workers=1, collate_fn=dataset.collate_fn
    )

    Tensor = torch.cuda.FloatTensor if torch.cuda.is_available() else torch.FloatTensor

    labels = []
    sample_metrics = []  # List of tuples (TP, confs, pred)
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
       
        # Extract labels
        labels += targets[:, 1].tolist()
        print(labels)
        # Rescale target
        targets[:, 2:] = xywh2xyxy(targets[:, 2:])
        targets[:, 2:] *= img_size

        imgs = Variable(imgs.type(Tensor), requires_grad=False)

        with torch.no_grad():
            outputs = model(imgs)
            outputs = non_max_suppression(outputs, conf_thres=conf_thres, nms_thres=nms_thres)

        sample_metrics += get_batch_statistics(outputs, targets, iou_threshold=iou_thres)

    # Concatenate sample statistics
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
    precision, recall, AP, f1, ap_class = ap_per_class(true_positives, pred_scores, pred_labels, labels)

    return precision, recall, AP, f1, ap_class

Total loss 19.913291931152344
---- ETA 0:00:00

---- Evaluating Model ----
Detecting objects:   0%|                                 | 0/55 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    batch_size=8,
  File "/home/yang/workspace/YOLO/PyTorch-YOLOv3-master/test.py", line 40, in evaluate
    labels += targets[:, 1].tolist()
TypeError: list indices must be integers or slices, not tuple

**Comment by OwlWisdom** [comment]
That's my problem, can you help me ?

**Comment by QZ-cmd** [comment]
Could your problem be solved, I also encountered a similar problem
TypeError: tuple indices must be integers or slices, not tuple

**Comment by githubsumanlm10** [comment]
I have the same problem, Any help ??

**Comment by tw0226** [comment]
@OwlWisdom @QZ-cmd , @githubsumanlm10 
I sovled the problem.
In my case, I didn't use given dataloader, customize dataloader. 
the reason is that it doesn't support batch images in real.
original target has 2-d list ([:, :]). but, through batch dataloader, it became [batch, [ :, :]].
So if you wanna use, detach batch dimension like using one more 'for'.  
In example, 
`for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
    labels += targets[:, 1].tolist()
    print(labels)
    # Rescale target
    targets[:, 2:] = xywh2xyxy(targets[:, 2:])
    targets[:, 2:] *= img_size`

to

`for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc="Detecting objects")):
    for batch_i_in, (_, imgs_in_batch, imgs_in_target) in enumerate(zip(imgs, targets)):
    labels += targets[:, 1].tolist()
    print(labels)
    # Rescale target
    targets[:, 2:] = xywh2xyxy(targets[:, 2:])
    targets[:, 2:] *= img_size`

i'm different from your source. but if you're in trouble, at least try this.
:)
