### ISSUE TITLE
custom training needs tensorflow

### ISSUE THREAD

**Issue by adidasnike90** [eriklindernoren/PyTorch-YOLOv3#221]
Given its a pytorch version, why do we still need tensorflow for training?

**Comment by sxudai** [comment]
same question

**Comment by zrl4836** [comment]
you can see logger.py .it only used for logs.

**Comment by peaceiris** [comment]
TensorFlow is imported and used for only logging.

https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/80c93a1c5489bf6d16745d1390e3bb4ba87dfb17/utils/logger.py#L1-L17

**Comment by haoyanggit** [comment]
should I install tensorflow in my conda environment?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
