### ISSUE TITLE
A bug in utils utils.py build_targets

### ISSUE THREAD

**Issue by renzhenwang** [eriklindernoren/PyTorch-YOLOv3#224]
Hi，thanks for your work!
I have met a bug in training with my own custom dataset, when the code running at  [Epoch 0/100, Batch 321/1223]. The bug was:
 line 306, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
IndexError: index 13 is out of bounds for dimension 1 with size 12

I have run several times and similar errors have always been come, and what's wrong? Thank you!

**Comment by ghimiredhikura** [comment]
Hi @renzhenwang, 

I think you encounter this error when some of the image in your dataset do not have labeled objects. Make sure there exists at least one bounding box per image. Hope this will help! 

Best,
Deepak

**Comment by fyting** [comment]
Has the problem been solved?

**Comment by felixplum** [comment]
Hi, 

to me that happened when boxes were labeled as being slightly larger than 1.

Solution:
1. Check your labels!
2. Lazy solution: In https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/utils.py#L290

do instead 

`gxy = torch.clamp(target_boxes[:, :2], 0, nG-1e-5)`.

Cheers, 
Felix
