### ISSUE TITLE
Incorporating False Positives Into Training

### ISSUE THREAD

**Issue by tobal101** [eriklindernoren/PyTorch-YOLOv3#226]
Hello,

I am fairly new to networks, and started to use YOLO for detecting objects in big images (30,000x15,000) using a single class. When testing YOLO on 416x416 images, all with the desired object in them, it preforms almost flawlessly, but if I feed the network 416x416 images that were cut from the larger image, most without the desired object, it creates hundreds of false positives. To pour salt onto the open wound, the network is also more confident about the false positives than the objects it does detect.

My question is how do I reduce the number of false positives, or how do I increase the network's confidence for the objects it correctly identifies. How do I teach the network that false positives are wrong?

I have tried adding a class for false positives and ignore any detection predicted to be one, but that only worsened the results. I have also tried feeding the network empty annotations in hopes that no annotation meant do not detect, yet I was met with similar results. 

Is there another approach, or are the previous methods successful when executed in a certain manner? Thanks in advance.

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
