### ISSUE TITLE
how can i apply my own train on video file 

### ISSUE THREAD

**Issue by sub2sub2** [eriklindernoren/PyTorch-YOLOv3#228]
I get weights file by training my own dataset, so I can test it to image file by using detect.py.
But I want to apply this for video file and generate output video. So how can I revise detect.py ?

please answer or revsise code. thanks

**Comment by Flova** [comment]
You can split your video into the different frames using ffmpeg, run detect.py on the folder and then merge them to a video using ffmpeg.
