### ISSUE TITLE
Some problems with saving weights

### ISSUE THREAD

**Issue by Brizel** [eriklindernoren/PyTorch-YOLOv3#23]
I've been followed this repo for about a week and make it work to start training on my own data. But when I tried to save weights, I got an error:

       AttributeError: 'Darknet' object has no attribute 'seen' 

I checked in models.py. Unfortunately, self.seen and self.header_info are missing parameters in class Darknet. I looked up some materials and make them declared as:

    self.seen = 0
    self.header_info = torch.IntTensor([0,0,0,0,0])

add two sentences in save_weights:

        header = self.header_info
        header = header.numpy()

and  changed self.header_info.tofile(fp) into header_info.tofile(fp). After all these modification, weights can be saved and loaded. But when I loaed them in detect.py , no detections can be made.
 
I  wondered this problem is caused either my modification on seen and header_info or too few epoches. It'll be really nice of you to offer me some suggestion. Thanks for your time.

**Comment by eriklindernoren** [comment]
Yes, I will push a fix for this later today.

**Comment by Brizel** [comment]
Using the weights I trained , I'll get :

Performing object detection:
	+ Batch 0, Inference Time: 0:00:00.262377
	+ Batch 1, Inference Time: 0:00:00.026853
	+ Batch 2, Inference Time: 0:00:00.032170
	+ Batch 3, Inference Time: 0:00:00.008161
	+ Batch 4, Inference Time: 0:00:00.007893
	+ Batch 5, Inference Time: 0:00:00.008063
	+ Batch 6, Inference Time: 0:00:00.007226
	+ Batch 7, Inference Time: 0:00:00.007327
	+ Batch 8, Inference Time: 0:00:00.007915
	+ Batch 9, Inference Time: 0:00:00.008136
	+ Batch 10, Inference Time: 0:00:00.008143
	+ Batch 11, Inference Time: 0:00:00.006397
	+ Batch 12, Inference Time: 0:00:00.006317
	+ Batch 13, Inference Time: 0:00:00.005665
	+ Batch 14, Inference Time: 0:00:00.005724

Does this means no prediction has been made? The loss is dropping during the training, I used a weight which has 0.3 total loss to predict. I wonder if there is an issue in the loss function or somewhere else.

**Comment by eriklindernoren** [comment]
Hi, this is fixed in 6727086. Unfortunately I have yet to get the model to converge to the same results as the authors during training.
