### ISSUE TITLE
img_size must be equal 416 when I evaluate

### ISSUE THREAD

**Issue by hnsywangxin** [eriklindernoren/PyTorch-YOLOv3#232]
Hello, the parameter of evaluate function  which is  img_size must be equal to 416, I have changed to other values ,such as 720 or 518,it will casued error :
`RuntimeError:invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307` 
My img shape is 1920x1200x3
Anyone can help me?thanks!

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.

**Comment by NJUEELJN** [comment]
I have similar problems due to changing class numbers, have U solved this pls?

**Comment by Flova** [comment]
Could you open a separate issue with a detailed description regarding this?
