### ISSUE TITLE
target dimension and size when going through YOLOLayer

### ISSUE THREAD

**Issue by JamMochi** [eriklindernoren/PyTorch-YOLOv3#234]
Hi, I am currently manually inputting a target into the YOLOLayer, but I'm running into some issues. So I'm posting here to see if anyone know the target tensor dimension when entering the YOLO detection layer. I'm trying to do some tweaking with YOLOv3 and would appreciate the help.

formats i have tried: (class, last 4 bbox coordinates)
0 0.41125 0.6675 0.16625 0.331666

and this (index, class, last 4 bbox coordinates)
1 0 0.41125 0.6675 0.16625 0.331666

300     # Set masks
301     obj_mask[b, best_n, gj, gi] = 1
302     noobj_mask[b, best_n, gj, gi] = 0

RuntimeError: index 1 is out of bounds for dim with size 1

**Comment by nathasha-naranpanawa** [comment]
Hi, did you find the correct format for the target?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
