### ISSUE TITLE
Training Error module_def["classes"] empty

### ISSUE THREAD

**Issue by smartdanny** [eriklindernoren/PyTorch-YOLOv3#238]
When training with my own dataset (actually just a subset of coco) with only 1 class, I get an error that module_def["classes"] is empty and cant be casted to an int:

`Traceback (most recent call last):
  File "train.py", line 54, in <module>
    class_names = load_classes(data_config["names"])
  File "/home/shatz/Desktop/PyTorch-YOLOv3/models.py", line 241, in __init__
    self.hyperparams, self.module_list = create_modules(self.module_defs)
  File "/home/shatz/Desktop/PyTorch-YOLOv3/models.py", line 75, in create_modules
    num_classes = int(module_def["classes"])
ValueError: invalid literal for int() with base 10: ''`

My classes.names file only has 1 line in it. Can anyone help with this?

**Comment by smartdanny** [comment]
Sorry, it was my fault. When I created the custom config file I forgot to specify number of classes

**Comment by JunhoYi** [comment]
@smartdanny 
I have the same problem.
I set the number with shell scripts, which files did you fix?
