### ISSUE TITLE
Does anyone achieve the speed like the author repos?

### ISSUE THREAD

**Issue by chunniunai220ml** [eriklindernoren/PyTorch-YOLOv3#239]
when I test the detect.py with yolov3.weights in 1080Ti(8G),the inference time is about 50-60ms. is it normally? I can not impelement the repo get 74FPS as @eriklindernoren  says in README.md

**Comment by felixplum** [comment]
I'm at around 20ms (as opposed to 5ms using plain Darknet) on a GTX1060. Do you have CUDNN installed?

**Comment by chunniunai220ml** [comment]
@felixplum    I have installed. I have no idea about the reason why I can  not achieve the speed. when it test on V100 about 23FPS
