### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Darknet:

### ISSUE THREAD

**Issue by lyjslay** [eriklindernoren/PyTorch-YOLOv3#245]
i successfulliy trained my own datasets and get the "best.pt",but when i use it to detect,it gives me Runtimerror:
Traceback (most recent call last):
  File "detect.py", line 144, in <module>
    output=opt.output)
  File "detect.py", line 39, in detect
    model.load_state_dict(torch.load(weights, map_location=device)['model'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 837, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Darknet:
        size mismatch for module_list.81.conv_81.weight: copying a param with shape torch.Size([255, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 1024, 1, 1]).
        size mismatch for module_list.81.conv_81.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
        size mismatch for module_list.93.conv_93.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 512, 1, 1]).
        size mismatch for module_list.93.conv_93.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
        size mismatch for module_list.105.conv_105.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
        size mismatch for module_list.105.conv_105.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).

i have searched it on the internet,but haven't solve it,by the way ,i correctly modified the cfg file

**Comment by yyx1107** [comment]
I have met the problem ,but I tried for twice and it was ok.

**Comment by Avan-2608** [comment]
I have also encountered the same problem.

**Comment by sgflower66** [comment]
I have also encountered the same problem.
I correctly modified the cfg file such as:
    parser.add_argument("--image_folder", type=str, default="data/samples", help="path to dataset")
    parser.add_argument("--model_def", type=str, default="config/yolov3-custom.cfg", help="path to model definition file")
    parser.add_argument("--weights_path", type=str, default="checkpoints/yolov3_ckpt_18.pth", help="path to weights file")#weights/yolov3.weights   checkpoints/yolov3_ckpt_13.pth
    parser.add_argument("--class_path", type=str, default="data/custom/classes.names", help="path to class label file")

and met the same problem:

	size mismatch for module_list.81.conv_81.weight: copying a param with shape torch.Size([255, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 1024, 1, 1]).
	size mismatch for module_list.81.conv_81.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([153]).
	size mismatch for module_list.93.conv_93.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 512, 1, 1]).
	size mismatch for module_list.93.conv_93.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([153]).
	size mismatch for module_list.105.conv_105.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([153, 256, 1, 1]).
	size mismatch for module_list.105.conv_105.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([153]).


my environment:
python3.6.3, pytorch1.0

**Comment by JeasonUESTC** [comment]
I miss the same problem. So have you solved it ?

**Comment by ChristopherSTAN** [comment]
For me, I just check the cfg file. Make sure cfg is the same (train and test).
