### ISSUE TITLE
Calculation of the detection_mask can be simplified

### ISSUE THREAD

**Issue by v-iashin** [eriklindernoren/PyTorch-YOLOv3#247]
I think this line
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/models.py#L209

can be simplified to
```
detected_mask = conf50 * class_mask
```

Why?
1. `tconf` is the same as `obj_mask` but of a different type (`float`);
2. `obj_mask` is the same as `class_mask` but it is "less strict": `obj_mask` contains 1s even on the positions where the predicted label doesn't match the ground truth label.
3. Therefore, `class_mask * tconf = class_mask`

**Comment by gaojunbin** [comment]
> I think this line
> 
> https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/models.py#L209
> 
> can be simplified to
> 
> ```
> detected_mask = conf50 * class_mask
> ```
> 
> Why?
> 
> 1. `tconf` is the same as `obj_mask` but of a different type (`float`);
> 2. `obj_mask` is the same as `class_mask` but it is "less strict": `obj_mask` contains 1s even on the positions where the predicted label doesn't match the ground truth label.
> 3. Therefore, `class_mask * tconf = class_mask`

Hello. I agree with you.  I tested for many times to compare the output between ```detected_mask = conf50 * class_mask * tconf``` and ```detected_mask2 = conf50 * class_mask```. As expected, they are always the same.

**Comment by Flova** [comment]
Could someone provide a pr for this?

**Comment by v-iashin** [comment]
I can
