### ISSUE TITLE
Question: what is the model footrprint

### ISSUE THREAD

**Issue by Borda** [eriklindernoren/PyTorch-YOLOv3#249]
Hello @eriklindernoren, I found interesting to see reported processing speed and precision. Could you pls also share the model footprint, how much memory it requires runing on GPU and so if it possible to run multiple models in parallel? Thx

**Comment by felixplum** [comment]
You'll find benchmarks in the original yolov3 paper. The original Darknet implementation in C is around 4x faster than the PyTorch variant in my experience - using TensorRT or TVM might get you in the same ballpark, though. A useful heuristic to predict FPS is to look at the FLOPS/s of the hardware used in the available benchmarks and use it to convert to your target hardware.
And easiest and most accurate is to just git pull & try it out yourself (use e.g. `nvidia-smi` for memory footprint, timings are already printed).

As for multiple models on the same GPU: Depending on your application, you might benefit from using a single model with shared weights, and just use specialized branches for solving the different tasks. 

Cheers and happy research!
Felix
