### ISSUE TITLE
Incorrect bounding box coordinates?

### ISSUE THREAD

**Issue by Robylyon93** [eriklindernoren/PyTorch-YOLOv3#25]
Hi, in [utils.py](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/utils/utils.py#L34), when transforming from center and width to the exact coordinates of box2, you do the following operation:
`b2_x1, b2_x2 = box2[:, 0] - box1[:, 2] / 2, box2[:, 0] + box1[:, 2] / 2`
`b2_y1, b2_y2 = box2[:, 1] - box1[:, 3] / 2, box2[:, 1] + box1[:, 3] / 2`
but I think it should be:
`b2_x1, b2_x2 = box2[:, 0] - box2[:, 2] / 2, box2[:, 0] + box2[:, 2] / 2`
`b2_y1, b2_y2 = box2[:, 1] - box2[:, 3] / 2, box2[:, 1] + box2[:, 3] / 2`
since the width and height are referred to the second box. Am I right or am I missing something? Thanks in advance!

**Comment by eriklindernoren** [comment]
You're exactly right. A fix will be pushed later today.

**Comment by eriklindernoren** [comment]
It's fixed in 6727086.
