### ISSUE TITLE
Potential padding issue

### ISSUE THREAD

**Issue by felixplum** [eriklindernoren/PyTorch-YOLOv3#255]
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/datasets.py#L114-L117

Shouldn't the x and y coordinates be influenced only by the left (pad[0]) and top (pad[2]) padding respectively?

**Comment by qiuhuan** [comment]
Yes, you are right, I think.

**Comment by wondervictor** [comment]
same question

**Comment by pppplin** [comment]
+1

**Comment by Quintus-Zhang** [comment]
Yep

**Comment by pandalgx** [comment]
Yes, I think you are right, and because here pad[0] == pad[1], pad[2] == pad[3], so the result doesn't matter.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
