### ISSUE TITLE
How to change the size of output image?

### ISSUE THREAD

**Issue by azikk** [eriklindernoren/PyTorch-YOLOv3#264]
I found that no matter how big Img I put, the output is 496x279 in detect.py
How could I change it?
thanks

**Comment by xiayanqian** [comment]
change the line in the detect.py
[https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/detect.py#L140](url)
to
`plt.savefig(f"output/{filename}.png",dpi=300, bbox_inches="tight", pad_inches=0.0)`
You can change the dpi parameter,the detect procedure my be much slower though.

**Comment by QuentinAI** [comment]
> change the line in the detect.py
> https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/detect.py#L140
> 
> 
> to
> `plt.savefig(f"output/{filename}.png",dpi=300, bbox_inches="tight", pad_inches=0.0)`
> You can change the dpi parameter,the detect procedure my be much slower though.

Thanks. But how can I change the output size the same as the input one?

**Comment by hongjianyuan** [comment]
> > 更改detect.py中的行
> > https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/detect.py#L140
> > 
> > 到
> > `plt.savefig(f"output/{filename}.png",dpi=300, bbox_inches="tight", pad_inches=0.0)`
> > 您可以更改dpi参数，但是检测程序却要慢得多。
> 
> 谢谢。但是，如何更改输出大小与输入大小相同？

Did you solve it?

**Comment by Flova** [comment]
You can adjust the image size in the `.cfg` file. Note that the image size needs to be in a square aspect ratio internally.
