### ISSUE TITLE
Convert *.pth to *.weights?

### ISSUE THREAD

**Issue by hank-nguyen** [eriklindernoren/PyTorch-YOLOv3#272]
I would like to convert checkpoint file *.pth to original darknet *.weights. Many thanks.

**Comment by realtainyi** [comment]
you can refer to yolov3 project of    github ultralytics

**Comment by LifeIsSoSolong** [comment]
> you can refer to yolov3 project of github ultralytics

thanks ,I try that but failed. Because the type of this project's .pth is different from ultralytics's .pth   
So , run convert will counter error.

I want to convert this project's .pth to darknet's .weights ,anyone else have some advice?

**Comment by LifeIsSoSolong** [comment]
> I would like to convert checkpoint file *.pth to original darknet *.weights. Many thanks.

Hello , Do you complete the convert from .pth to .weights?
I try to load .pth and save to .weights using:
model.load_state_dict(torch.load(pth))
 model.save_darknet_weights(weights_path) 
but when using the converted weights in darknet ,the detect result is None.
You have some advice?

**Comment by oscarzasa** [comment]
Hi,
Has anyone achieved converting the files?

**Comment by penglongluan** [comment]
@LifeIsSoSolong @oscarzasa @hank-nguyen   did you convert checkpoint file *.pth to original darknet *.weights completed?

**Comment by oscarzasa** [comment]
@penglongluan No succesfully, not yet.

**Comment by Flova** [comment]
You can load the model in an ipython and call the convert to darknet function.
