### ISSUE TITLE
The data type in labes?

### ISSUE THREAD

**Issue by caesar-yabo** [eriklindernoren/PyTorch-YOLOv3#273]
Hi,everyone! I wonder the data in the labe.txt
is it   label_id  center_x  center_y  width height
or other types?
please tell me,Thank you.
I'm training myself dataset.Thanks

**Comment by whyz070205** [comment]
May be the following:
label_id_0 center_x_0 center_y_0 width_0 height_0
label_id_1 center_x_1 center_y_1 width_1 height_1
...

**Comment by Damon2019** [comment]
Hello, did you solve it?

**Comment by Flova** [comment]
This is described in the readme.
