### ISSUE TITLE
How to use Tensorboard to see the progress of training?

### ISSUE THREAD

**Issue by Findlazyfriend** [eriklindernoren/PyTorch-YOLOv3#276]
### **when I follow this step：**
_Track training progress in Tensorboard:
Initialize training
Run the command below
Go to http://localhost:6006/
`$ tensorboard --logdir='logs' --port=6006`_

### **the result is ：**
_TensorBoard
scalars 
Inactive 
Show data download links
Ignore outliers in chart scaling
Tooltip sorting method:
Smoothing
weight 
Horizontal Axis
steprelativewall 
Runs
Write a regex to filter runs 
Toggle All Runs 
Filter tags (regular expressions supported) 
cls_1 1 
cls_1 
cls_2 1 
cls_2 
cls_3 1 
cls_acc_1 1 
cls_acc_2 1 
cls_acc_3 1 
conf_1 1 
conf_2 1 
conf_3 1 
conf_noobj_1 1 
conf_noobj_2 1 
conf_noobj_3 1 
conf_obj_1 1 
conf_obj_2 1 
conf_obj_3 1 
h_1 1 
h_2 1 
h_3 1 
loss 1 
loss_1 1 
loss_2 1 
loss_3 1 
precision_1 1 
precision_2 1 
precision_3 1 
recall50_1 1 
recall50_2 1 
recall50_3 1 
recall75_1 1 
recall75_2 1 
recall75_3 1 
w_1 1 
w_2 1 
w_3 1 
x_1 1 
x_2 1 
x_3 1 
y_1 1 
y_2 1 
y_3 1_ 

**I don't know how to see the result of training,whether i need to add some code???**

**Comment by coolmarat** [comment]
all of this is links. Just click it and it will rolldown and show you statistics.
