### ISSUE TITLE
error while test 

### ISSUE THREAD

**Issue by 1518136851** [eriklindernoren/PyTorch-YOLOv3#284]
$ python test.py --weights_path weights/yolov3.weights
Detecting objects: 0it [00:01, ?it/s]
Namespace(batch_size=8, class_path='data/coco.names', conf_thres=0.001, data_config='config/coco.data', img_size=416, iou_thres=0.5, model_def='config/yolov3.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Compute mAP...
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    batch_size=8,
  File "test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by JeasonUESTC** [comment]
Hi,  I miss to the same problem and have you solve this problem?

**Comment by ramondoo** [comment]
if len(sample_metrics) > 0:
        true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
        precision, recall, AP, f1, ap_class = ap_per_class(true_positives, pred_scores, pred_labels, labels)
        assert len(ap_class) == len(AP)
    else:
        ap_class = np.unique(labels).astype("int32")
        precision = np.zeros(len(ap_class), dtype=np.float)
        recall = precision
        AP = precision
        f1 = 2 * precision * recall / (precision + recall + 1e-16)

**Comment by summeryumyee** [comment]
Thank you ~~~

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
