### ISSUE TITLE
How to train with mult gus

### ISSUE THREAD

**Issue by Hanson0910** [eriklindernoren/PyTorch-YOLOv3#290]
When i train with mult gpus, it occus AttributeError: 'DataParallel' object has no attribute 'load_darknet_weights'

**Comment by yangzhaonan18** [comment]
load_darknet_weight 不是 pytorch的标志库，所以不能直接使用多GPU加载权重
兄弟，多GPU训练，你弄好对了吗？

**Comment by ywatanabe1989** [comment]
I implemented multi-gpu version.
We need custom data parallel construction since the number of GT bboxes and predicted ones are not predicted at all.
https://github.com/ywatanabe1989/PyTorch-gaussian-YOLOv3-1D/

**Comment by ujsyehao** [comment]
you can refer to https://github.com/ujsyehao/yolov3-multigpu

**Comment by Flova** [comment]
Duplicate of #520
