### ISSUE TITLE
How to conver model to onnx?

### ISSUE THREAD

**Issue by AnmachenGuo** [eriklindernoren/PyTorch-YOLOv3#291]

**Comment by AlexKaravaev** [comment]
Maybe this will help https://medium.com/styria-data-science-tech-blog/running-pytorch-models-in-production-fa09bebca622 .

**Comment by JustinLJun** [comment]
@AlexKaravaev  hi, i can not open this link, and i need to conver model to onnx. Tell me how to do, thank you~

**Comment by cqray1990** [comment]
@lmo-aiot did you convert to onnx successlly?

**Comment by futureflsl** [comment]
article  https://medium.com/styria-data-science-tech-blog/running-pytorch-models-in-production-fa09bebca622  can be seen this url:
https://blog.csdn.net/FL1623863129/article/details/109900219

**Comment by Flova** [comment]
I will have a look at this and provide a description in the README
