### ISSUE TITLE
why  noobj_scale/obj_scale = 100 ??

### ISSUE THREAD

**Issue by CaoWGG** [eriklindernoren/PyTorch-YOLOv3#295]
why  noobj_scale/obj_scale = 100 ??

**Comment by ujsyehao** [comment]
When you train 1 epoch or more, you can find:
loss-obj : 1.95
loss-noobj: 0.01
loss-noobj x 100: 0.87
So the scale factor balances the two loss.

**Comment by CaoWGG** [comment]
@ujsyehao 
Thank you for your answer
