### ISSUE TITLE
.pth file to .weights file

### ISSUE THREAD

**Issue by oscarzasa** [eriklindernoren/PyTorch-YOLOv3#299]
Hi,
Does anyone know if there is a way to convert the .pth checkpoint file to a .weights file like the ones Darknet uses to perform its inference? Thanks

**Comment by longyueying** [comment]
I think you can use model’s state_dict to convert the .pth checkpoint file to a .weights file

**Comment by JsBlueCat** [comment]
> state_dict

how can it be done ? i also need to convert .pth to .weights

**Comment by iot-hunter** [comment]
@JsBlueCat  in class Darknet have a function  save_darknet_weights(self, path, cutoff=-1) to do this!!! i think this will help you

**Comment by coolmarat** [comment]
@iot-hunter, I'm newbie in python. Can you explain in more details?

**Comment by Khaivdo** [comment]
This should solve the problem, just change the path "checkpoints/yolov3_ckpt_24.pth" to ur own one 
```
    # Initiate model
    model = Darknet(opt.model_def).to(device)
    model.load_state_dict(torch.load("checkpoints/yolov3_ckpt_24.pth", map_location=torch.device('cpu')))
    Darknet.save_darknet_weights(model, 'newYolov3.weights', cutoff=-1)
    if opt.weights_path.endswith(".weights"):
        # Load darknet weights
        model.load_darknet_weights('newYolov3.weights')
    else:
        # Load checkpoint weights
        model.load_state_dict(torch.load(opt.weights_path))`
```

**Comment by aarkey81** [comment]
@oscarzasa, @JsBlueCat  Open train.py and replace the code as under. Also, replace "checkpoints/yolov3_ckpt_99.pth" by your .pth file path. Thereafter, start training again by using cmd "python train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data" and a new weight file named newYolov3.weights will be created after completion of 1 epoch. Stop the training after 1 epoch as your weight file will be ready. Credit @Khaivdo 
# Initiate model
    model = Darknet(opt.model_def).to(device)
    model.apply(weights_init_normal)
    model.load_state_dict(torch.load("checkpoints/yolov3_ckpt_99.pth", map_location=torch.device('cpu')))
    Darknet.save_darknet_weights(model, 'backup/newYolov3.weights', cutoff=-1)
    # If specified we start from checkpoint
    if opt.pretrained_weights:
        if opt.pretrained_weights.endswith(".weights"):
            model.load_darknet_weights(opt.pretrained_weights)
        else:
            model.load_state_dict(torch.load(opt.pretrained_weights))

**Comment by summeryumyee** [comment]
mark

**Comment by PoojanPanchal** [comment]
was anyone able to convert .pth file to .weights ??? please anyone can provide proper solution that where to put the code given by @LContini91 and @aarkey81 ???

**Comment by aarkey81** [comment]
> was anyone able to convert .pth file to .weights ??? please anyone can provide proper solution that where to put the code given by @LContini91 and @aarkey81 ???

Create a new python file, import all the requirements and write the following lines in them

model = Darknet("your .cfg file")

model.load_state_dict(torch.load("your_ckpt.pth", map_location=torch.device('cpu'))) # for loading model on cpu

model.save_weights(savedfile='your_ckpt.weights', cutoff=0)
print("successfully converted .pth to .weights")

Hopefully it will work for you

**Comment by aarkey81** [comment]
> > @oscarzasa, @JsBlueCat Open train.py and replace the code as under. Also, replace "checkpoints/yolov3_ckpt_99.pth" by your .pth file path. Thereafter, start training again by using cmd "python train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data" and a new weight file named newYolov3.weights will be created after completion of 1 epoch. Stop the training after 1 epoch as your weight file will be ready. Credit @Khaivdo
> > # Initiate model
> > ```
> > model = Darknet(opt.model_def).to(device)
> > model.apply(weights_init_normal)
> > model.load_state_dict(torch.load("checkpoints/yolov3_ckpt_99.pth", map_location=torch.device('cpu')))
> > Darknet.save_darknet_weights(model, 'backup/newYolov3.weights', cutoff=-1)
> > # If specified we start from checkpoint
> > if opt.pretrained_weights:
> >     if opt.pretrained_weights.endswith(".weights"):
> >         model.load_darknet_weights(opt.pretrained_weights)
> >     else:
> >         model.load_state_dict(torch.load(opt.pretrained_weights))
> > ```
> 
> Replace this code in which line on train.py?

Line 56-64

Plz replace following (line 56-64) 

 # Get data configuration
    data_config = parse_data_config(opt.data_config)
    train_path = data_config["train"]
    valid_path = data_config["valid"]
    class_names = load_classes(data_config["names"])

    # Initiate model
    model = Darknet(opt.model_def).to(device)
    model.apply(weights_init_normal)

    # If specified we start from checkpoint
    if opt.pretrained_weights:
        if opt.pretrained_weights.endswith(".pth"):
            model.load_state_dict(torch.load(opt.pretrained_weights))
        else:
            model.load_darknet_weights(opt.pretrained_weights)

by under mentioned code in train.py

model = Darknet(opt.model_def).to(device)
model.apply(weights_init_normal)
model.load_state_dict(torch.load("checkpoints/yolov3_ckpt_99.pth", map_location=torch.device('cpu')))
Darknet.save_darknet_weights(model, 'backup/newYolov3.weights', cutoff=-1)
# If specified we start from checkpoint
if opt.pretrained_weights:
    if opt.pretrained_weights.endswith(".weights"):
        model.load_darknet_weights(opt.pretrained_weights)
    else:
        model.load_state_dict(torch.load(opt.pretrained_weights))

Thereafter, start training again by using cmd "python train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data" and a new weight file named newYolov3.weights will be created after completion of 1 epoch. Stop the training after 1 epoch as your weight file will be ready or you can use the other method suggested above.

**Comment by Flova** [comment]
See #722 for the current official solution
