### ISSUE TITLE
Improving the repo for Windows users

### ISSUE THREAD

**Issue by QuteBits** [eriklindernoren/PyTorch-YOLOv3#312]
Hi,

just tried to run your repo from scratch on a Windows machine. 2 things didn't work but worked after very minor adjustments:

1) `python detect.py --image_folder ./data/samples` instead of `python detect.py --image_folder /data/samples` (added a dot in front of the samples path)
2) when saving files (in `detect.py`), filenames right at the end had backward-slashes - so the script failed trying to store complaining about: `No such file or directory: 'output/samples\\dog.png'`. Maybe you find a slicker way of solving it, I went for a hacky way by replacing
`filename = path.split("/")[-1].split(".")[0]`
with 
`filename = path.split("/")[-1].split('\\')[-1].split(".")[0]`

P.S. Thanks for the awesome work

**Comment by incredible-john** [comment]
thanks man ! it really solved the problem!
