### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 12.93 GiB (GPU 0; 5.00 GiB total capacity; 1.44 GiB already allocated; 2.31 GiB free; 6.04 MiB cached)

### ISSUE THREAD

**Issue by JeasonUESTC** [eriklindernoren/PyTorch-YOLOv3#317]
After pytorch was upgraded to 1.1, the error  of `RuntimeError: CUDA out of memory. Tried to allocate 12.93 GiB (GPU 0; 5.00 GiB total capacity; 1.44 GiB already allocated; 2.31 GiB free; 6.04 MiB cached)`was reported at the beginning of training, tuning batch_size did not work, adding with_grad() did not work, who can help?

**Comment by IsaacBerman** [comment]
Lowering batch size to 4 doesn't work for you?

**Comment by cxjaicj** [comment]
Have you solved your problem？

**Comment by IsaacBerman** [comment]
I lowered batch size and it was solved, but would like to be able to optimize so that I don't run into it at higher batch sizes.

**Comment by JeasonUESTC** [comment]
> Have you solved your problem？

Yeah, I lowered batch size and it was solved.

**Comment by JeasonUESTC** [comment]
> I lowered batch size and it was solved, but would like to be able to optimize so that I don't run into it at higher batch sizes.

Yes, my dataSets images is so big that it only lower batch size.

**Comment by nguyentienanh2303** [comment]
@JeasonUESTC @IsaacBerman @cxjaicj 
I got an issue that CUDA out of memory although I've changed any batch size such as 1, 2, 4, 8, 16.
Any one can help me, please?
