### ISSUE TITLE
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

### ISSUE THREAD

**Issue by smalldroid** [eriklindernoren/PyTorch-YOLOv3#327]
Which version of tensorflow should we use in this source code? Thanks!

**Comment by smalldroid** [comment]
try to use tf.summary.create_file_writer('log_dir') in tensorflow 2.0

**Comment by WJohnnyW** [comment]
hello, my tf version is 2.0 ,it happend that in this version tensorflow has no attribute Summary, and I am new to tf, I  don't know how to fix the code to solve this problem .
![1](https://user-images.githubusercontent.com/37621759/67963690-f8dbca80-fc39-11e9-8eaa-d79fa7c11a53.PNG)

**Comment by smalldroid** [comment]
Go to this  930c587 to solve that problem.

**Comment by WJohnnyW** [comment]
> try to use tf.summary.create_file_writer('log_dir') in tensorflow 2.0

thank you so much!!!(*^▽^*)

**Comment by WJohnnyW** [comment]
> Go to this [930c587](https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/930c5872eea3d22233805f3f693dd5c9a9892707) to solve that problem.

thank you so much (*^▽^*)

**Comment by Mohamed209** [comment]
All previous solutions are appreciated , but I solved it by downgrading tensor flow version into 1.15.0

**Comment by Borda** [comment]
there is a better way, drop TensorFlow dependency completely, see #412

**Comment by sakurasakura1996** [comment]
All previous solutions are appreciated.I solved it by the instruction of  [930c587](https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/930c5872eea3d22233805f3f693dd5c9a9892707)

**Comment by interestingzhuo** [comment]
https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/930c5872eea3d22233805f3f693dd5c9a9892707 doesn't work for tf2.0

**Comment by interestingzhuo** [comment]
How did you fix the error 'have no attribute 'Summary''

**Comment by LakhiCharanMahato** [comment]
This works for me:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by Kris10Xing** [comment]
930c587 doesn't work to me, what should I do?

**Comment by cesarhcq** [comment]
> Go to this [930c587](https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/930c5872eea3d22233805f3f693dd5c9a9892707) to solve that problem.

Thks! It solved my problem too

**Comment by Flova** [comment]
@cesarhcq the tf dependency has been completely dropped on the current master
