### ISSUE TITLE
Batchisze affect MAP?

### ISSUE THREAD

**Issue by dongzhen123** [eriklindernoren/PyTorch-YOLOv3#330]
when change the batchsize in test.py from 8 to 36,the map drop from 48.5 to 37.5.
why?
conf_thres=0.5
Nms_thres=0.5
Iou_thres=0.5

**Comment by jenn0727** [comment]
I meet the same problem. Have u solve it?

**Comment by dongzhen123** [comment]
> I meet the same problem. Have u solve it?

There is a bug in the code of datasets.py.
When the img and label one-to-one correspondence,there is no problem.But if the img lack of label, the bug will be triggered.

The img and label are not one-to-one correspondence like this in one batch(batchsize=64).
img1-label1
img2-label2
....   -   ....
img9-label9
img10-label11
...  -  ...
img64-next_batch label1
And the batchsize more larger,the Map more lower.
So you could change the code like this:

class ListDataset(Dataset):

       def __init__():

       def __getitem__():
           if os.path.exists(label_path):
               ###############
           else:
               targets=None
               img=None
        def collate_fn():
              paths,img,targets=list(zip(*batch))
              targets=[boxes for boxes in targets if boxes is not None]
              imgs=[img for img in imgs if img is not None]
              ############
              return paths,img,targets



After thehandle then if the pic lack of label,the corresponding image will also be deleted
img1-label1
img2-label2
....   -   ....
img9-label9
img11-label11
...  -  ...
img64-label64
