### ISSUE TITLE
RuntimeError: grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by gsx0015** [eriklindernoren/PyTorch-YOLOv3#331]
When I use a single GPU, it works fine. 
But with model = torch.nn.DataParallel(model, device_ids=[0, 1]), I get an error. 
How to solve this problem?
# ---
i try "loss.backward(torch.Tensor([1, 1])) or loss.sum().backward().", but not work.

**Comment by shaoxiongji** [comment]
Hi, I have the same error. Have you solved this problem?

**Comment by Flova** [comment]
Multiple GPUs are not supported at the moment. Thread for multi GPU training #520
