### ISSUE TITLE
Why recall is bigger than 1?

### ISSUE THREAD

**Issue by Jsdst** [eriklindernoren/PyTorch-YOLOv3#332]
In my test, recall rate is often bigger than 1. I think there is a problem in utils\utils.py get_batch_statistics function in line 177.
`176........iou, box_index = bbox_iou(pred_box.unsqueeze(0), target_boxes).max(0)`
`177........if iou >= iou_threshold and box_index not in detected_boxes:`
`178............true_positives[pred_i] = 1`
`179............detected_boxes += [box_index]`
Whether line 177 only judges the accuracy of the bbox and does not guarantee the accuracy of the class? Should line 177 be changed to the following?
`177........if pred_label == target_labels[box_index] and iou >= iou_threshold and box_index not in detected_boxes:`

**Comment by zihaozhang9** [comment]
Yes. I also have a situation where mAP is greater than 1.

**Comment by red0orange** [comment]
I also found this problem and couldn't understand it. Is this actually a logical error?

**Comment by Flova** [comment]
This might be due to a wrong true positive count as described in #233
