### ISSUE TITLE
 File "D:\PyTorch-YOLOv3-master2\utils\utils.py", line 294, in build_targets     best_ious, best_n = ious.max(0) RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an ident ity

### ISSUE THREAD

**Issue by cxjaicj** [eriklindernoren/PyTorch-YOLOv3#339]
Does anyone know how to fix this mistake?

**Comment by imwxc** [comment]
> Does anyone know how to fix this mistake?

I've fixed this
解决办法是：如果你的错误是在 best_ious, best_n = ious.max(0) 中出现的，可以考虑将 augmentations.py 文件夹中的 DefaultAug(),这一行注释掉，因为自定义的 iaa.Affine 中 translate_percent 参数会导致输出的bb_targets 变为空值

**Comment by Flova** [comment]
Could you provide a pull request with your fix?

**Comment by imwxc** [comment]
> Could you provide a pull request with your fix?

i've pull the request ,please look at  it if it works.
