### ISSUE TITLE
shape error ？？

### ISSUE THREAD

**Issue by ZhenhuiTang** [eriklindernoren/PyTorch-YOLOv3#341]
Namespace(batch_size=1, checkpoint_model=None, class_path='data/coco.names', conf_thres=0.8, image_folder='data/samples/', img_size=416, model_def='config/yolov3.cfg', n_cpu=0, nms_thres=0.4, weights_path='weights/yolov3.weights')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    model.load_darknet_weights(opt.weights_path)
  File "/home/machinelearning/Documents/PyTorch-YOLOv3-master/models.py", line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 2551507

**Comment by wongqueng** [comment]
me,too.because pytorch1.3??

**Comment by wongqueng** [comment]
> 
> 
> Namespace(batch_size=1, checkpoint_model=None, class_path='data/coco.names', conf_thres=0.8, image_folder='data/samples/', img_size=416, model_def='config/yolov3.cfg', n_cpu=0, nms_thres=0.4, weights_path='weights/yolov3.weights')
> Traceback (most recent call last):
> File "detect.py", line 48, in
> model.load_darknet_weights(opt.weights_path)
> File "/home/machinelearning/Documents/PyTorch-YOLOv3-master/models.py", line 315, in load_darknet_weights
> conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
> RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 2551507

you should first "
cd weights
bash download_weights.sh
cd data  
bash get_coco_dataset.sh

**Comment by ZhenhuiTang** [comment]
Yeah, l have already deal with this problem. 
The major cause is that my coco data path is wrong in the coco.names.
Thanks for your attention.

**Comment by AadeIT** [comment]
I have the same problem. Could you tell me your solution? please！
