### ISSUE TITLE
torch.cuda.is_available bug

### ISSUE THREAD

**Issue by glenn-jocher** [eriklindernoren/PyTorch-YOLOv3#35]
`test.py` and `train.py` always return `cuda = True` because boolean is reflecting function presence rather than cuda presence. Also redundant `if` statement. Suggest replace
`cuda = True if torch.cuda.is_available else False`

with
`cuda = torch.cuda.is_available()`

**Comment by alexandru-dinu** [comment]
If you want to be extra pedantic, I'd also suggest to add:
```
cuda = args.use_cuda and torch.cuda.is_available()
```

**Comment by eriklindernoren** [comment]
This is resolved in 84f3e13
