### ISSUE TITLE
No weights file after training

### ISSUE THREAD

**Issue by coolmarat** [eriklindernoren/PyTorch-YOLOv3#352]
I have checkpoint file, but there is no yolov3.weights file after training this net on my custom dataset . How can I get it?

**Comment by hackobi** [comment]
The weights file is created after the last epoch, does your model train past the last epoch? or does it stop before?

**Comment by hackobi** [comment]
and did you modify any of the code?

**Comment by Flova** [comment]
There are checkpoints in the PyTorch format, you can convert them to the darknet format as described in issue #722.
