### ISSUE TITLE
I download the "weight" , but when I run test.py, I get this "0" result.Can anyone tell me why?

### ISSUE THREAD

**Issue by wallcuber** [eriklindernoren/PyTorch-YOLOv3#353]
Namespace(batch_size=8, class_path='data/custom/custom.names', conf_thres=0.001, data_config='config/custom.data', img_size=416, iou_thres=0.5, model_def='config/yolov3-custom.cfg', n_cpu=8, nms_thres=0.5, weights_path='weights/yolov3.weights')
Compute mAP...
Detecting objects: 100%|██████████| 1/1 [00:02<00:00,  2.58s/it]
Computing AP: 100%|██████████| 1/1 [00:00<?, ?it/s]
Average Precisions:
+ Class '0' (train) - AP: 0.0
mAP: 0.0

**Comment by sakurasakura1996** [comment]
Did you solve the problem, I also met this problem. When I use this code to train my custom dataset, the AP of computing was 0.

**Comment by wallcuber** [comment]
> Did you solve the problem, I also met this problem. When I use this code to train my custom dataset, the AP of computing was 0.

Sorry. I don't solve it.I use another YOLOv3 pytorch code.

**Comment by sakurasakura1996** [comment]
> > Did you solve the problem, I also met this problem. When I use this code to train my custom dataset, the AP of computing was 0.
> 
> Sorry. I don't solve it.I use another YOLOv3 pytorch code.

Thank you.I also use another repository and solve the problem
