### ISSUE TITLE
RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1

### ISSUE THREAD

**Issue by yyyyykp** [eriklindernoren/PyTorch-YOLOv3#361]
file"augmentation.py"
images = torch.flip(images, [-1])
RuntimeError: expected flip dims axis >= 0, but got min flip dims=-1
can anyone help me?

**Comment by yyyyykp** [comment]
This problem has been solved!

**Comment by zahrasalahshoori** [comment]
hi @yyyyykp 
we have the same problem 
How you solved this?
Thanks

**Comment by yyyyykp** [comment]
pytorch 1.3.1 tensorflow-gpu 1.13 python 3.6


This is my final configuration, i don't know if the others will work.
hope it can help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zahrasalahshoori"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 晚上10:24
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"贝尔静"<838359518@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: expected flip dims axis &gt;= 0, but got min flip dims=-1 (#361)




hi @yyyyykp
 we have the same problem
 How you solved this?
 Thanks

**Comment by nengbunengzhengdianqi** [comment]
> This problem has been solved!

How did you do it?

**Comment by yyyyykp** [comment]
i modified the configuration and this problem disappeared.


pytorch 1.3.1 tensorflow-gpu 1.13 python 3.6


This is my final configuration, i don't know if the others could work.
hope it can help you.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 晚上9:10
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"贝尔静"<838359518@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] RuntimeError: expected flip dims axis &gt;= 0, but got min flip dims=-1 (#361)





  
This problem has been solved!
  
How did you do it?

**Comment by Flova** [comment]
If I got it right, the problem is solved. I, therefore, close the issue. Feel free to reopen if there's more to do.
