### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by xwf12345678** [eriklindernoren/PyTorch-YOLOv3#374]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb9 in position 17: illegal multibyte sequence
How to solve it.

**Comment by Zzheng-6** [comment]
I also meet this problem,do you have solved?

**Comment by Flova** [comment]
What's the encoding of your `train.txt` file?

**Comment by Flova** [comment]
Maybe it is encoded with some special non-UTF-8 encoding for Chinese, Japanese, ... symbols. Try to encode the file with UTF-8 or ASCII.

**Comment by Zzheng-6** [comment]
Thank you for your answer. I solved this problem yesterday. It's strange that I will train.txt The training path in the picture can be changed to absolute.
