### ISSUE TITLE
which anchor match the groudtruth？

### ISSUE THREAD

**Issue by toyal** [eriklindernoren/PyTorch-YOLOv3#380]
hello,i want to ask a question,which anchor match the groudtruth? i think groudtruth match the anchor which has largest IOU with groudtruth between different yolo layer ，but i discover the code do this by matching the groudtruth with anchor in every yolo layer and this make some problem in the detection result，hope answer，thx。

**Comment by toyal** [comment]
![image](https://user-images.githubusercontent.com/27479107/70883876-50c66900-200f-11ea-8c88-85902edec441.png)

**Comment by ForeverRuri** [comment]
and the iou is calculated without pos info
pretty strange

**Comment by zerostan** [comment]
I have the same question with you. Have you got the answer?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
