### ISSUE TITLE
noobj_mask and obj_mask

### ISSUE THREAD

**Issue by ShengyuanTang-GD** [eriklindernoren/PyTorch-YOLOv3#381]
noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
why not use "obj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 1"?

**Comment by toyal** [comment]
the SSD use this strategy，you can try this 。i think this may solve thie imbanlance of positive and negative samples  To some extent

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
