### ISSUE TITLE
Can someone really reproduce the repo. mAP from scratch?

### ISSUE THREAD

**Issue by zyj0021200** [eriklindernoren/PyTorch-YOLOv3#382]
I tried to train the model from scratch but the evaluation result was really poor. And I also noticed some other related issues #193 .  Can someone really reproduce the result from scratch?

**Comment by PingHGao** [comment]
I wonder it too! Please help.

**Comment by ly0303521** [comment]
> I wonder it too! Please help.
my mAP is more than 0.8,  but when it comes to detect, the conf is 1 nearly, its not normal i think

**Comment by voodoopotato** [comment]
this repo does not converge. 
take a look at #504

**Comment by Flova** [comment]
![image](https://user-images.githubusercontent.com/15075613/125204771-2dad7b00-e27f-11eb-9376-8c0c6fde75ee.png)

The convergence has been improved lately. Not perfect yet, but definitely better than before.
