### ISSUE TITLE
in NMS, cuda is slower than cpu

### ISSUE THREAD

**Issue by pangkun248** [eriklindernoren/PyTorch-YOLOv3#385]
Why is using Tensor on cuda in each NMS 0.5ms slower than Tensor on cpu? Shouldn't it be faster?

**Comment by Flova** [comment]
Copying the data to the GPU to perform small operations can be slower compared to doing them with the CPU it is a tradeoff, but ideally, the NMS data is already on the GPU, so it heavily depends on your test setup.
