### ISSUE TITLE
About img_size in training phase.

### ISSUE THREAD

**Issue by Joker316701882** [eriklindernoren/PyTorch-YOLOv3#389]
It is quite confusing that why **--img_size** is set as cmd parameters while it's never been used in training stage.

**Comment by jaagut** [comment]
I think, the existence of this argument is quite useful, therefore we should finally make use of this parameter in the `models.py`...

**Comment by Flova** [comment]
Pull request #261 closed this issue

**Comment by jaagut** [comment]
> therefore we should remove this parameter from the model.

No it did not. Please reopen...
My future will resolve this soon.
