### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by LinpengPan** [eriklindernoren/PyTorch-YOLOv3#391]
How to train this network with multiple GPUs?

**Comment by jaysonph** [comment]
@LinpengPan 
I think you can refer to PyTorch website.
A short example taken from there:
>>> net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
>>> output = net(input_var)  # input_var can be on any device, including CPU

**Comment by Flova** [comment]
Duplicate of #520
