### ISSUE TITLE
which tensorflow version?

### ISSUE THREAD

**Issue by Note-Liu** [eriklindernoren/PyTorch-YOLOv3#394]

**Comment by qiullv** [comment]
tensorflow==1.13.1 can run successfully，but  2.0 version or higher has some problems.

**Comment by omizonly** [comment]
In tensorflow == 1.13.1 
Error: module tf has no attribute ' create_file_writer '
In tensorflow == 2.0
Error: module tf has no attribute 'Summary'
What should I do?

**Comment by qiullv** [comment]
&nbsp;In tensorflow == 1.13.1&nbsp; utils.py




 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "omizonly"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 中午12:42
收件人: "eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;; 
抄送: "Hey"<2391361235@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [eriklindernoren/PyTorch-YOLOv3] which tensorflow version? (#394)




In tensorflow == 1.13.1
 Error: module tf has no attribute ' create_file_writer '
 In tensorflow == 2.0
 Error: module tf has no attribute 'Summary'
 What should I do?

**Comment by qiullv** [comment]
sorry, the code is in logger.py which is in utils directory.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "omizonly"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 中午12:42
收件人: "eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;; 
抄送: "Hey"<2391361235@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [eriklindernoren/PyTorch-YOLOv3] which tensorflow version? (#394)




In tensorflow == 1.13.1
 Error: module tf has no attribute ' create_file_writer '
 In tensorflow == 2.0
 Error: module tf has no attribute 'Summary'
 What should I do?

**Comment by qiullv** [comment]
In tensorflow == 1.13.1
更改utils文件夹里面的logger.py的第七行
self.writer = tf.summary.FileWriter(log_dir)

**Comment by Borda** [comment]
there is a better way, drop TensorFlow dependency completely, see #412

**Comment by Note-Liu** [comment]
> there is a better way, drop TensorFlow dependency completely, see #412

thanks!

**Comment by reggievick** [comment]
For tensorflow 2.x change your `utils/logger.py` file to the below:

```
import tensorflow as tf


class Logger(object):
    def __init__(self, log_dir):
        """Create a summary writer logging to log_dir."""
        #self.writer = tf.summary.FileWriter(log_dir)
        self.writer = tf.summary.create_file_writer(log_dir)

    def scalar_summary(self, tag, value, step):
        """Log a scalar variable."""
        #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])
        #self.writer.add_summary(summary, step)
        with self.writer.as_default():
            tf.summary.scalar(tag, value, step=step)
            self.writer.flush()

    def list_of_scalars_summary(self, tag_value_pairs, step):
        """Log scalar variables."""
        #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
        #self.writer.add_summary(summary, step)

        with self.writer.as_default():
            for tag, value in tag_value_pairs:
                tf.summary.scalar(tag, value, step=step)
                self.writer.flush()
```

**Comment by PALMJJ** [comment]
> 
> 
> For tensorflow 2.x change your `utils/logger.py` file to the below:
> 
> ```
> import tensorflow as tf
> 
> 
> class Logger(object):
>     def __init__(self, log_dir):
>         """Create a summary writer logging to log_dir."""
>         #self.writer = tf.summary.FileWriter(log_dir)
>         self.writer = tf.summary.create_file_writer(log_dir)
> 
>     def scalar_summary(self, tag, value, step):
>         """Log a scalar variable."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])
>         #self.writer.add_summary(summary, step)
>         with self.writer.as_default():
>             tf.summary.scalar(tag, value, step=step)
>             self.writer.flush()
> 
>     def list_of_scalars_summary(self, tag_value_pairs, step):
>         """Log scalar variables."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
>         #self.writer.add_summary(summary, step)
> 
>         with self.writer.as_default():
>             for tag, value in tag_value_pairs:
>                 tf.summary.scalar(tag, value, step=step)
>                 self.writer.flush()
> ```

thanks

**Comment by st1312st** [comment]
> For tensorflow 2.x change your `utils/logger.py` file to the below:
> 
> ```
> import tensorflow as tf
> 
> 
> class Logger(object):
>     def __init__(self, log_dir):
>         """Create a summary writer logging to log_dir."""
>         #self.writer = tf.summary.FileWriter(log_dir)
>         self.writer = tf.summary.create_file_writer(log_dir)
> 
>     def scalar_summary(self, tag, value, step):
>         """Log a scalar variable."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])
>         #self.writer.add_summary(summary, step)
>         with self.writer.as_default():
>             tf.summary.scalar(tag, value, step=step)
>             self.writer.flush()
> 
>     def list_of_scalars_summary(self, tag_value_pairs, step):
>         """Log scalar variables."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
>         #self.writer.add_summary(summary, step)
> 
>         with self.writer.as_default():
>             for tag, value in tag_value_pairs:
>                 tf.summary.scalar(tag, value, step=step)
>                 self.writer.flush()
> ```

very thanks

**Comment by theweakgod** [comment]
> For tensorflow 2.x change your `utils/logger.py` file to the below:
> 
> ```
> import tensorflow as tf
> 
> 
> class Logger(object):
>     def __init__(self, log_dir):
>         """Create a summary writer logging to log_dir."""
>         #self.writer = tf.summary.FileWriter(log_dir)
>         self.writer = tf.summary.create_file_writer(log_dir)
> 
>     def scalar_summary(self, tag, value, step):
>         """Log a scalar variable."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])
>         #self.writer.add_summary(summary, step)
>         with self.writer.as_default():
>             tf.summary.scalar(tag, value, step=step)
>             self.writer.flush()
> 
>     def list_of_scalars_summary(self, tag_value_pairs, step):
>         """Log scalar variables."""
>         #summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
>         #self.writer.add_summary(summary, step)
> 
>         with self.writer.as_default():
>             for tag, value in tag_value_pairs:
>                 tf.summary.scalar(tag, value, step=step)
>                 self.writer.flush()
> ```

thanks!!!!!
