### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 1, 416, 416] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by Northautumn** [eriklindernoren/PyTorch-YOLOv3#401]
![image](https://user-images.githubusercontent.com/49355997/71777878-3c0f3c80-2fe1-11ea-8344-80619e17a987.png)

when i have run the train.py,  python detect.py --weights_path  weights/yolov3.weights.and then i try to run the detect.py,it occurs this bug,
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 1, 416, 416] to have 3 channels, but got 1 channels instead
how can i solve it to detect the sample pictures

**Comment by leonmayer** [comment]
Hi,
are you training with custom weights?
I am experiencing the same issue when using weights that were trained on greyscale images.
The error seems to lie somewhere deep inside pytorch, so propably no easy fix.
Were you able to fix it?

**Comment by zxin8218** [comment]
I encountered the same error when I tested the SAR image, did you solve it？

**Comment by atinesh-s** [comment]
I am facing similar issue, seems like just changing `channels=1` in `config/yolov3-custom.cfg` doesn’t work. Did you guys found any work around.

**Comment by atinesh-s** [comment]
Have a look [here](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/414#issuecomment-618931177)
