### ISSUE TITLE
RuntimeError: shape '[2, 3, 6, 16, 16]' is invalid for input of size 16384

### ISSUE THREAD

**Issue by wyuzyf** [eriklindernoren/PyTorch-YOLOv3#403]
i did as README ,but still have this problem。
ex：classes = 1
       filters = （classes+4+1）*3 =18

please help me ,THANK YOU ~~~

**Comment by vimeitor** [comment]
Did you download the weights? I got this problem too before I downloaded them.

**Comment by wyuzyf** [comment]
i have download pre-weights, but I think the problem has nothing to do with it。only running models.py still have this problem .

**Comment by 123wk45678** [comment]
do you slove it?

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
