### ISSUE TITLE
detect.py detect.py: error: unrecognized arguments: --imagefolder data/samples

### ISSUE THREAD

**Issue by vmirea** [eriklindernoren/PyTorch-YOLOv3#407]
I pulled the code last week and it seems that detect.py parameters changed. 
The command from the documentation seems to be outdated:

`usage: detect.py [-h] [--image_folder IMAGE_FOLDER] [--model_def MODEL_DEF]
                 [--weights_path WEIGHTS_PATH] [--class_path CLASS_PATH]
                 [--conf_thres CONF_THRES] [--nms_thres NMS_THRES]
                 [--batch_size BATCH_SIZE] [--n_cpu N_CPU]
                 [--img_size IMG_SIZE] [--checkpoint_model CHECKPOINT_MODEL] 
detect.py: error: unrecognized arguments: --imagefolder data/samples
 python3 detect.py --image_folder data/samples/`

**Comment by vmirea** [comment]
Invalid:
The parrameter is "--image_folder" instead on "--imagefolder"

**Comment by Borda** [comment]
Try this fork https://github.com/Borda/PyTorch-YOLOv3
