### ISSUE TITLE
convert darknet weights to pytorch weights 

### ISSUE THREAD

**Issue by poornimajd** [eriklindernoren/PyTorch-YOLOv3#409]
Hey can the save darknet weights function in models.py be used to save the weights in pytorch format ,i.e with the extension .pt ,or how is that function used?
how do we use function to convert the darknet weights to pytorch weights ? Is it just by passing the path with the model name extension as '.pt'

**Comment by Flova** [comment]
You could load the model in an IPython shell or simple script (see README.md) and call the function `torch.save(model.state_dict(), <path>)` to save it at `<path>`.
