### ISSUE TITLE
Evaluation freezing on custom dataset

### ISSUE THREAD

**Issue by wildcat5566** [eriklindernoren/PyTorch-YOLOv3#415]
Hello, 

I currently started the training process on a custom dataset and I haven't set up a GPU yet.
Just to check if everything is working correctly, I am using only a few images for the evaluation. First there were 12 and then I reduced it to 2. 
Training works fine but however the evaluation process just FREEZES (and also the ETA displayed is something like 00:0<?) from the first epoch.
Did anyone encounter the same problem? I would like to know how you solved it. Thanks!

**Comment by tmvhs1004** [comment]
i have a same problem

**Comment by dyh-bupt** [comment]
i have the same problem sometimes, just restart may help.

**Comment by Flova** [comment]
You have too many predictions due to the random initialization. This should be fixed with the timeout for the nms that was introduced some time ago.
