### ISSUE TITLE
can not save output image

### ISSUE THREAD

**Issue by xiuzheDorothy** [eriklindernoren/PyTorch-YOLOv3#416]
In detect.py:

> Saving images:
> (0) Image: 'data/samples\carflow.jpg'
> 	+ Label: car, Conf: 0.93545
> Traceback (most recent call last):
>   File "E:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2712, in safe_execfile
>     self.compile if shell_futures else None)
>   File "E:\anaconda\lib\site-packages\IPython\utils\py3compat.py", line 168, in execfile
>     exec(compiler(f.read(), fname, 'exec'), glob, loc)
>   File "E:\MachineLearning\PyTorch-YOLOv3\detect.py", line 140, in <module>
>     plt.savefig(f"output/{filename}.png", bbox_inches="tight", pad_inches=0.0)
>   File "E:\anaconda\lib\site-packages\matplotlib\pyplot.py", line 722, in savefig
>     res = fig.savefig(*args, **kwargs)
>   File "E:\anaconda\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
>     self.canvas.print_figure(fname, **kwargs)
>   File "E:\anaconda\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 88, in print_figure
>     super().print_figure(*args, **kwargs)
>   File "E:\anaconda\lib\site-packages\matplotlib\backend_bases.py", line 2082, in print_figure
>     **kwargs)
>   File "E:\anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 530, in print_png
>     cbook.open_file_cm(filename_or_obj, "wb") as fh:
>   File "E:\anaconda\lib\contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "E:\anaconda\lib\site-packages\matplotlib\cbook\__init__.py", line 447, in open_file_cm
>     fh, opened = to_filehandle(path_or_file, mode, True, encoding)
>   File "E:\anaconda\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
>     fh = open(fname, flag, encoding=encoding)
> FileNotFoundError: [Errno 2] No such file or directory: 'output/samples\\carflow.png'

Is it because of the Windows administrator privileges?Or Anaconda problem?

**Comment by alsawaf** [comment]
i'm having this problem could you solve it ?

**Comment by Whisper94** [comment]
I copied all samples from input/samples to output/samples and it works :D👯

**Comment by Flova** [comment]
It seems like your path contains both `/` and `\` maybe Windows doesn't like paths like this. The code shouldn't do stuff like this anymore. Maybe an older version assumed a Linux path format.
