### ISSUE TITLE
About a line in train.py: ap_table += [[c, class_names[c], "%.5f" % AP[i]]]

### ISSUE THREAD

**Issue by Adoreee** [eriklindernoren/PyTorch-YOLOv3#418]
I use the DOTA dataset (15 classes)
when i run train.py, appear

Traceback (most recent call last):
  File "train.py", line 176, in <module>
    ap_table += [[c, class_names[c], "%.5f" % AP[i]]]
IndexError: list index out of range

Why is that?
Thank U

**Comment by Adoreee** [comment]
solved. Because the last line of the names file is missing a newline.
Thank you

**Comment by arxlan786** [comment]
kmlmkl** m, m,**

**Comment by sdustdk1427** [comment]
@Adoreee Hello, I have the same problem but I don't know what you mean?How exactly did you change it?thanks！

**Comment by Adoreee** [comment]
> @Adoreee Hello, I have the same problem but I don't know what you mean?How exactly did you change it?thanks！

Add a "\n" to the last line of *.names

**Comment by sdustdk1427** [comment]
@Adoreee Thank you  very much!

**Comment by SriramPingali** [comment]
@Adoreee 
What exactly do you mean by adding a "\n"?

Let's say my .names file is as follows:
BOARD
TEXT
PERSON

**Comment by bisonliao** [comment]
add check code can solve?

                if c < len(class_names):
                    ap_table += [[c, class_names[c], "%.5f" % AP[i]]]
                else:
                    print("!!! invalid class index:", c)
