### ISSUE TITLE
Training on Custom Data

### ISSUE THREAD

**Issue by ryanh18** [eriklindernoren/PyTorch-YOLOv3#421]
Having issues with training on custom data. I've put the data and the labels where the instructions said to but I keep getting an error that 'data/custom/images/' is a directory which is obviously true. How do I remedy this? Seems like we should be able to feed it a directory of all the images

**Comment by neeveermoree** [comment]
Specify your problem and I will be able to help you

**Comment by ryanh18** [comment]
I was able to fix it I just had to use sed/awk to make a file with all of the paths to my training images. However, i've given up on this repo... it put too much strain on my GPU and wasn't training
