### ISSUE TITLE
RuntimeError: shape '[512, 256, 3, 3]' is invalid for input of size 391694

### ISSUE THREAD

**Issue by pedrooct** [eriklindernoren/PyTorch-YOLOv3#425]
Hi , what does this mean ! i have only one class and i created a custom cfg file.

Traceback (most recent call last):
  File "train.py", line 64, in <module>
    model.load_darknet_weights(opt.pretrained_weights)
  File "/home/data/PyTorch-YOLOv3/models.py", line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[512, 256, 3, 3]' is invalid for input of size 391694

help me please. Thank you.

**Comment by Nabiod** [comment]
Maybe you need make your original pictures is 3 channels.

**Comment by markgao-916** [comment]
三个检测层的filter的数量（原文是255）计算和class number有关，3*（80+4+1）=255
