### ISSUE TITLE
why GPU is always occupied 0.5G when I choose "CPU" device

### ISSUE THREAD

**Issue by Aismarter** [eriklindernoren/PyTorch-YOLOv3#426]
Hi everyone, 
  Now I have a problem need your help. I wanted to use CPU device to running this model, but when choose the device to CPU in the code, I found my GPU memory was always occupied 0.5G in Task Scheduler.Is anyone know why about it and how to forbidden the GPU device when i detecting pictures, thanks a lot.

**Comment by Flova** [comment]
I think PyTorch loads some stuff on the GPU if it is imported. You could set the environment variable `CUDA_VISIBLE_DEVICES=""`. That could work.
