### ISSUE TITLE
"errorMessage": "'str' object has no attribute 'read'",

### ISSUE THREAD

**Issue by TAKU853** [eriklindernoren/PyTorch-YOLOv3#428]
I am trying to imprement environment variable for operating SQS Policy.
I'm facing error when I set as below.
[Action_SR : SQS:SendMessage,SQS:ReceiveMessage]
(It is having 2 items for parameter Action of SQS Policy.)

I have completed when I set value on AWS Lambda below.
[Action_R : SQS:ReceiveMessage]

It is my code below
****************************************************
import boto3
import json
import os

client = boto3.client('sqs')

def lambda_handler(event, context):
    response = client.set_queue_attributes(
        QueueUrl = 'https://sqs.*****.amazonaws.com/*****',
        Attributes={'Policy': json.dumps(
            {
                "Version": "2012-10-17",
                "Id": "arn:aws:sqs:***********",
                "Statement": [
                    {
                        "Sid": "Sid************",
                        "Effect": "Allow",
                        "Principal": "*",
                        "Action": [os.environ['Action_SR']],
                        "Resource": "arn:aws:sqs:***********"
                    }
                ]
            }
        )}
    )
****************************************************

What am I doing wrong ?
I just want it to take value from environment variables.
how can I do implement as wish for ?

It is error message.
****************************************************
"errorMessage": "'str' object has no attribute 'read'",
"errorType": "AttributeError",
****************************************************

**Comment by GaussianAlgebra** [comment]
I also met the same problem.

**Comment by Yi19960820** [comment]
me too

**Comment by GreeshmaTR** [comment]
@Flova can you please tell how did you solve the issue

**Comment by jaagut** [comment]
This error message and code snippet seems to be in NO relation to this current source code repository.
This repository provides a PyTorch implementation of the neural network YOLO for object detection on images. It has nothing to do with AWS or SQS.

@Flova has not solved the issue, but has instead closed it because it is off-topic.
I am sorry, we cannot provide you any help.
