### ISSUE TITLE
About the train and detector

### ISSUE THREAD

**Issue by TanMengluoye** [eriklindernoren/PyTorch-YOLOv3#43]
in detect.py:(line 109)
 for x1, y1, x2, y2, conf, cls_conf, cls_pred in detections:
IS this should be :
for x, y, w, h, conf, cls_conf, cls_pred in detections:
because in yolo layer: pred_boxes is [x,y,w,h]

**Comment by eriklindernoren** [comment]
pred_boxes is indeed structured as [x, y, w, h] in the yolo layer but if you look in utils.non_max_suppression you see that they are refactored to [x1, y1, x2, y2]

**Comment by TanMengluoye** [comment]
That's True! thanks.
