### ISSUE TITLE
plz tell me why +1 when you calculate IoU(torch.clamp(inter_rect_x2 - inter_rect_x1 + 1, min=0))

### ISSUE THREAD

**Issue by Vito0924** [eriklindernoren/PyTorch-YOLOv3#432]

**Comment by adricarda** [comment]
Did you figure it out? I was wondering the same.

**Comment by JackGodfrey122** [comment]
To account for the fact the calculations are done for pixel values and not real values. See the 2nd answer from here: https://stackoverflow.com/questions/25349178/calculating-percentage-of-bounding-box-overlap-for-image-detector-evaluation
