### ISSUE TITLE
When I run test.py,I failed. FileNotFoundError: [Errno 2] No such file or directory: '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg'

### ISSUE THREAD

**Issue by xiaoyuzhu666** [eriklindernoren/PyTorch-YOLOv3#435]

**Comment by Guiglc** [comment]
I met the same problem yesterday, now I have solved it. 

I suppose that you run the code on Windows. You might change the 5K.txt and trainvalno5k.txt like pictures below to solve this problem. 

Focus on the “/” and “:”. I am not familiar with Linux, I don't know why that works.

![image](https://user-images.githubusercontent.com/34328861/76584301-7d0e5a80-6516-11ea-8d18-1f4cdc3811c0.png)

**Comment by xiaoyuzhu666** [comment]
> I met same problem yesterday, now I have solved it.
> 
> I suppose that you run the code on Windows. You might change the 5K.txt and trainvalno5k.txt like pictures below to solve this problem.
> 
> Focus on the “/” and “:”. I am not familiar with Linux, I don't know why that works.
> 
> ![image](https://user-images.githubusercontent.com/34328861/76584301-7d0e5a80-6516-11ea-8d18-1f4cdc3811c0.png)
> 
> Are you Chinese? My major is not computer science, but I have to solve engineering problems by YOLO. Could I add you? Maybe we could learn it together.

是的，问题解决了，谢谢啦

**Comment by luckyxu168** [comment]
您好，我也遇到了同样的问题，请问你是如何解决这个问题的？

**Comment by xiaoyuzhu666** [comment]
我修改了5k.txt文件：使用绝对路径而不是相对路径。。你可以检查一下5k.txt文件，看看图片的路径有没有问题？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"徐威"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 晚上8:48
收件人:&nbsp;"eriklindernoren/PyTorch-YOLOv3"<PyTorch-YOLOv3@noreply.github.com&gt;;
抄送:&nbsp;"。。。"<2194844358@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] When I run test.py,I failed. FileNotFoundError: [Errno 2] No such file or directory: '/e/PyTorch-YOLOv3-master/data/coco/images/val2014/COCO_val2014_000000000164.jpg' (#435)





 
您好，我也遇到了同样的问题，请问你是如何解决这个问题的？
