### ISSUE TITLE
missing detection

### ISSUE THREAD

**Issue by hayanakamura** [eriklindernoren/PyTorch-YOLOv3#438]
I did train my custom dataset and detect test data.
I got this like grid all of outputs.
Why dit it  happen?
Please help me.
![000033](https://user-images.githubusercontent.com/48349965/76194788-4096e200-622a-11ea-95ab-b5cbfdfc4ecb.png)

**Comment by daixiangzi** [comment]
do you modify raw code?use default param to  train your custom data?

**Comment by hayata-nakamura** [comment]
> do you modify raw code?use default param to train your custom data?

What's raw code? You mean params we can change by argparse?

**Comment by daixiangzi** [comment]
> > do you modify raw code?use default param to train your custom data?
> 
> What's raw code? You mean params we can change by argparse?

No,for example anchor in your config/yolov3-custom.cfg

**Comment by hayata-nakamura** [comment]
> > > do you modify raw code?use default param to train your custom data?
> > 
> > 
> > What's raw code? You mean params we can change by argparse?
> 
> No,for example anchor in your config/yolov3-custom.cfg

I changed classes and filters but didn't change anchor.
How to set anchors??
