### ISSUE TITLE
label horisontal_flip error

### ISSUE THREAD

**Issue by Oliverwang** [eriklindernoren/PyTorch-YOLOv3#440]

**Comment by Oliverwang** [comment]
label horisontal_flip is correct

**Comment by gh19970322** [comment]
`def horisontal_flip(images, targets):
    images = torch.flip(images, [-1])
    targets[:, 2] = 1 - targets[:, 2]
    return images, targets`
@Oliverwang
Hello,i have a question about the flip augmentation（horisontal_flip） 
The image i get should be (height,width，3),so why does the function(torch.flip) use the numer [-1]?
If i need the horisontal flip(according to t`argets[:, 2] = 1 - targets[:, 2]`)，I` think that i should use the numer [1],  Right?
Anybody help？
