### ISSUE TITLE
Is there anyway to set a fixed number of output bounding boxes?

### ISSUE THREAD

**Issue by Huangxt57** [eriklindernoren/PyTorch-YOLOv3#442]
Hi, I want to use this model to extract proposals from custom datas and I want each output picture contains a fixed number of bounding boxes? Is there anyway I can manage that?

**Comment by Flova** [comment]
No the way yolo works is that it predicts if a grid cell contains the center of a bounding box, this cannot be limited easily. But you could predict many boxes using a low confidence threshold, sort them my confidence and pick the best n boxes. It could be lower than n in some edge cases where the model really is not able to find sufficient boxes in the given confidence range. Lowering the lower bound makes the postprocessing slower so it is not recommended.
