### ISSUE TITLE
non_max_suppression about bad case

### ISSUE THREAD

**Issue by daixiangzi** [eriklindernoren/PyTorch-YOLOv3#443]
iou_thresh and nms_thresh  is 0.5
in result:

![81](https://user-images.githubusercontent.com/24811131/76497291-adea8300-6475-11ea-9bbe-66f4b5a13162.png)

it looks like overlap....

**Comment by lmomoy** [comment]
have you solved it?

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
