### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by cendelian** [eriklindernoren/PyTorch-YOLOv3#450]
hello
when i train, and it occur error as below:

**File "/media/cendelian/新加卷/CV/Project/PyTorch-YOLOv3/test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)**

could you help me

**Comment by construct-care** [comment]
It seems the model is not trained well at first epoch. You can change the option evaluation_interval to 10 and  train.py line 152   1 to 5. Then have a try.

**Comment by jas-nat** [comment]
> hello
> when i train, and it occur error as below:
> 
> *_File "/media/cendelian/新加卷/CV/Project/PyTorch-YOLOv3/test.py", line 53, in evaluate true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(_sample_metrics))] ValueError: not enough values to unpack (expected 3, got 0)__
> 
> could you help me
I also discovered same problem

**Comment by jas-nat** [comment]
> It seems the model is not trained well at first epoch. You can change the option evaluation_interval to 10 and train.py line 152 1 to 5. Then have a try.

Do you mean this train.py line 152 ? 
`if epoch % opt.evaluation_interval == 0:` ?

**Comment by jas-nat** [comment]
Try to check this #222 @cendelian

**Comment by construct-care** [comment]
> > It seems the model is not trained well at first epoch. You can change the option evaluation_interval to 10 and train.py line 152 1 to 5. Then have a try.
> > @construct-care
> > Do you mean this train.py line 152 ?
> > `if epoch % opt.evaluation_interval == 0:` ?

Yes.  Sorry. 0 to 5.  You can have a try.
