### ISSUE TITLE
Load RGB and thermal images at the same time

### ISSUE THREAD

**Issue by jas-nat** [eriklindernoren/PyTorch-YOLOv3#455]
Hello. I am trying to train RGB and thermal images as the input. First, I have tried to train RGB and thermal images separately. It worked well. I converted thermal images from 1 channel into 3 channels. Now, I want to combine them together as a single input. What should I configure? 

Thanks

**Comment by AntoineMath** [comment]
- You can concatenate RGB and thermal to have a WxHx4 tensor as the input (you just have to change the input shape of the network.

- Or you can create 2 inputs (one of shape WxHx3 and another one of shape WxHx1)  and perform several convolutions separately before merging the 2 features map by using torch.cat  (and then keep the rest of the network unchanged).

I would try the first method before diving into too much code

**Comment by Flova** [comment]
So you want 4 channels (3 rgb and 1 thermal)?

**Comment by jas-nat** [comment]
Yes. But thankfully I managed to do it. So I will close this issue.

**Comment by Flova** [comment]
Okay thanks!
