### ISSUE TITLE
Run detect.py, some problems occur!(TypeError: tuple indices must be integers or slices, not tuple)

### ISSUE THREAD

**Issue by Madrid-Ista** [eriklindernoren/PyTorch-YOLOv3#457]
Traceback (most recent call last):
  File "detect.py", line 78, in <module>
    detections = non_max_suppression(detections, opt.conf_thres, opt.nms_thres)
  File "D:\Downloads\code\PyTorch-YOLOv3-master\utils\utils.py", line 236, in non_max_suppression
    prediction[..., :4] = xywh2xyxy(prediction[..., :4])                    # prediction为yolo输出列表
TypeError: tuple indices must be integers or slices, not tuple

**Comment by jaebbb** [comment]
last week it was running in my code, but now I have the same error...

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
