### ISSUE TITLE
a bug in datasets.py

### ISSUE THREAD

**Issue by zhenxing9968** [eriklindernoren/PyTorch-YOLOv3#46]
labels[:, 3] *= w / padded_w
labels[:, 4] *= h / padded_h
to 
labels[:, 3] *= float(w) / padded_w
labels[:, 4] *= float(h) / padded_h

**Comment by BobLiu20** [comment]
@zhenxing9968  no a bug. it is correct in python3

**Comment by zhenxing9968** [comment]
@BobLiu20 Oh... sorry, I used it in python2
