### ISSUE TITLE
augmentation

### ISSUE THREAD

**Issue by www7890** [eriklindernoren/PyTorch-YOLOv3#466]
There is a file "/utils/augmentations.py"
I have few questions:
Q1. I am curious what's the meaning of torch.flip with negative value of dimension.  ex. torch.flip(input, dims)?
Q2. Can I add more augmentation skill in this file? How to implement with the code given by eriklindernorn?

**Comment by gh19970322** [comment]
Did you solve it?
i have a question about the flip augmentation（horisontal_flip）
The image i get should be (height,width，3),so why does the function(torch.flip) use the numer [-1]?
If i need the horisontal flip(according to targets[:, 2] = 1 - targets[:, 2])，I` think that i should use the numer [1], Right?
Anybody help

**Comment by Jason-hao123** [comment]
> 
> 
> Did you solve it?
> i have a question about the flip augmentation（horisontal_flip）
> The image i get should be (height,width，3),so why does the function(torch.flip) use the numer [-1]?
> If i need the horisontal flip(according to targets[:, 2] = 1 - targets[:, 2])，I` think that i should use the numer [1], Right?
> Anybody help
i have solved the problem,thanks
[https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/440#issuecomment-751221359](url)
