### ISSUE TITLE
Is it possible to train without anchors like in original YOLO?

### ISSUE THREAD

**Issue by smolendawid** [eriklindernoren/PyTorch-YOLOv3#472]
Is it possible to train without anchors like in the original YOLO? What anchors should be set?

**Comment by www7890** [comment]
Anchors can be calculate by kmeans by IOU distance.

Get your own anchors for custom dataset helps to training yolov3, while it is still possible to get good result by default anchors.

**Comment by smolendawid** [comment]
Thank you, I understand, although I was wondering how to train the model without anchors at all.
