### ISSUE TITLE
Proper format of providing bounding boxes for training

### ISSUE THREAD

**Issue by jiteshm17** [eriklindernoren/PyTorch-YOLOv3#474]
If I have my bounding box coordinates as `(xmin,ymin,xmax,ymax)` and my image height and width are `(width,height)`, could you please mention how to convert them into the scale required for training Yolov3?

**Comment by AlanNewImage** [comment]
see data/custom,there is a sample.
labels.txt:   idx center_x/width center_y/height  (xmax-xmin)/width (ymax-ymin)/height

**Comment by jiteshm17** [comment]
Thanks a lot! I managed to get them in the proper format.

**Comment by dimimal** [comment]
Can we add many bounding boxes in the script that correspond to the same class over an image?
