### ISSUE TITLE
detect.py problem, the cls_conf is always 1.0

### ISSUE THREAD

**Issue by ly0303521** [eriklindernoren/PyTorch-YOLOv3#478]
when I use detect.py, the cls_conf is always 1.0,  who can tell me why
+ Label: without_mask, Conf: 1.00000

**Comment by ly0303521** [comment]
not always 1.0,  but closed, more than 0.9

**Comment by ly0303521** [comment]
output is single class

**Comment by ly0303521** [comment]
/home/ly/Pictures/Screenshot from 2020-04-09 19-56-48.png

**Comment by HHHcwb** [comment]
@ly0303521  Hi, I have the same problem. Did you find out the reason?

**Comment by HHHcwb** [comment]
@ly0303521 我已经解决了这个问题，你只要把conf这个属性输出就可以了

**Comment by Flova** [comment]
Classification is trivial with a single class so it is expected to get a confidence of 1 right? If I didn't understand feel free to answer. I otherwise close this issue for now.
