### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Summary'

### ISSUE THREAD

**Issue by PommesPeter** [eriklindernoren/PyTorch-YOLOv3#480]
When I run the train.py, using the custom data set and show this result.
`Traceback (most recent call last):
  File "train.py", line 141, in <module>
    logger.list_of_scalars_summary(tensorboard_log, batches_done)
  File "G:\PyTorch-YOLOv3-master\utils\logger.py", line 16, in list_of_scalars_summary
    summary = tf.summary(value=[tf.summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
  File "G:\PyTorch-YOLOv3-master\utils\logger.py", line 16, in <listcomp>
    summary = tf.summary(value=[tf.summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'Value'`

I think that it's the TensorFlow's problem, I am using the TensorFlow2.1.0, I don't know how to fix it. I have searched a lot of data but there are no solution

**Comment by PommesPeter** [comment]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    logger.list_of_scalars_summary(tensorboard_log, batches_done)
  File "G:\PyTorch-YOLOv3-master\utils\logger.py", line 18, in list_of_scalars_summary
    summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
  File "G:\PyTorch-YOLOv3-master\utils\logger.py", line 18, in <listcomp>
    summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value) for tag, value in tag_value_pairs])
AttributeError: module 'tensorflow' has no attribute 'Summary'

**Comment by sdustdk1427** [comment]
@PommesPeter How did you solve this problem?I had the same problem today.Thanks!

**Comment by liupenglei** [comment]
> @PommesPeter How did you solve this problem?I had the same problem today.Thanks!

你安装的tensorflow版本过高，可以卸载了然后安装tensorflow==1.3.0版本的就完美解决问题了

**Comment by Jackerho** [comment]
> > @PommesPeter How did you solve this problem?I had the same problem today.Thanks!
> 
> 你安装的tensorflow版本过高，可以卸载了然后安装tensorflow==1.3.0版本的就完美解决问题了

ERROR: Could not find a version that satisfies the requirement tensorflow==1.3.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow==1.3.0 
没有1版本了
