### ISSUE TITLE
about pytorch-yolov4

### ISSUE THREAD

**Issue by SOVLOOKUP** [eriklindernoren/PyTorch-YOLOv3#487]
here is an yolov4 version
https://github.com/SOVLOOKUP/PyTorch-YOLOv4

**Comment by Borda** [comment]
What is the difference compared to v3?

**Comment by SOVLOOKUP** [comment]
some compares:
https://n.sinaimg.cn/spider2020424/489/w1080h1009/20200424/8590-isqivxh8586423.png
