### ISSUE TITLE
an error when test.py  No such file or directory: '/images/val2014/COCO_val2014_000000000164.jpg'

### ISSUE THREAD

**Issue by bokerbi** [eriklindernoren/PyTorch-YOLOv3#488]

**Comment by ardeal** [comment]
according to the code, you should download COCO from:
wget -c https://pjreddie.com/media/files/train2014.zip
wget -c https://pjreddie.com/media/files/val2014.zip

however, some image files don't have corresponding label files, and some label files don'e have image files.

You should firstly make sure image files and labels files have corresponding matching files.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
