### ISSUE TITLE
class score ignored when calculating mAP

### ISSUE THREAD

**Issue by Eladamar** [eriklindernoren/PyTorch-YOLOv3#490]
I have noticed that the class scores(output[:, 5]) might be ignored in get_batch_statistics
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/utils.py#L155
so only the objectness later used to calculate all metrics in test.py. 
Am i missing something? if not, how should it be handled properly?

**Comment by Flova** [comment]
Duplicate of #233
