### ISSUE TITLE
IndexError: list index out of range(while training on custom dataset with two classes)

### ISSUE THREAD

**Issue by impravin22** [eriklindernoren/PyTorch-YOLOv3#492]
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    ap_table += [[c, class_names[c], "%.5f" % AP[i]]]
IndexError: list index out of range

**Comment by nodiz** [comment]
Hello, in utils.py, load_classes change 

```
    names = fp.read().split("\n")[:-1]
```

To

```
    names = fp.read().split("\n")
```


I didn't understand why the loader wasn't taking the last class into account so I just changed there. Then it should work

**Comment by impravin22** [comment]
> Hello, in utils.py, load_classes change
> 
> ```
>     names = fp.read().split("\n")[:-1]
> ```
> 
> To
> 
> ```
>     names = fp.read().split("\n")
> ```
> 
> I don't really understand why in the loader they are not taking the last class into account, but I just changed there. Then it should work


Thank you. It worked for me as I just press enter at the end of the line in the classes.names file. If you know how to detect the video, please do let me know.

Thanks

**Comment by swjtulinxi** [comment]
hello，why is my cls_acc==100%,

**Comment by cotyyang** [comment]
thanks,i also solved it

**Comment by Flova** [comment]
The names file needs a blank line at the end. It's also the case for the coco `.names` file.

**Comment by Flova** [comment]
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file
