### ISSUE TITLE
Problems on finetuning on custom dataset---TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Kravrolens** [eriklindernoren/PyTorch-YOLOv3#495]
hello，Thanks for your work!

When I make a custom dataset and train the model as the README.md said. But After having trained for about 100 batches(batch size=2) on cpus, Compiler raises the error : 

"TypeError: 'NoneType' object is not subscriptable", 
"Traceback (most recent call last): .........for batch_i, (_, imgs, targets) in enumerate(dataloader):......."
(in line 99 train.py)

I have run many times and always meet similar errors, and what's wrong? Thank you!

**Comment by Kravrolens** [comment]
[ #256](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/256) comments maybe helpful, I'll try again later.

**Comment by Kravrolens** [comment]
> [ #256](https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/256) comments maybe helpful, I'll try again later.

It is True.

**Comment by qzk1193564654** [comment]
Have you solved this problem? Thank you very much

**Comment by Kravrolens** [comment]
> Have you solved this problem? Thank you very much

yes，do as it says.

**Comment by qzk1193564654** [comment]
Hello, I'm sorry to disturb you，Did you change it according to this sentence?    
           I ran into this issue and it ended up being caused by having training images that did not have corresponding labels. I removed the images that did not have annotations and that fixed the problem. Hope that fixes the issue for you as well., 



The meaning of this sentence is the training images is not marked?  How did you solve it?
Thanks！

**Comment by Kravrolens** [comment]
> Hello, I'm sorry to disturb you，Did you change it according to this sentence?
> I ran into this issue and it ended up being caused by having training images that did not have corresponding labels. I removed the images that did not have annotations and that fixed the problem. Hope that fixes the issue for you as well.,
> 
> The meaning of this sentence is the training images is not marked? How did you solve it?
> Thanks！

yes, a few images did not have corresponding labels, so I cleared them.
