### ISSUE TITLE
some question about GT matching

### ISSUE THREAD

**Issue by zerostan** [eriklindernoren/PyTorch-YOLOv3#500]
I have read the ''build_targets( )" function in the module YOLO Layer. My question is that all targets will be matched in each yolo layer, and every target will match one anchor in each yolo layer, so each will match 3 anchors totally (there are 3 yolo layer). But the paper says there is one anchor for one target.

**Comment by yinghuang** [comment]
same question

**Comment by Flova** [comment]
There are 3 anchors per YOLO Layer. This results in 9 for the full-size YOLO and 6 for the tiny yolo.
