### ISSUE TITLE
training doesn't converge

### ISSUE THREAD

**Issue by ardeal** [eriklindernoren/PyTorch-YOLOv3#504]
Hi,

I used COCO to train the code on Tesla V100 on Ubuntu.
All the parameters are not changed(i.e. the same as those in the code on github).

I trained more than 100 epochs, the AP is around 28%, and the loss is around 5. 

I convert the pth model to onnx and plot the network which is the same as that plotted from cfg file. This means that the network is correct, but it doesn't converge.

Is there any ideas to trace the problem? 

+ ----------------
The issue is similar as #489 

the epoch 0/50, the training is continued after more than 100 epochs:

---- [Epoch 0/50, Batch 686/15278] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 15           | 30           | 60           |
| loss       | 0.933914     | 1.042986     | 0.841405     |
| x          | 0.026712     | 0.023458     | 0.035226     |
| y          | 0.018076     | 0.014557     | 0.036573     |
| w          | 0.090962     | 0.039141     | 0.035578     |
| h          | 0.050231     | 0.027877     | 0.021490     |
| conf       | 0.724891     | 0.915479     | 0.689265     |
| cls        | 0.023042     | 0.022475     | 0.023273     |
| cls_acc    | 65.31%       | 64.15%       | 60.38%       |
| recall50   | 0.551020     | 0.528302     | 0.509434     |
| recall75   | 0.530612     | 0.509434     | 0.509434     |
| precision  | 0.586957     | 0.417910     | 0.164634     |
| conf_obj   | 0.805160     | 0.732810     | 0.785851     |
| conf_noobj | 0.002448     | 0.002504     | 0.002176     |
+------------+--------------+--------------+--------------+
Total loss 2.818305015563965
---- ETA 1:31:33.039536
epoch == 000, batch_i==00686, lr == 0.001, loss == 2.818, accuracy_all == 0.0000

Thanks,
Ardeal

**Comment by ardeal** [comment]
The trained model is used for test. The following are ground truth and prediction result.

![image](https://user-images.githubusercontent.com/6227348/82393529-3f2f3480-9a79-11ea-96da-4466624899cc.png)

![image](https://user-images.githubusercontent.com/6227348/82393612-874e5700-9a79-11ea-97de-526f517647c1.png)

![image](https://user-images.githubusercontent.com/6227348/82393629-959c7300-9a79-11ea-9562-73bcf8aa7372.png)

![image](https://user-images.githubusercontent.com/6227348/82393665-b06ee780-9a79-11ea-83be-aa6a04331a79.png)

**Comment by Chenney0813** [comment]
do you solve this problem? my map is also 28

**Comment by ardeal** [comment]
Please check the conversation in this issue.
https://github.com/AlexeyAB/darknet/issues/5676


The AP is around 0.25 for epoch = 150. Sometimes, it is around 0.29. 
I am still training, hopefully, the accuracy could be the same as that in the YOLOv3 paper when the epoch=300.

**Comment by ardeal** [comment]
@Chenney0813 ,

after more than 150 epochs, my AP is around 0.31:

**Comment by Chenney0813** [comment]
> @Chenney0813 ,
> 
> after more than 150 epochs, my AP is around 0.31:
> 
> epoch == 052, batch_i==13642, lr == 0.001, loss == 4.775, accuracy_all == 0.3119
> epoch == 052, batch_i==13643, lr == 0.001, loss == 4.065, accuracy_all == 0.3119
> epoch == 052, batch_i==13644, lr == 0.001, loss == 2.725, accuracy_all == 0.3119

do you use the train.py evaluate or test.py evaluate?  the train.py evaluate conf_thes is 0.5 ,which is too high for compute ap. I am train the repo also now but i use 16batch .I will tell you my result after training

**Comment by ardeal** [comment]
In train.py file, these isn't evaluate function. there is only one in test.py file:

```Python
            precision, recall, AP, f1, ap_class = evaluate(
                model,
                path=valid_path,
                iou_thres=0.5,
                conf_thres=0.5,
                nms_thres=0.5,
                img_size=opt.img_size,
                batch_size=8,
            )
```

**Comment by ardeal** [comment]
I eventually confirmed that the code(https://github.com/eriklindernoren/PyTorch-YOLOv3) doesn't converge, but the code (https://github.com/ultralytics/yolov3) converges.

I trained eriklindernoren/PyTorch-YOLOv3 code for around 180 epoch, but the AP is around 0.26.  
 
however, I trained ultralytics/yolov3 code for only 21 epoch. the AP is much better. Furthermore, the increasement of AP is normal. The following table is the output of the training of code ultralytics/yolov3


|epoch|mem|lossbox|lossobj|losscls|losstotal|targets|img_size|P|R|mAP|F1|GIoU|obj|cls|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|1/299|6.23G| 5.22|  3.5| 5.61| 14.3|    5|  512|0.067|0.0138|0.0067|0.00813| 5.22|  2.4|  5.3|
|2/299|6.24G| 4.42| 2.66| 4.59| 11.7|    5|  320|0.119|0.0464|0.0363|0.0439| 4.31| 2.04| 4.45|
|3/299|6.29G| 4.13| 2.37| 3.98| 10.5|    5|  576|0.212|0.0929|0.0849|0.0961| 3.75| 1.84| 3.69|
|4/299|8.87G| 3.95| 2.33| 3.59| 9.87|    5|  320|0.268|0.144|0.125|0.144| 3.53| 1.76| 3.28|
|5/299|6.23G| 3.83| 2.26| 3.31|  9.4|    5|  640|0.306|0.185|0.165|0.188| 3.36| 1.71| 2.95|
|6/299|6.23G| 3.75| 2.24|  3.1| 9.09|    5|  384|0.355|0.217|  0.2|0.226| 3.23| 1.61|  2.7|
|7/299|6.29G| 3.68| 2.21| 2.95| 8.83|    5|  448|0.376|0.232| 0.22|0.246| 3.16| 1.56| 2.57|
|8/299| 8.8G| 3.62| 2.16| 2.81|  8.6|    5|  320|0.383|0.247|0.235|0.261| 3.12| 1.54| 2.48|
|9/299| 8.8G| 3.59| 2.18|  2.7| 8.48|    5|  576|0.402|0.257|0.246|0.272| 3.09| 1.53| 2.42|
|10/299|8.81G| 3.55| 2.15| 2.61|  8.3|    5|  384|0.409|0.264|0.255|0.282| 3.07| 1.52| 2.37|
|11/299|8.81G| 3.52| 2.16| 2.53| 8.21|    5|  320|0.422|0.269|0.264|0.289| 3.05| 1.51| 2.33|
|12/299|8.81G| 3.48| 2.13| 2.46| 8.07|    5|  640|0.437|0.275|0.273|0.298| 3.03|  1.5| 2.29|
|13/299| 8.8G| 3.46| 2.11|  2.4| 7.97|    5|  448|0.446| 0.28|0.282|0.306| 3.02| 1.49| 2.25|
|14/299| 8.8G| 3.44| 2.07| 2.34| 7.85|    5|  320|0.447|0.285| 0.29|0.314|    3| 1.49|  2.2|
|15/299| 8.8G| 3.42|  2.1|  2.3| 7.82|    5|  576|0.462|0.289|0.299|0.321| 2.99| 1.48| 2.16|
|16/299| 8.8G| 3.41|  2.1| 2.27| 7.78|    5|  320|0.475|0.294|0.307|0.328| 2.97| 1.47| 2.12|
|17/299| 8.8G| 3.39| 2.08| 2.22| 7.69|    5|  384|0.482|0.301|0.315|0.336| 2.95| 1.46| 2.08|
|18/299| 8.8G| 3.38| 2.07| 2.19| 7.64|    5|  576|0.491|0.306|0.324|0.343| 2.94| 1.45| 2.03|
|19/299| 8.8G| 3.36| 2.05| 2.16| 7.57|    5|  448|0.498|0.315|0.332|0.352| 2.92| 1.45| 1.99|
|20/299| 8.8G| 3.35| 2.06| 2.13| 7.53|    5|  384|0.502|0.325|0.341|0.362|  2.9| 1.44| 1.94|
|21/299| 8.8G| 3.33| 2.02| 2.11| 7.46|    5|  320|0.502|0.333|0.348|0.369| 2.88| 1.43|  1.9|

**Comment by Chenney0813** [comment]
> I eventually confirmed that the code(https://github.com/eriklindernoren/PyTorch-YOLOv3) doesn't converge, but the code (https://github.com/ultralytics/yolov3) converges.
> 
> I trained eriklindernoren/PyTorch-YOLOv3 code for around 180 epoch, but the AP is around 0.26.
> 
> however, I trained ultralytics/yolov3 code for only 21 epoch. the AP is much better. Furthermore, the increasement of AP is normal. The following table is the output of the training of code ultralytics/yolov3
> 
> epoch	mem	lossbox	lossobj	losscls	losstotal	targets	img_size	P	R	mAP	F1	GIoU	obj	cls
> 1/299	6.23G	5.22	3.5	5.61	14.3	5	512	0.067	0.0138	0.0067	0.00813	5.22	2.4	5.3
> 2/299	6.24G	4.42	2.66	4.59	11.7	5	320	0.119	0.0464	0.0363	0.0439	4.31	2.04	4.45
> 3/299	6.29G	4.13	2.37	3.98	10.5	5	576	0.212	0.0929	0.0849	0.0961	3.75	1.84	3.69
> 4/299	8.87G	3.95	2.33	3.59	9.87	5	320	0.268	0.144	0.125	0.144	3.53	1.76	3.28
> 5/299	6.23G	3.83	2.26	3.31	9.4	5	640	0.306	0.185	0.165	0.188	3.36	1.71	2.95
> 6/299	6.23G	3.75	2.24	3.1	9.09	5	384	0.355	0.217	0.2	0.226	3.23	1.61	2.7
> 7/299	6.29G	3.68	2.21	2.95	8.83	5	448	0.376	0.232	0.22	0.246	3.16	1.56	2.57
> 8/299	8.8G	3.62	2.16	2.81	8.6	5	320	0.383	0.247	0.235	0.261	3.12	1.54	2.48
> 9/299	8.8G	3.59	2.18	2.7	8.48	5	576	0.402	0.257	0.246	0.272	3.09	1.53	2.42
> 10/299	8.81G	3.55	2.15	2.61	8.3	5	384	0.409	0.264	0.255	0.282	3.07	1.52	2.37
> 11/299	8.81G	3.52	2.16	2.53	8.21	5	320	0.422	0.269	0.264	0.289	3.05	1.51	2.33
> 12/299	8.81G	3.48	2.13	2.46	8.07	5	640	0.437	0.275	0.273	0.298	3.03	1.5	2.29
> 13/299	8.8G	3.46	2.11	2.4	7.97	5	448	0.446	0.28	0.282	0.306	3.02	1.49	2.25
> 14/299	8.8G	3.44	2.07	2.34	7.85	5	320	0.447	0.285	0.29	0.314	3	1.49	2.2
> 15/299	8.8G	3.42	2.1	2.3	7.82	5	576	0.462	0.289	0.299	0.321	2.99	1.48	2.16
> 16/299	8.8G	3.41	2.1	2.27	7.78	5	320	0.475	0.294	0.307	0.328	2.97	1.47	2.12
> 17/299	8.8G	3.39	2.08	2.22	7.69	5	384	0.482	0.301	0.315	0.336	2.95	1.46	2.08
> 18/299	8.8G	3.38	2.07	2.19	7.64	5	576	0.491	0.306	0.324	0.343	2.94	1.45	2.03
> 19/299	8.8G	3.36	2.05	2.16	7.57	5	448	0.498	0.315	0.332	0.352	2.92	1.45	1.99
> 20/299	8.8G	3.35	2.06	2.13	7.53	5	384	0.502	0.325	0.341	0.362	2.9	1.44	1.94
> 21/299	8.8G	3.33	2.02	2.11	7.46	5	320	0.502	0.333	0.348	0.369	2.88	1.43	1.9

thank you very much!  in my experiment, this repo doesn't converge too. in 7 epoch, the loss is around 7, and not in 30 epoch, the loss is around 5. the mAp increase slowly ,I think it may cause by  data argument,  cos lr , burn in ,which seems not to show in this repo and the loss function

**Comment by ardeal** [comment]
This my training result of ultralytics/yolov3 code after 30 epochs.
The result is obviously good.  


|epoch|mem|lossbox|lossobj|losscls|losstotal|targets|img_size|P|R|mAP|F1|GIoU|obj|cls|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|1/299|6.23G| 5.22|  3.5| 5.61| 14.3|    5|  512|0.067|0.0138|0.0067|0.00813| 5.22|  2.4|  5.3|
|2/299|6.24G| 4.42| 2.66| 4.59| 11.7|    5|  320|0.119|0.0464|0.0363|0.0439| 4.31| 2.04| 4.45|
|3/299|6.29G| 4.13| 2.37| 3.98| 10.5|    5|  576|0.212|0.0929|0.0849|0.0961| 3.75| 1.84| 3.69|
|4/299|8.87G| 3.95| 2.33| 3.59| 9.87|    5|  320|0.268|0.144|0.125|0.144| 3.53| 1.76| 3.28|
|5/299|6.23G| 3.83| 2.26| 3.31|  9.4|    5|  640|0.306|0.185|0.165|0.188| 3.36| 1.71| 2.95|
|6/299|6.23G| 3.75| 2.24|  3.1| 9.09|    5|  384|0.355|0.217|  0.2|0.226| 3.23| 1.61|  2.7|
|7/299|6.29G| 3.68| 2.21| 2.95| 8.83|    5|  448|0.376|0.232| 0.22|0.246| 3.16| 1.56| 2.57|
|8/299| 8.8G| 3.62| 2.16| 2.81|  8.6|    5|  320|0.383|0.247|0.235|0.261| 3.12| 1.54| 2.48|
|9/299| 8.8G| 3.59| 2.18|  2.7| 8.48|    5|  576|0.402|0.257|0.246|0.272| 3.09| 1.53| 2.42|
|10/299|8.81G| 3.55| 2.15| 2.61|  8.3|    5|  384|0.409|0.264|0.255|0.282| 3.07| 1.52| 2.37|
|11/299|8.81G| 3.52| 2.16| 2.53| 8.21|    5|  320|0.422|0.269|0.264|0.289| 3.05| 1.51| 2.33|
|12/299|8.81G| 3.48| 2.13| 2.46| 8.07|    5|  640|0.437|0.275|0.273|0.298| 3.03|  1.5| 2.29|
|13/299| 8.8G| 3.46| 2.11|  2.4| 7.97|    5|  448|0.446| 0.28|0.282|0.306| 3.02| 1.49| 2.25|
|14/299| 8.8G| 3.44| 2.07| 2.34| 7.85|    5|  320|0.447|0.285| 0.29|0.314|    3| 1.49|  2.2|
|15/299| 8.8G| 3.42|  2.1|  2.3| 7.82|    5|  576|0.462|0.289|0.299|0.321| 2.99| 1.48| 2.16|
|16/299| 8.8G| 3.41|  2.1| 2.27| 7.78|    5|  320|0.475|0.294|0.307|0.328| 2.97| 1.47| 2.12|
|17/299| 8.8G| 3.39| 2.08| 2.22| 7.69|    5|  384|0.482|0.301|0.315|0.336| 2.95| 1.46| 2.08|
|18/299| 8.8G| 3.38| 2.07| 2.19| 7.64|    5|  576|0.491|0.306|0.324|0.343| 2.94| 1.45| 2.03|
|19/299| 8.8G| 3.36| 2.05| 2.16| 7.57|    5|  448|0.498|0.315|0.332|0.352| 2.92| 1.45| 1.99|
|20/299| 8.8G| 3.35| 2.06| 2.13| 7.53|    5|  384|0.502|0.325|0.341|0.362|  2.9| 1.44| 1.94|
|21/299| 8.8G| 3.33| 2.02| 2.11| 7.46|    5|  320|0.502|0.333|0.348|0.369| 2.88| 1.43|  1.9|
|22/299| 8.8G| 3.33| 2.03| 2.09| 7.45|    5|  320|0.504|0.343|0.356|0.377| 2.87| 1.42| 1.86|
|23/299| 8.8G| 3.32| 2.03| 2.06| 7.41|    5|  640|0.503|0.353|0.364|0.384| 2.85| 1.41| 1.82|
|24/299| 8.8G| 3.31| 2.04| 2.04| 7.38|    5|  448|0.498|0.363| 0.37|0.391| 2.83| 1.41| 1.79|
|25/299| 8.8G|  3.3| 2.01| 2.02| 7.33|    5|  576|0.493|0.373|0.377|0.398| 2.82|  1.4| 1.75|
|26/299| 8.8G|  3.3| 2.06| 2.01| 7.38|    5|  640|0.487|0.383|0.383|0.404|  2.8| 1.39| 1.72|
|27/299| 8.8G| 3.29| 2.02| 1.99|  7.3|    5|  512|0.484|0.391|0.389|0.409| 2.79| 1.39| 1.69|
|28/299| 8.8G| 3.28| 2.02| 1.97| 7.27|    5|  384|0.477|  0.4|0.395|0.414| 2.78| 1.38| 1.66|

**Comment by summeryumyee** [comment]
@ardeal  I've been following you for a long time.Which dataset did you train in and what version of cfg did you use? is default yolov3.cfg?
Thank you!

**Comment by ardeal** [comment]
@summeryumyee,
I am using COCO 2014.
yes, the cfg I am using is the default yolov3.cfg downloaded from the git.

**Comment by gaojunbin** [comment]
@ardeal 
Hello, I meet the same problem with you. after training for 35 epochs, the mAP is only around 16.7%. Do you know why this code doesn't converge? I read the code but not find problems yet but the result is poor. I am confused. What's more, when I use the yolov3.weithts as pre-trained model, the loss is very high. I don't know why? can you help me, thank you

**Comment by jiu-jian-xian** [comment]
来个人一起研究下啊 我的loss倒是收敛了 但是结果不对呀

**Comment by gaojunbin** [comment]
> 来个人一起研究下啊 我的loss倒是收敛了 但是结果不对呀

Can you leave a contact

**Comment by dickygiancini** [comment]
i also find this repo did not converge well, when i evaluate some weights they seems to go up and down for no reason

**Comment by qin79** [comment]
how can you know the best ckpt.pth in the training? by using the test.py to evaluate is too slow...

**Comment by Flova** [comment]
If you evaluated during training you can use tensorboard to have a look at it.

**Comment by Flova** [comment]
Also I stumbled across some serious issues regarding the loading of the optimizer params (they aren't loaded at all) so there will be some progress in the future which will help this repo to converge better.

**Comment by dickygiancini** [comment]
> Also I stumbled across some serious issues regarding the loading of the optimizer params (they aren't loaded at all) so there will be some progress in the future which will help this repo to converge better.

i hope so, also i think for convergance reasons, using SGD instead of Adam might be better (havent test myself, but there is a paper that covers it)

**Comment by Flova** [comment]
> i hope so, also i think for convergence reasons, using SGD instead of Adam might be better (haven't test myself, but there is a paper that covers it)

Getting SGD to work is quite hard, it is implemented, but converges very slowly. I made some adjustments that should improve the convergence with ADAM a lot.

Current mAP/Epoch with a 416x416 px resolution:
![image](https://user-images.githubusercontent.com/15075613/125204459-bc20fd00-e27d-11eb-9e1f-6e93f4f0b60c.png)

It would be possible to reach the given 55 mAP with some further hyperparameter tuning / longer training
