### ISSUE TITLE
random_resize

### ISSUE THREAD

**Issue by mao-jy** [eriklindernoren/PyTorch-YOLOv3#511]
To make it easier to train, I use k-means to determine my initial anchors. The steps are: 
1. pad to the original images to square and then resize them to 416*416 in the way that the author used in datasets.py. 
2. compute the width and height(0 < width, height < 1) of all anchors. 
3. use k-means to obtain 9 pair of [width, height] and then multiply them by 416 to get 9 anchors.

I notice that the author use random_resize to preprocess the images, and it may resize the images to some resolution which is not 416*416. But the scale of anchors is not changed, which is still kept under 416. Will this cause a problem? 

Somebody can explain this plz?

**Comment by swjtulinxi** [comment]
when detecting,   how to save the  input image size  as  original size

**Comment by Lixueqingqq** [comment]
@mao-jy I have the same problem, Have you solved it

**Comment by mao-jy** [comment]
> @mao-jy I have the same problem, Have you solved it

No, I haven't found the answer.

**Comment by voodoopotato** [comment]
I found the author's preprocessing and data loading code to be very troublesome. I suggest that you write your own.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
