### ISSUE TITLE
the procedure entry point ***** could not be located in dynamic link library 

### ISSUE THREAD

**Issue by elharroussomar** [eriklindernoren/PyTorch-YOLOv3#514]
I m trying to train the present model on custom data but when I run the code the following error in a dialog angle shown: 
the procedure entry point ?tls_local_tensor_type_@....... set could not be located in the dynamic link library 
C:\......\lib\site-packages\torchvision\_C.pyd.
Can anyone help?
best regards,

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
