### ISSUE TITLE
train time for one epoch is too long

### ISSUE THREAD

**Issue by Stephanessy** [eriklindernoren/PyTorch-YOLOv3#517]
I am training on coco2014. One epoch takes about four hours, is this normal? After one epoch, mAP is 0.0063.

**Comment by khasebou** [comment]
his code is disk read intensive. thus bottle necking the gpu

**Comment by voodoopotato** [comment]
I manage to reduce training time per epoch to about 1000 seconds by taking advantage of PyTorch's distributed parallel package + Nvidia Apex optimization package.

**Comment by Stephanessy** [comment]
@voodoopotato That's really cool! I will try these on my project. Thanks!

**Comment by voodoopotato** [comment]
@Stephanessy after experimenting, I abandon this repo for another one due to the fact that this implementation is good only for inference.  I suggest you don't waste your time and resource using this repo to train on custom dataset.

**Comment by ChengChen2020** [comment]
> @Stephanessy after experimenting, I abandon this repo for another one due to the fact that this implementation is good only for inference. I suggest you don't waste your time and resource using this repo to train on custom dataset.

Hello, may I ask which repo do you use for training @ScottHoang ? Thank you.
