### ISSUE TITLE
这个代码可以实现预测功能么，输入一张图片能预测么

### ISSUE THREAD

**Issue by liupenglei** [eriklindernoren/PyTorch-YOLOv3#524]

**Comment by CescMessi** [comment]
先用`download_weights.sh`下载权重文件，把你的图片放到 data/samples/里面，然后运行`$ python3 detect.py --image_folder data/samples/`

最好不要用中文提问。

First download the weight file with `download_weights.sh`, put your picture in data/samples/, then run `$ python3 detect.py --image_folder data/samples/`

**Comment by liupenglei** [comment]
> 先用`download_weights.sh`下载权重文件，把你的图片放到 data/samples/里面，然后运行`$ python3 detect.py --image_folder data/samples/`
> 
> 最好不要用中文提问。
> 
> First download the weight file with `download_weights.sh`, put your picture in data/samples/, then run `$ python3 detect.py --image_folder data/samples/`

thank you very much

**Comment by B1D1ng** [comment]
> 先用`download_weights.sh`下载权重文件，把你的图片放到 data/samples/里面，然后运行`$ python3 detect.py --image_folder data/samples/`
> 
> 最好不要用中文提问。
> 
> First download the weight file with `download_weights.sh`, put your picture in data/samples/, then run `$ python3 detect.py --image_folder data/samples/`
请问老哥知道这个版本的数据格式怎么转换吗,我有标记好的图片和.xml文件,但是不知道这个版本是怎么生成train.txt valid.txt以及最后的label文件夹里面的txt文件.求老哥指点

**Comment by CescMessi** [comment]
> > 先用`download_weights.sh`下载权重文件，把你的图片放到 data/samples/里面，然后运行`$ python3 detect.py --image_folder data/samples/`
> > 最好不要用中文提问。
> > First download the weight file with `download_weights.sh`, put your picture in data/samples/, then run `$ python3 detect.py --image_folder data/samples/`
> 
> 请问老哥知道这个版本的数据格式怎么转换吗,我有标记好的图片和.xml文件,但是不知道这个版本是怎么生成train.txt valid.txt以及最后的label文件夹里面的txt文件.求老哥指点

train.txt里面是所有训练图片的路径，每行一张图片，valid.txt类似，label里面的txt文件是每张图片一个文件，每行表示一个框，顺序是类别、中心x、中心y、宽、高，坐标和宽度是相对图片的比例。看一下data/custom/里面的文件就知道了。

**Comment by Flova** [comment]
Please provide an English explanation of your issue.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
