### ISSUE TITLE
MODEL size

### ISSUE THREAD

**Issue by erolgerceker** [eriklindernoren/PyTorch-YOLOv3#525]
How can i reduce the model size? or convert another format?
it is too big (240MB) :(
i used the tiny model but accuracy is not sufficent

**Comment by voodoopotato** [comment]
the size of the model is directly correlated to the number of operations, so changing to different "format" will not reduce to the overall size. If you are planning to cramp this model on something like a Pi4, I suggest experimentation with which layer you can discard while maintaining adequate accuracy
