### ISSUE TITLE
I can't download weights for pretrain

### ISSUE THREAD

**Issue by CAM1113** [eriklindernoren/PyTorch-YOLOv3#526]
When I run download_weights.sh, I got 404.

**Comment by voodoopotato** [comment]
don't bother with this repo. This implementation is only good for running inference on Yolo's weights trained with darknet. It doesn't converge when train natively on PyTorch.

**Comment by itsjoshthedeveloper** [comment]
@CAM1113 For all the `wget` calls in `download_weights.sh` and `get_coco_dataset.sh`, you need to add `--header "Referer: pjreddie.com"` and enclose the http link with quotes to make it a string. Found the solution [here](https://stackoverflow.com/questions/7623698/wget-cant-download-404-error).

**Comment by Flova** [comment]
Interesting the download works for me on the current master.

**Comment by jaagut** [comment]
I think it does no harm, if we add this fix. At least, it could fix the issue for some users.

**Comment by Flova** [comment]
I agree with you.

**Comment by itsjoshthedeveloper** [comment]
I can make a PR

**Comment by Flova** [comment]
PR is merged. Thanks for your contribution @itsjoshthedeveloper
