### ISSUE TITLE
error in collect_fn

### ISSUE THREAD

**Issue by zhangkui669** [eriklindernoren/PyTorch-YOLOv3#528]
![image](https://user-images.githubusercontent.com/29877991/84653774-932a1d80-af40-11ea-8614-a98db8cc2aa1.png)
add sample index operation should applied before remove empty target, otherwise it will point to wrong image

by the way, this operation simplify the build_targets operation, but it not friendly when use multi-gpus to train

**Comment by jiu-jian-xian** [comment]
是的 我也发现了这个问题！

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
