### ISSUE TITLE
use tensorrt , got this problem :IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by yingjie-jiang** [eriklindernoren/PyTorch-YOLOv3#529]
find code in utils/utils.py:
     non_max_suppression(prediction, conf_thres=0.5, nms_thres=0.4, method=1)
change code:
    image_pred = image_pred[(-score).argsort()]
to
    image_pred = image_pred[(-score.numpy()).argsort()]

**Comment by Flova** [comment]
Could you provide additional info on the tensorrt thing. Afiak it isn't a part of this repo.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
