### ISSUE TITLE
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 3267995

### ISSUE THREAD

**Issue by ThanhPham1987** [eriklindernoren/PyTorch-YOLOv3#533]
Hi all,
 python3 detect.py --image_folder data/samples/
Namespace(batch_size=1, checkpoint_model=None, class_path='data/coco.names', conf_thres=0.8, image_folder='data/samples/', img_size=416, model_def='config/yolov3.cfg', n_cpu=0, nms_thres=0.4, weights_path='weights/yolov3.weights')
Traceback (most recent call last):
  File "detect.py", line 48, in <module>
    model.load_darknet_weights(opt.weights_path)
  File "/home/thanhpham/PycharmProjects/YoloV3_Pytorch/PyTorch-YOLOv3/models.py", line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 3267995

Please help me!!!

**Comment by bianlongpeng** [comment]
@ThanhPham1987  this issue  may help you [https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/479]

**Comment by ThanhPham1987** [comment]
@bianlongpeng thanks

**Comment by Reddevil811** [comment]
@ThanhPham1987 Did it help? Because I still get the same error even after changing the yolov3-custom.cfg according to the number of classes i wanted

**Comment by Flova** [comment]
Did you also change the number of filters before the yolo layer?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
