### ISSUE TITLE
get_batch_statistics()函数中是不是有点小问题啊？

### ISSUE THREAD

**Issue by datuizhuang** [eriklindernoren/PyTorch-YOLOv3#534]
在代码中有：iou, box_index = bbox_iou(pred_box.unsqueeze(0), target_boxes).max(0)。
我觉得这里pred box应该与同类别的GT计算IOU才对吧？然后根据IOU和阈值比较，判断当前pred box是否为TP。

**Comment by youzhaxiaomayi** [comment]
I agree you

**Comment by zxj11838** [comment]
I have another question. Suppose there are two target_box, when pred_box[0] matches target_box[0]、target_box[1], will a pred_box match two target box?

**Comment by dlmuzpy** [comment]
I agree with you. Using the 'evaluate' function here will make Map higher than normal.

**Comment by Flova** [comment]
Please provide an English explanation of your issue.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
