### ISSUE TITLE
I find the way you caculate coordinates after padding might be wrong.

### ISSUE THREAD

**Issue by tengjunvan** [eriklindernoren/PyTorch-YOLOv3#535]
In datasets.py ,  line : 114-117, I think it should be:
            x1 += pad[0]
            y1 += pad[2]
            x2 += pad[0]
            y2 += pad[2]

original code is like:
            x1 += pad[0]
            y1 += pad[2]
            x2 += pad[1]
            y2 += pad[3]

Why caculate the right padding?

**Comment by tengjunvan** [comment]
If i'm right, this is fatal.

**Comment by tengjunvan** [comment]
If i am right, this might be very serious cause the coordinate label is not accurate for each sample.

**Comment by changshuangzhao** [comment]
I am agree

**Comment by wangsssky** [comment]
Yes， I fixed it, but still can not get a well-trained model from scratch.

**Comment by Flova** [comment]
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.
