### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by lonelywm** [eriklindernoren/PyTorch-YOLOv3#54]
After running 8 epochs on my 1080ti about 6 hours, and the checkpoints folder has 7 files: [0..7].weights. I run "python detect.py --weights_path checkpoints/7.weights" to detect.But no detections, if I download the wights from "https://pjreddie.com/media/files/yolov3.weights", It can detect,  So I suspect there is something wrong with the training, or I have to wait until 30 epochs.

**Comment by lonelywm** [comment]
[Epoch 16/30, Batch 4400/7329] [Losses: x 0.013750, y 0.013628, w 0.003818, h 0.003543, conf 0.037071, cls 0.005950, total 0.077760, recall: 0.61353]
[Epoch 16/30, Batch 4410/7329] [Losses: x 0.008723, y 0.008725, w 0.002754, h 0.001924, conf 0.028565, cls 0.003257, total 0.053949, recall: 0.62105]

==================
before saving img I print the len:  

print(len(detections) if detections is not None else 0)
=====================
Saving images:
(0) Image: 'data/samples/dog.jpg'
0
(1) Image: 'data/samples/eagle.jpg'
0
(2) Image: 'data/samples/giraffe.jpg'
0
(3) Image: 'data/samples/herd_of_horses.jpg'
0
(4) Image: 'data/samples/img1.jpg'
0
(5) Image: 'data/samples/img2.jpg'
0
(6) Image: 'data/samples/img3.jpg'
0
(7) Image: 'data/samples/img4.jpg'
0
(8) Image: 'data/samples/messi.jpg'
0
(9) Image: 'data/samples/person.jpg'
0

**Comment by Ricardozzf** [comment]
@lonelywm have u solved it?

**Comment by lonelywm** [comment]
yes

**Comment by Ricardozzf** [comment]
@lonelywm would you mind sharing the detail how you solve it? I have been confused with it for a long tiim. :(

**Comment by lonelywm** [comment]
I diy  just use L1_Loss instead of bceloss for x y w h

**Comment by Ricardozzf** [comment]
@lonelywm Thanks for your reply.

I will try it as you suggest.

**Comment by eriklindernoren** [comment]
Hi, let's keep training issues in #2.
