### ISSUE TITLE
command error when run python3 train.py --data_config config/coco.data  --pretrained_weights

### ISSUE THREAD

**Issue by zzy444626905** [eriklindernoren/PyTorch-YOLOv3#542]
(yolov5) [root@centoskafka PyTorch-YOLOv3]# python3 train.py --data_config config/coco.data  --pretrained_weights weights/darknet53.conv.74
Illegal instruction

**Comment by ThanhPham1987** [comment]
me too

**Comment by Flova** [comment]
Is this only for this configuration. 
Sadly I think that this is some dependent that is broken. Try updating the requirements.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
