### ISSUE TITLE
detect.py conf problem

### ISSUE THREAD

**Issue by YoonSungLee** [eriklindernoren/PyTorch-YOLOv3#544]
Hi, I have used this repo, because I want to do my project associated with YOLO v3.
When I run detect.py to my custom dataset, I found a strange output.
The results are as follows:

![test](https://user-images.githubusercontent.com/56310840/87637328-fc3dc480-c77c-11ea-9444-8b1a9f8bab25.PNG)

I knew that this code set 0.8 object confidence threshold by default value. But, from the above results, I found that **'Label: with_mask, Conf: 0.28812'** in the last line. I don't know why these results came out.

Am I wrong about the concept of conformance? Or is there code I have to change?
Thank you!

**Comment by wangsssky** [comment]
There are two different conf there.

**Comment by YoonSungLee** [comment]
> There are two different conf there.

I don't know what you mean. Could you tell me more detail?

**Comment by wangsssky** [comment]
there are obj conf and cls conf.  the thresh is for obj, and the output is cls.

**Comment by YoonSungLee** [comment]
> there are obj conf and cls conf. the thresh is for obj, and the output is cls.

Thank you for your answer.
Then, even though no matter how small it is, can it make a bbox?

**Comment by wangsssky** [comment]
> > there are obj conf and cls conf. the thresh is for obj, and the output is cls.
> 
> Thank you for your answer.
> Then, even though no matter how small it is, can it make a bbox?

Sorry, I didn't quite get your question. if you mean we set a low thresh, Yes, we can still get boxes, but there can be a lot of false detections.

**Comment by gaojunbin** [comment]
Hello, I think in this project, we can only set thresh for obj conf. The result shows the conf of cls, It is the max  conf in all 80 classes. no matter how small it is, it represents the maximum conf during all 80 classes.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
