### ISSUE TITLE
multiscale training problem

### ISSUE THREAD

**Issue by ghang-ouc** [eriklindernoren/PyTorch-YOLOv3#547]
def collate_fn(self, batch):
        paths, imgs, targets = list(zip(*batch))
        print(self.batch_count)
        print(self.img_size)
        print(targets)
        print(paths)
        # Remove empty placeholder targets
        targets = [boxes for boxes in targets if boxes is not None]
        # Add sample index to targets
        for i, boxes in enumerate(targets):
            boxes[:, 0] = i  
        targets = torch.cat(targets, 0)  
        # Selects new image size every tenth batch
        if self.multiscale and self.batch_count % 10 == 0:
            self.img_size = random.choice(range(self.min_size, self.max_size + 1, 32))
        # Resize images to input shape
        imgs = torch.stack([resize(img, self.img_size) for img in imgs])
        self.batch_count += 1
        print(targets)
        print(paths)
        return paths, imgs, targets

I don’t understand why you are resizing the image here, and the target has not changed accordingly. The position of the target boxes does not match the size of the picture.
“if self.multiscale and self.batch_count % 10 == 0:
            self.img_size = random.choice(range(self.min_size, self.max_size + 1, 32))”

**Comment by FantasyJXF** [comment]
I noticed this too, I think this a bug on multiscale training, we should scale up the targets too if we use multiscale training

**Comment by FantasyJXF** [comment]
The targets has rescale to [0-1]
