### ISSUE TITLE
Discussion of mAP and epoch number

### ISSUE THREAD

**Issue by YoonSungLee** [eriklindernoren/PyTorch-YOLOv3#548]
Hi, I'm using well this repo in my custom dataset.
while doing my project with this repo, I had a two question about this.

1. discussion of mAP
After training this model with my custom dataset, I found that it has about 0.72 mAP to my custom test dataset. So, I thought it is a higher score than expected. But after running detect.py in my test dataset, I found that there are a little people which this model couldn't detect. I think the model with this performance can't use in daily life. I think this model has a low recall score. What can I do for this problem?

2. Epoch number
After considering the problem above, I was wondering what I should do with the number of epoch. I set 100 epoch that is default number of this repo. Can I know the criterion of setting epoch? Or is it a not crucial point of my problem?

Thank you for reading my issue.

**Comment by arunm8489** [comment]
@YoonSungLee
I think you can train the model with anchor boxes of small aspect ratio. Do k means clustering based on iou on your bounding boxes to get anchor box suggestions. May this will help.

**Comment by Flova** [comment]
Hi,
I am sad to hear that your training fails.

* Using the 100th epoch isn't the best choice. Have a look at your tensorboard and look if the validation mAP peaked before this Epoch. Maybe you are overfitting, You could also increase the epoch count until the mAP starts to go down again or your training takes too long. After doing this pick the checkpoint of the peak.
* What is the size of your test and training dataset?

**Comment by qin79** [comment]
> Hi,
> I am sad to hear that your training fails.
> 
>     * Using the 100th epoch isn't the best choice. Have a look at your tensorboard and look if the validation mAP peaked before this Epoch. Maybe you are overfitting, You could also increase the epoch count until the mAP starts to go down again or your training takes too long. After doing this pick the checkpoint of the peak.
> 
>     * What is the size of your test and training dataset?
> 
> 
> Flo

i'm not sure how to find the best ckpt.pth in my trained model(100epoch). by evaluating mAP using the test.py is too slow.

**Comment by Flova** [comment]
If you evaluated them during training it is already done and you can pick one with the mAP shown in the logs in tensorboard.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
