### ISSUE TITLE
some problems in detect.py,anyone help me please

### ISSUE THREAD

**Issue by wuhao2212** [eriklindernoren/PyTorch-YOLOv3#558]
when I run the detect.py , I found that the image  pixel value all become 0  after I pull it out from dataloader,  what happened ??

here is the code,  all tensors are  00000000000000000000000!!!!    

![QQ截图20200813182815](https://user-images.githubusercontent.com/57285480/90126059-9b160a80-dd95-11ea-9ca3-6dca88784edb.png)

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
