### ISSUE TITLE
 54/5000  I am a student at Tsinghua University. After training, while doing validation (eval) on my own data set, the following error occurred. My NCPU was set to 1

### ISSUE THREAD

**Issue by xianglei3** [eriklindernoren/PyTorch-YOLOv3#561]
python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data
then the erros is:
BrokenPipeError: [Errno 32] Broken pipe
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 5645) is killed by signal: Killed.

**Comment by Flova** [comment]
Please test this with the new dataloader.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
