### ISSUE TITLE
 I am a student of Tsinghua University. I am currently practicing in Tencent. I use custom datasets for training and verification. When the interval of verification is set to more than 2, the following error appears after several times. Please kneel down for your reply 

### ISSUE THREAD

**Issue by xianglei3** [eriklindernoren/PyTorch-YOLOv3#562]
i use :
python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data  --evaluation_interval 2

---- Evaluating Model ----
Detecting objects: 100%|████████████████████████████| 10/10 [00:02<00:00,  3.82it/s]
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    batch_size=1,
  File "/home/gpdi/xl/ys/test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by viperit** [comment]
That means your 'sample_metrics' (in test.py)is empty, which is say the model doesn't detect anything.

**Comment by GreysonPhoenix** [comment]
Did you use negative samples in your custom dataset? In that case, modify a line in utils.get_batch_statistics. In the file utils.py, about line 160, you can find  'annotations = targets[targets[:, 0] == sample_i][:, 1:] if len(targets)'. Modify it to  'annotations = targets[targets[:, 0] == sample_i][:, 1:] if len(targets) else []'

**Comment by jaychen1996-byte** [comment]
Train according to the correct configuration. This situation means that you have not trained enough epochs. You can try to use a pre-trained model to quickly verify your problem.
