### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by zhangnan-hust** [eriklindernoren/PyTorch-YOLOv3#564]
when I run the detect.py the result like this, and I try to solve the error about qt.qpa.plugin by searching on the Internet but none of the method worked.

/home/pdg/anaconda3/envs/pytorch/bin/python /home/pdg/下载/github/PyTorch-YOLOv3-master/detect.py
Namespace(batch_size=1, checkpoint_model=None, class_path='data/coco.names', conf_thres=0.8, image_folder='data/samples', img_size=416, model_def='config/yolov3.cfg', n_cpu=0, nms_thres=0.4, weights_path='weights/yolov3.weights')

Performing object detection:
	+ Batch 0, Inference Time: 0:00:00.742195
	+ Batch 1, Inference Time: 0:00:00.555316
	+ Batch 2, Inference Time: 0:00:00.571946
	+ Batch 3, Inference Time: 0:00:00.547146
	+ Batch 4, Inference Time: 0:00:00.554333
	+ Batch 5, Inference Time: 0:00:00.596538
	+ Batch 6, Inference Time: 0:00:00.721775
	+ Batch 7, Inference Time: 0:00:00.651040
	+ Batch 8, Inference Time: 0:00:00.826751

Saving images:
(0) Image: 'data/samples/dog.jpg'
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by zhangnan-hust** [comment]
I got the solution from the Qt Forum:
sudo apt-get install libxcb-xinerama0
Thanks!

**Comment by Flova** [comment]
Does your machine feature a graphical output?
