### ISSUE TITLE
Can anyone guide me, how i can change yolov3 backbone from darknet53 to some other network like resnet,vgg using this repo. Help plz :)

### ISSUE THREAD

**Issue by zunairaR** [eriklindernoren/PyTorch-YOLOv3#566]

**Comment by Ema1997** [comment]
change the yolov3.cfg in config

**Comment by zunairaR** [comment]
thanks for your reply, but i have tried alot. and everytime I get assertion error. :(
Can you please elaborate how I can change it.

**Comment by kjunhwa** [comment]
Did you solve the problem? Either I want to change to other model such as resnet, vgg, efficientnet...  Where can i get config file or how to make it?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
