### ISSUE TITLE
yolov3-tiny: shape '[1, 3, 85, 12, 12]' is invalid for input of size 39780

### ISSUE THREAD

**Issue by ajaykumaar** [eriklindernoren/PyTorch-YOLOv3#567]
Hi @eriklindernoren ,
I'm using yolov3-tiny weights and config files from this repo and I run into the error:
Runtime error: shape '[1, 3, 85, 12, 12]' is invalid for input of size 39780

What changed should I make or have this issue been solved?

Thanks in advance

**Comment by Flova** [comment]
What dataset are you using? Does the number of classes match the one in the `.cfg`?

**Comment by Flova** [comment]
If you change the number of classes you have to adapt `classes` in the `.cfg`. But you also have to adapt the filters of the previous layer to `(classes + 5) * 3`.

**Comment by Flova** [comment]
In your case, it would be 255 for the filters.
