### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Zongwei996** [eriklindernoren/PyTorch-YOLOv3#569]
true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)
could you help me about the question

**Comment by xiaomore** [comment]
I also have this problem, please tell me how you solve it? Thanks!!

**Comment by Flova** [comment]
Closing due to duplication of #178. Have a look over there.
