### ISSUE TITLE
IOU of gt bbox and anchors

### ISSUE THREAD

**Issue by weiaicunzai** [eriklindernoren/PyTorch-YOLOv3#57]
I've noticed when you compute the iou of gt bbox and anchors, sets their center coordinates to zero, why is that? Could you please tell me why??
```
gt_box = torch.FloatTensor(np.array([0, 0, gw, gh])).unsqueeze(0)
# Get shape of anchor box
anchor_shapes = torch.FloatTensor(np.concatenate((np.zeros((len(anchors), 2)), np.array(anchors)), 1))
# Calculate iou between gt and anchor shapes
anch_ious = bbox_iou(gt_box, anchor_shapes)
```
Or for any one who figured out,  could you please let me know? Thanks

**Comment by glenn-jocher** [comment]
This is simply determining the best anchor to assign to the truth box. This is done by aligning the truth box to the anchor boxes using a common origin for the IOU calculation. I don't see any issue here.

**Comment by weiaicunzai** [comment]
@glenn-jocher , Thanks for the replay, but, what about the anchors near the image edge, do we need to clamp the anchors so the anchors could lie in the image? For example, at the top left cell, the anchor 's top left corner could be outside of the input image, do we need to clamp the anchor? Thank you.

**Comment by weiaicunzai** [comment]
@glenn-jocher  I get it now, for some one who has the same question as I did, the author shift the anchors and gt bbox to be top left corner at (0, 0), and bottom right corner at (w, h), then compute the iou, clever. Thanks for the replay, again.

**Comment by lshiwjx** [comment]
@weiaicunzai Could you please explain it more? Why set the centre of gt bbox to (0,0) rather than its original coordinate. 
Besides, the grid point that is responsible for the current gt bbox is calculated by int(x). Why not use int(x+0.5) that is more reasonable. Thanks. Look forward to your reply.
