### ISSUE TITLE
Train VOC2007, stuck

### ISSUE THREAD

**Issue by eekarot** [eriklindernoren/PyTorch-YOLOv3#572]
I convert the data set of VOC to coco format, and every time in the test part of the fourth epoch, the program will be stuck

**Comment by Flova** [comment]
Could you provide additional logs? The program doesn't exit, right? What is the traceback if you kill it with `ctrl+c`

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
