### ISSUE TITLE
Convert .pth to .weights

### ISSUE THREAD

**Issue by ftft1034** [eriklindernoren/PyTorch-YOLOv3#574]
Hello,

Was anyone able yet to convert the .pth model to a .weights model?

BR,
FT

**Comment by AkhileshV** [comment]
create a new python file, import all the requirements and write the following lines in them

model = Darknet("your .cfg file")

model.load_state_dict(torch.load("your_ckpt.pth", map_location=torch.device('cpu'))) # for loading model on cpu

model.save_weights(savedfile='your_ckpt.weights', cutoff=0)
print("successfully converted .pth to .weights")

This worked for me. 
Hope it helps you

**Comment by WANGCHAO1996** [comment]
> create a new python file, import all the requirements and write the following lines in them
> 
> model = Darknet("your .cfg file")
> 
> model.load_state_dict(torch.load("your_ckpt.pth", map_location=torch.device('cpu'))) # for loading model on cpu
> 
> model.save_weights(savedfile='your_ckpt.weights', cutoff=0)
> print("successfully converted .pth to .weights")
> 
> This worked for me.
> Hope it helps you

Hello, how to convert Pt model (https://github.com/ultralytics/yolov3)to weights

**Comment by AkhileshV** [comment]
The procedure is the same as .pth model. Once you load .pt model in torch, you save it in weights format using save_weights method of Darknet class

**Comment by borninfreedom** [comment]
> `model = Darknet("your .cfg file")`，how to import the `Darknet`？

**Comment by Flova** [comment]
```python
from pytorchyolo.models import Darknet
```

**Comment by qianz11** [comment]
from pytorchyolo.models import Darknet
ModuleNotFoundError: No module named 'pytorchyolo'

How can I solve it?

**Comment by Flova** [comment]
You need to install it by running the steps in the readme. In case of poetry you also need to activate the venv via `poetry shell`.
