### ISSUE TITLE
can not run the train.py

### ISSUE THREAD

**Issue by lucafei** [eriklindernoren/PyTorch-YOLOv3#577]
hello, i'm recently training a yolov3 model using my own dataset, but i find when i try to run the train.py through command "python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data", the train.py file didn't be executed. And it doesn't have any error happening. Do you know where is the problem.
![error at running yolo](https://user-images.githubusercontent.com/29920326/95650627-0bff4780-0ae5-11eb-853c-7803ad8615f2.PNG)
Thank you very much in advance

**Comment by Flova** [comment]
This seems weird. Does `python3` work for other scripts?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
