### ISSUE TITLE
The download link of pre-trained networks is no longer available

### ISSUE THREAD

**Issue by Linsen-cc** [eriklindernoren/PyTorch-YOLOv3#580]
The download link of pre-trained networks is no longer available, could you fix it , thank you so much.

**Comment by Flova** [comment]
What fails specifically? Could you post some steps to reproduce?

**Comment by Linsen-cc** [comment]
It can work normally now, it may be my network problem at that time， thanks ~~~~~~~~~~~~~~~~~~ 😁

**Comment by Flova** [comment]
Okay no problem
