### ISSUE TITLE
Definition about mAP

### ISSUE THREAD

**Issue by Qian2333** [eriklindernoren/PyTorch-YOLOv3#581]
the test.py will output a AP named mAP.
but I think it means AP50.
AsI learned that mAP is a AP whose IoU is range from 0.5 to 0.95
so is you AP the AP50 or AP(0.5-0.95)?

**Comment by Flova** [comment]
As the v3 paper we use the AP50 metric but it is also called mAP or 0.5 mAP in the Paper.
