### ISSUE TITLE
[Error]: No such file or directory: 'data/coco/train2017/..\\image\\158.jpg'

### ISSUE THREAD

**Issue by WWaynee** [eriklindernoren/PyTorch-YOLOv3#582]
Is there anyone who met the same error? I need help and I often have this question while training other detection project, I think it was caused by os.path.join(), but I don't know how to do with it...I would be grateful if anyone could help me...Thanks a lot.

**Comment by nnzy11** [comment]
您好，我也遇到了相同的问题，请问您解决了吗

**Comment by yangle15** [comment]
You must rewrite the dataset and dataloader by yourself if you want to use MSCOCO2017. This repo is for COCO2014 and VOC.

**Comment by WWaynee** [comment]
> 您好，我也遇到了相同的问题，请问您解决了吗

解决了，是labelme的问题，这个url后面的"...\\img\\xxx.jpg"是在json文件里面的，你可以修改json文件里面的"imagePath"，修改之前是"imagePath": "..\\img\\158.jpg"，需要修改成"158.jpg"，我用的是labelme的4.5.6版本也是出现了这个问题，自带了相对路径，但是很多项目训练不需要前面的路径，目前不知道什么版本的labelme可以解决这个问题，手动改太麻烦了。
![image](https://user-images.githubusercontent.com/59861939/100236366-89cdc400-2f68-11eb-8cb4-7465989224f7.png)

**Comment by Flova** [comment]
Are there any open questions?

**Comment by Flova** [comment]
Issues with missing files should also be fixed with the new dataloader in #600

**Comment by Flova** [comment]
I close this for now. Feel free to reopen for further discussion
