### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by CASTTim** [eriklindernoren/PyTorch-YOLOv3#586]
My GPU memory is 4G, and my tensorflow is 2.1.0 for gpu, when I run:
```shell
python train.py --data_config config/coco.data  --pretrained_weights weights/darknet53.conv.74 --batch_size 1
```
this error happended, and my command window is dead.
I also changed the batch_size to 1 in yolov3.cfg, but did not work.
I tried this solution: https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/510#issuecomment-690076029
When I commented Tensorboard logging codes, this error didn't happend:
```python
#tensorboard_log = []
#for j, yolo in enumerate(model.yolo_layers):
#    for name, metric in yolo.metrics.items():
#        if name != "grid_size":
#            tensorboard_log += [(f"{name}_{j+1}", metric)]
#tensorboard_log += [("loss", loss.item())]
#logger.list_of_scalars_summary(tensorboard_log, batches_done) 
```
Then I created a new annaconda environment with tensorflow 1.13, batch_size set to 2, this error didn't happen.
My new environment used tensorflow 1.13.0 for cpu, and my environment is:
python==3.7
tensorflow==1.13.1
tensorboard==1.13.1
numpy
pytorch==1.7.0
torchvision==0.8.1
matplotlib
terminaltables
pillow==6.2.1
tqdm

I hope this can help someone.

**Comment by crownz-sec** [comment]
I have the same problem, and I tried the method.But it still happened...

**Comment by CASTTim** [comment]
> I have the same problem, and I tried the method.But it still happened...

Try this:
+ set `--batch_size` default value to `1` and set `--n_cpu` default value to `0` in  `train.py`
+ set `batch=1` in  `yolov3.cfg`

**Comment by crownz-sec** [comment]
> > I have the same problem, and I tried the method.But it still happened...
> 
> Try this:
> 
> * set `--batch_size` default value to `1` and set `--n_cpu` default value to `0` in  `train.py`
> * set `batch=1` in  `yolov3.cfg`

okay,thanks

**Comment by Flova** [comment]
The tensorflow dependency is removed now. 
Also reducing the batch size should help.
If there are any open points left feel free to reopen the issue.
