### ISSUE TITLE
Bounding boxes are very small during inference

### ISSUE THREAD

**Issue by padmasreenagarajan** [eriklindernoren/PyTorch-YOLOv3#591]
I am using TIDL by Texas Instruments for inferencing YOLOv3 model.
The detection part is working but the **bounding boxes drawn on the image are very small.**
I have used default anchors only with input size of 608x608 and 416x416.

Please provide me with the solution. @eriklindernoren

**Comment by Flova** [comment]
They are in the right position, but too small? And are they in the correct shape if you use the provided `detection.py`?

**Comment by Flova** [comment]
I closed this issue due to inactivity it also seems like an inference problem. Feel free to reopen for further discussion.
