### ISSUE TITLE
Speed difference between pre-trained weights and checkpoints.

### ISSUE THREAD

**Issue by junukwon7** [eriklindernoren/PyTorch-YOLOv3#593]
When testing pre-trained weights: took about 4 mins.
![image](https://user-images.githubusercontent.com/48399106/103343424-5fbf7280-4acf-11eb-814a-f0a60e310fcf.png)
But when I tested checkpoints, ETA is more than an hour.
![image](https://user-images.githubusercontent.com/48399106/103343477-7ebe0480-4acf-11eb-92d1-2774950319a2.png)

I also tried saving the checkpoints in .weight format using `save_darknet_weights`, but didn't reduce the time.
Any suggestions? Please help me...

**Comment by Flova** [comment]
This is weird. I could not reproduce it. Could you provide additional info?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
