### ISSUE TITLE
the route layer filters num

### ISSUE THREAD

**Issue by guanfuchen** [eriklindernoren/PyTorch-YOLOv3#6]
I wonder why the route layer filter num [https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/models.py#L45](url) is different from the [https://github.com/ayooshkathuria/YOLO_v3_tutorial_from_scratch/blob/master/darknet.py#L122](url). Here the route filter index is from 0 at output_filters, but the implement from the another link is from the current filter index at output_filters. Thanks for your reply.

**Comment by eriklindernoren** [comment]
In the other implementation he converts all indices in the config file to negative integers and then computes the position as the `current_index + negative_idx`. The way I do it is I directly access the element at the position specified in the config file. So `-1` is accessed as the last element in the output_filters list, meaning the number of output filters in the last layer that was added. The index `10` is directly accessed at `output_filters[10]`.
