### ISSUE TITLE
Recall50, Recall75, Precision ALWAYS equal to 0 

### ISSUE THREAD

**Issue by qxtaiba** [eriklindernoren/PyTorch-YOLOv3#605]
Is there any reason why the values mentioned above are always zero during training? Is this a mistake or expected? 

---- [Epoch 0/100, Batch 659/29316] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 14           | 28           | 56           |
| loss       | 5.133108     | 5.039142     | 5.855659     |
| x          | 0.105147     | 0.100520     | 0.096455     |
| y          | 0.074078     | 0.056703     | 0.072684     |
| w          | 0.609751     | 0.438645     | 0.487483     |
| h          | 0.598389     | 0.284308     | 0.408482     |
| conf       | 3.681444     | 4.102895     | 4.736791     |
| cls        | 0.064299     | 0.056071     | 0.053764     |
| cls_acc    | 35.29%       | 33.33%       | 36.17%       |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.117185     | 0.080454     | 0.036350     |
| conf_noobj | 0.012405     | 0.012388     | 0.009368     |
+------------+--------------+--------------+--------------+
Total loss 16.027908325195312
---- ETA 2:12:48.243439

**Comment by mei123hao** [comment]
I have same problem, do you solved it?

**Comment by Flova** [comment]
The original issue was in epoch 0, so the network hasn't learned anything useful yet. This resulted in no predictions and therefore low recall and precision metics.
This is expected behavior.
