### ISSUE TITLE
Train.py metaclass conflict with nonechucks via import evaluate ex test.py

### ISSUE THREAD

**Issue by JoernHen** [eriklindernoren/PyTorch-YOLOv3#607]
I became a metaclass conflict at running train.py from nonechucks that imported via test.evaluate (see below) 
![IMG-20210114-WA0011~2](https://user-images.githubusercontent.com/35383421/104640641-08adc600-56a9-11eb-92a5-dc7a57ac0a78.jpeg)

At my local machine it runs with Pytorch 1.7.1.
At server it runs with a testset with 3 images. With real set i get this error

**Comment by Flova** [comment]
The issue seems to be related to the `with_metaclass` method. The `nonechucks` dependency will be dropped before the branch is merged. You can therefore remove it yourself for now (or wait until my replacement is pushed). There should be no difference if you use it with only 3 images.
