### ISSUE TITLE
Can we have this model via torch.hub?

### ISSUE THREAD

**Issue by ydcjeff** [eriklindernoren/PyTorch-YOLOv3#610]
Can you add `hubconf.py` so that we can load the models via `torch.hub`?
More info: https://pytorch.org/docs/stable/hub.html
Example script: https://github.com/pytorch/vision/blob/master/hubconf.py

Thank you!

**Comment by jaagut** [comment]
I think, this is not necessary, as this repo does not contain any pretrained models. It just offers the possibility to use pretreined darknet yolo models.
