### ISSUE TITLE
Validation recall is greater than 1

### ISSUE THREAD

**Issue by bencsikb** [eriklindernoren/PyTorch-YOLOv3#612]
Hi everyone!

I trained a network with KITTI dataset from pretrained darknet weights, and it works fine, the maximum value of validation recall is 1.0.

However, if I train the network with my custom dataset, which has 2 categories and the annontation files are in the exact same format as the KITTI annotations, I get a higher value for validation recall than 1. 
I printed all the relevant parameters in the _ap_per_class_ function, to make it understandable. So, the problem is, that considering category 1.0, there are more true positive bounding boxes (cumsum tpc) than ground truth bounding boxes.  The number of ground truth bboxes are correct for each category, so something is wrong with the true positive calculations.
![image](https://user-images.githubusercontent.com/72827411/104937179-c092ea00-59ad-11eb-987f-de2d366b06ec.png)

I really don't understand what's the problem here. I should also mention that in the _get_batch_statistics_ function, where the categories are not examined separately, the _number of true positives_ <= _ground truth bboxes_ is always true for every batch.
What's more, this issue only appears if the custom validation dataset contains more than ~50 images.

Does anyone have any idea where should I start to search for the problem?

Thanks in advance!

**Comment by Aidol** [comment]
I had also meet this problem in validation, the AP was 1.4

**Comment by Flova** [comment]
Is this issue still relevant/occurring?
