### ISSUE TITLE
coordinates of the bounding box

### ISSUE THREAD

**Issue by Howie86** [eriklindernoren/PyTorch-YOLOv3#617]
Hello. I'm puzzled as to why the coordinates of the bounding box, **x2**, **y2** need to plus **pad[1]**, **pad[3]** in Class **ListDataset**, **datasets.py**. Why **x2**, **y2** plus **pad[1]**, **pad[3]**, rather than **pad[0]**, **pad[2]**? I‘m quite confused, can you show me the answer.
Thanks very much.

![11](https://user-images.githubusercontent.com/45527358/106240206-d4a4da00-623e-11eb-965e-d1d7a164fdcb.JPG)

**Comment by Flova** [comment]
I am closing this because this is from am old version of this repo. The padding was moved to the imgaug lib a few weeks ago.
