### ISSUE TITLE
train.py issue

### ISSUE THREAD

**Issue by mama110** [eriklindernoren/PyTorch-YOLOv3#62]
Different images from the dataloader, but there is one result in imgs tensor, just as follows:

code:
for epoch in range(opt.epochs):
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
        imgs = Variable(imgs.type(Tensor))

result about imgs:
tensor([[[[ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020],
          [ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020],
          [ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020],
          ...,
          [ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020],
          [ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020],
          [ 0.5020,  0.5020,  0.5020,  ...,  0.5020,  0.5020,  0.5020]],

Is this right?

**Comment by bobo0810** [comment]
Hello, I have encountered this situation. Can you solve it?
It is caused by this line
` input_img = np.pad(img, pad, 'constant', constant_values=128) / 255.`

**Comment by eriklindernoren** [comment]
Hi, let's keep training issues in #2.

**Comment by WannaSeaU** [comment]
> Hello, I have encountered this situation. Can you solve it?
> It is caused by this line
> ` input_img = np.pad(img, pad, 'constant', constant_values=128) / 255.`
Have you solved it?
