### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by 948024326** [eriklindernoren/PyTorch-YOLOv3#620]
![QQ截图20210131180556](https://user-images.githubusercontent.com/59902823/106380871-0f01a900-63f0-11eb-8b68-84291692b4f5.png)

Detecting objects: 100%|██████████| 250/250 [00:31<00:00,  7.95it/s]
Traceback (most recent call last):
  File "D:/YOLO-V3-PyTorch/PyTorch-YOLOv3/train.py", line 170, in <module>
    batch_size=2,
  File "D:\YOLO-V3-PyTorch\PyTorch-YOLOv3\test.py", line 55, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

I am training coco datasets in train.py
But when it up to 1 epoch,it detect the val_map and some values,but it happends an error
could anybody help me?

**Comment by 948024326** [comment]
@yrrah @wptoux @id9502

**Comment by yrrah** [comment]
Looks like the prediction is returning an empty result. Hard to say why without looking over your shoulder to debug.

**Comment by 948024326** [comment]
> Looks like the prediction is returning an empty result. Hard to say why without looking over your shoulder to debug.

![image](https://user-images.githubusercontent.com/59902823/106382278-7708bd00-63f9-11eb-8e1b-3bb58147e8da.png)

all it's 0.

last few days i run it, and its' results is like  4.23125215e-10 but not onyl get 0.
I am confused...

**Comment by jaagut** [comment]
Hi @948024326,
you are running an older version. The ValueError should already be fixed on the master branch.

**Comment by 948024326** [comment]
> Hi @948024326,
> you are running an older version. The ValueError should already be fixed on the master branch.

oh thank u

and now i download new version,i want to train my coco datasets,how showld  I change the code?
I mean the path of images and labels.thank u 
![image](https://user-images.githubusercontent.com/59902823/106384830-e7b6d600-6407-11eb-8673-f257cb30e81b.png)

**Comment by 948024326** [comment]
ok  i got it..
but coco2014 seems not very good,in the val,it has some pictures and labels that can't match and raise an warning

**Comment by Flova** [comment]
The coco dataset has indeed some missing images in the validation dataset. This results in some warnings. But this is more of an coco issue :/

**Comment by 948024326** [comment]
> The coco dataset has indeed some missing images in the validation dataset. This results in some warnings. But this is more of an coco issue :/

yes.I got it.. 
Thank u.
And in the first epoch,it's results about map and some values all is 0.Is this normal or not?
thanks
![QQ图片20210201001316](https://user-images.githubusercontent.com/59902823/106390225-5012b100-6422-11eb-8499-95757463b62f.png)

**Comment by 948024326** [comment]
and i use it in the colab.
But it occuerd an error.
I have the same datasets in pc,but it won't arouse error.

![1](https://user-images.githubusercontent.com/59902823/106390323-ca433580-6422-11eb-96e1-36068631aaf0.png)

I think the reason it's like what my topics mentionend?    It seems that the metrics_output is none.
![2](https://user-images.githubusercontent.com/59902823/106390358-0ffffe00-6423-11eb-8c94-e5e36590b98c.png)

**Comment by Flova** [comment]
The full size model isnt that small. So training it on something like coco takes a few days minimum. I tried to improve the convrgence speed a bit recently and I am open for Ideas. Never the less it would still take a few epochs untl the mAP starts to increse. The no detections message issues from the model not detecting anythin in the validation set yet.

**Comment by 948024326** [comment]
> The full size model isnt that small. So training it on something like coco takes a few days minimum. I tried to improve the convrgence speed a bit recently and I am open for Ideas. Never the less it would still take a few epochs untl the mAP starts to increse. The no detections message issues from the model not detecting anythin in the validation set yet. This is expected behavior. If you are training on a custom dataset, try transfer learing with the official weights. This should avoid these issues and boost your training speed.

Thanks a lot!

**Comment by Flova** [comment]
No problem. 

I close this issue now. If you have any further questions feel free to reopen.
