### ISSUE TITLE
A question about changing the Residual 

### ISSUE THREAD

**Issue by 948024326** [eriklindernoren/PyTorch-YOLOv3#622]
Hi,I am changing the Residual but i  have a problem.
I want to change the Residual like this.
![image](https://user-images.githubusercontent.com/59902823/106585296-207aba80-6582-11eb-8bf6-c461b29053fe.png)

And the yolov3.cfg I changed it's like this.
![image](https://user-images.githubusercontent.com/59902823/106585431-4c963b80-6582-11eb-8de7-9edde63c1a62.png)

But when I use netron to see the structure it appered not what i want.
![image](https://user-images.githubusercontent.com/59902823/106585574-70598180-6582-11eb-8f2f-9dec8a2ca755.png)

Could anybody give me some suggestions?T
Thanks a lot!

**Comment by 948024326** [comment]
![image](https://user-images.githubusercontent.com/59902823/106585790-ae56a580-6582-11eb-8a2a-4bbfca422011.png)
Maybe i should changet the code here?

**Comment by Flova** [comment]
I think the darknet cfg currently only supports symmetric kernels

**Comment by Flova** [comment]
You could indeed add it to the parser at the highlighted code part.

**Comment by 948024326** [comment]
Ok,thank u. I tried ,but i failed- - . Could you help me?
The code i changed always get errors...

**Comment by Flova** [comment]
I would but I am sadly very busy at the moment and this isn't a part of the core implementation. : /

**Comment by 948024326** [comment]
> I would but I am sadly very busy at the moment and this isn't a part of the core implementation. : /

ok.Thanks a lot !
