### ISSUE TITLE
load self-trained darknet weight cannot detect object

### ISSUE THREAD

**Issue by TIMETOTIAO** [eriklindernoren/PyTorch-YOLOv3#627]
I used the original darknet yolov3 to train and get the weight. Then I used the detect.py to detect with loading darknet weights, but when I printed out the detection, it prints "None". But this weight works fine using darknet.

**Comment by Flova** [comment]
Does the printout work with the default darkent weights on the sample images provided in this repo?

**Comment by TIMETOTIAO** [comment]
> Does the printout work with the default darkent weights on the sample images provided in this repo?

Yes.

**Comment by Flova** [comment]
Are the thresholds, cfg definitions, number of classes, and so on set?

**Comment by Flova** [comment]
Did you set the weights using `--weights_path` and does the file name ends with `.weights`?

**Comment by TIMETOTIAO** [comment]
> Did you set the weights using `--weights_path` and does the file name ends with `.weights`?

I just copied the ".cfg" and name file from darknet folder to pytorch-yolov3 directly in order to avoid mistake. And the file name ends with .weights.

**Comment by Flova** [comment]
What's the whole name of the cfg?

**Comment by TIMETOTIAO** [comment]
> What's the whole name of the cfg?

yolov3-door-ball.cfg

**Comment by Flova** [comment]
Is it just the number of classes that is different in this cfg?

**Comment by TIMETOTIAO** [comment]
Yes. And some hyperparameter like batch and subvision.
________________________________
发件人: Florian Vahl <notifications@github.com>
发送时间: 2021年2月10日 19:34
收件人: eriklindernoren/PyTorch-YOLOv3 <PyTorch-YOLOv3@noreply.github.com>
抄送: LAI, Wei <1155095200@link.cuhk.edu.hk>; Author <author@noreply.github.com>
主题: Re: [eriklindernoren/PyTorch-YOLOv3] load self-trained darknet weight cannot detect object (#627)


Is it just the number of classes that is different in this cfg?

―

**Comment by TIMETOTIAO** [comment]
> Is it just the number of classes that is different in this cfg?

Yes. And some hyperparameter like batch and subvision.

**Comment by Flova** [comment]
Is this issue still relevant/occurring?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
