### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Zzheng-6** [eriklindernoren/PyTorch-YOLOv3#641]
D:\anaconda\python.exe D:/YOLOV3/train.py
Traceback (most recent call last):
  File "D:/YOLOV3/train.py", line 4, in <module>
    import torch.distributed as dist
  File "D:\anaconda\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\anaconda\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
How to solve this problem?

**Comment by Flova** [comment]
Honestly, I don't know. This seems to be more of a PyTorch issue than an issue regarding this repo.

The import `import torch.distributed as dist` is also not a part of this project afaik. This would be outside of the scope of this repo. Sorry :/

**Comment by Zzheng-6** [comment]
It's OK. Thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 凌晨5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] I have a problem (#641)





 
Honestly, I don't know. This seems to be more of a PyTorch issue than an issue regarding this repo.
 
The import import torch.distributed as dist is also not a part of this project afaik. This would be outside of the scope of this repo. Sorry :/
