### ISSUE TITLE
train.py reports: "could not read label",    but label looks correct

### ISSUE THREAD

**Issue by mimslim** [eriklindernoren/PyTorch-YOLOv3#644]
"Training Epoch 0:   0% 0/63 [00:00<?, ?it/s]Could not read label 'data/custom/labels/train_image_00067.txt'.
Could not read label 'data/custom/labels/train_image_00397.txt'.
Could not read label 'data/custom/labels/train_image_00410.txt'....."

But, I can see and view file fine:
!ls -al data/custom/labels/train_image_00067.txt
!more data/custom/labels/train_image_00067.txt
-rw------- 1 root root 84 Mar 15 21:53 data/custom/labels/train_image_00067.txt
0, 0.16709183673469388, 0.5905096660808435, 0.14158163265306123, 0.4472759226713
5324

Is there a reason why a label might not be readable, besides not being present?   My classes.names file contains one entry "Box", and all my data is of one class (the index "0").

**Comment by Flova** [comment]
It looks like you separated the entries using a `,` character. They are normally only separated by a space. This may lead to an exception while parsing the label, which results in the label been skipped.

Example label from the coco dataset:
```
23 0.770336 0.489695 0.335891 0.697559
23 0.185977 0.901608 0.206297 0.129554
```

**Comment by Flova** [comment]
The `classes.names` is needed later on in the pipeline and your description looks okay.

**Comment by mimslim** [comment]
Thanks again.  

-steve

**Comment by Flova** [comment]
No problem. I close this issue now okay?

**Comment by mimslim** [comment]
yes

**Comment by NJUEELJN** [comment]
> It looks like you separated the entries using a `,` character. They are normally only separated by a space. This may lead to an exception while parsing the label, which results in the label been skipped.
> 
> Example label from the coco dataset:
> 
> ```
> 23 0.770336 0.489695 0.335891 0.697559
> 23 0.185977 0.901608 0.206297 0.129554
> ```
> 
> Your Example in the correct format:
> 
> ```
> 0 0.16709183673469388 0.5905096660808435 0.14158163265306123 0.4472759226713
> ```

hi Flova, may I ask the meaning of four bbox elements, i.e. 0.16709183673469388 0.5905096660808435 0.14158163265306123 0.4472759226713, do they mean relavent position x1, y1, x2, y2?
> ```

**Comment by jaagut** [comment]
Hi, as this implementation is compatible with the original darknet YOLO, it uses the same data format as it is described [here](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects) (scroll a little bit down to step 5, there you will find the answer to your question).
