### ISSUE TITLE
train.py keep getting killed...

### ISSUE THREAD

**Issue by tagynedlrb** [eriklindernoren/PyTorch-YOLOv3#651]
I ran my code "python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data",
but the process is keep getting killed.
Mac OS, python 3.7 is my current spac(no GPU, only by CPU)
According to following article(https://stackoverflow.com/questions/64772335/pytorch-w-parallelnative-cpp206),
I've handled my multiprocessing error issue, and edited my [n_cpu = 0].
Also, I even resized my data 1/100, which is only 8KB each, and put only 3 of 'em.
I don't get what's wrong with it...

---- mAP 0.0
Training Epoch 4: 100%|███████████████████████████| 1/1 [00:09<00:00,  9.19s/it]

---- Evaluating Model ----
Detecting objects:   0%|                                  | 0/1 [00:00<?, ?it/s]
zsh: killed     python3 train.py --model_def config/yolov3-custom.cfg --data_config

**Comment by Flova** [comment]
That is indeed starange. But it kind of seems like a pytorch issue imo.

**Comment by tagynedlrb** [comment]
I guess it's just my mistake...
First no plenty dataset and second my mistake on writing train & valid.txt data.
I could say it's my fault I wrote all path of my data to each txts but I felt very confused on the sample train data,
as if it has written the same path both in train.txt and valid.txt...
More clear example of custom data would be helpful I guess. Thanks a lot Flova!
