### ISSUE TITLE
A problem when run train.py using my own dataset

### ISSUE THREAD

**Issue by chen-yuxi** [eriklindernoren/PyTorch-YOLOv3#653]
When I run train.py , 
python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data
there is an error that 
Could not read image '~/PyTorch-YOLOv3/data/custom/images/train2014/ss-214_0x0.jpg'.
Could not read image '~/PyTorch-YOLOv3/data/custom/images/train2014/ss-034_0x0.jpg'.
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")):
  File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/cyx/PyTorch-YOLOv3/utils/datasets.py", line 130, in collate_fn
    paths, imgs, bb_targets = list(zip(*batch))
ValueError: not enough values to unpack (expected 3, got 0)
Anyone can help me?

**Comment by Flova** [comment]
Please check the paths in youre `.txt` file. The leading `/` indicates an absolute path and I don't think your repository is located in your root directory.

**Comment by chen-yuxi** [comment]
Thank you. It works.

**Comment by Zzheng-6** [comment]
Do you have the wrong file path? I had the same problem

**Comment by chen-yuxi** [comment]
In the train.txt and valid.txt , we must use absolute path, not relative path.

**Comment by Zzheng-6** [comment]
Just like this?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] A problem when run train.py using my own dataset (#653)





 
In the train.txt and valid.txt , we must use absolute path, not relative path.

**Comment by chen-yuxi** [comment]
没看懂你在说什么，我这出现的是邮件的乱码

**Comment by Zzheng-6** [comment]
就像这样嘛？



data/custom/images/beizi17.jpg

data/custom/images/beizi18.jpg

data/custom/images/beizi21.jpg

data/custom/images/beizi27.jpg

data/custom/images/beizi28.jpg



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 上午10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] A problem when run train.py using my own dataset (#653)





 
没看懂你在说什么，我这出现的是邮件的乱码

**Comment by Zzheng-6** [comment]
已经可以训练了，多谢啦&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] A problem when run train.py using my own dataset (#653)





 
In the train.txt and valid.txt , we must use absolute path, not relative path.

**Comment by gongyue771234** [comment]
> When I run train.py , python3 train.py --model_def config/yolov3-custom.cfg --data_config config/custom.data there is an error that Could not read image '~/PyTorch-YOLOv3/data/custom/images/train2014/ss-214_0x0.jpg'. Could not read image '~/PyTorch-YOLOv3/data/custom/images/train2014/ss-034_0x0.jpg'. Traceback (most recent call last): File "train.py", line 107, in for batch_i, (_, imgs, targets) in enumerate(tqdm.tqdm(dataloader, desc=f"Training Epoch {epoch}")): File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/tqdm/std.py", line 1178, in **iter** for obj in iterable: File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in **next** data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/cyx/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch return self.collate_fn(data) File "/home/cyx/PyTorch-YOLOv3/utils/datasets.py", line 130, in collate_fn paths, imgs, bb_targets = list(zip(*batch)) ValueError: not enough values to unpack (expected 3, got 0) Anyone can help me?

hello，I have the same problem,but I had used absolute path
![Snipaste_2023-04-13_15-42-08](https://user-images.githubusercontent.com/109892843/231689293-1304c352-b744-4d50-958f-46d3ecff7f81.jpg)
![Snipaste_2023-04-13_15-42-08](https://user-images.githubusercontent.com/109892843/231689323-4c5586d8-cabe-4f3d-bab4-a37b178032d8.jpg)
