### ISSUE TITLE
determine the parameter of img_size

### ISSUE THREAD

**Issue by JerMouse** [eriklindernoren/PyTorch-YOLOv3#654]
my image size is 640 * 480, i want train my dataset，but i don't know how to determine the parameter of "img_size"

**Comment by Flova** [comment]
Yolo uses square padding. So it runs on an image with `image_size` x `image_size` resolution. It adds black bars if your image doesn't fit that aspekt ratio. Note also that a larger image size lowers the inference and training speed. So set it to 640 if you the want that maximum resolution at a lower speed.
