### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by oliver0922** [eriklindernoren/PyTorch-YOLOv3#656]
![1](https://user-images.githubusercontent.com/69920975/113518306-82769100-95c0-11eb-831d-11b0c9f7977a.PNG)
I am using Colab. When I try to training the dataset. The error like this occurred. How can I solve this problem? 
Thanks

**Comment by Flova** [comment]
Thanks for your issue!
What dataset did you use? Could you provide the trace when using the CPU and not CUDA? Set `CUDA_VISIBLE_DEVICES="" train.py ....` to disable CUDA while training.
