### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 6) occur when I run detect.py

### ISSUE THREAD

**Issue by s1mpleee** [eriklindernoren/PyTorch-YOLOv3#657]
Saving images:
(0) Image: 'data/samples\dog.jpg'
Traceback (most recent call last):
  File "detect.py", line 117, in <module>
    for x1, y1, x2, y2, conf, cls_conf, cls_pred in detections:
ValueError: not enough values to unpack (expected 7, got 6)

it seems that if I run this on images with object, this error would happen; however, if I run this on a no-object-picture,this error wouldn't happen. Now I'm confused...

**Comment by shangrilar** [comment]
I got exactly same error.

**Comment by jonghee-ban** [comment]
I got the same error. But now I solve this problem by edit detect.py.
The modified code is below:

for x1, y1, x2, y2, conf, cls_pred in detections:
    print("\t + Label: %s, Conf: %.5f" % (classes[int(cls_pred)], conf.item()))
    
I solved the problem by modifying the above two lines of code.

**Comment by s1mpleee** [comment]
> I got the same error. But now I solve this problem by edit detect.py.
> The modified code is below:
> 
> for x1, y1, x2, y2, conf, cls_pred in detections:
> print("\t + Label: %s, Conf: %.5f" % (classes[int(cls_pred)], conf.item()))
> 
> I solved the problem by modifying the above two lines(line 117, 118) of code.

problem solved perfectly. thanks!!!
