### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 6)

### ISSUE THREAD

**Issue by zhoutao-art** [eriklindernoren/PyTorch-YOLOv3#658]
Traceback (most recent call last):
  File "D:/Users/98045/PycharmProjects/PyTorch-YOLOv3-master/detect.py", line 117, in <module>
    for x1, y1, x2, y2, conf, cls_conf, cls_pred in detections:
ValueError: not enough values to unpack (expected 7, got 6)

Why I run the code to get this kind of error?

**Comment by Flova** [comment]
I just fixed this issue. This was caused due by a refactoring of the non-maximum suppression. Sorry :(
