### ISSUE TITLE
Error while running train.py

### ISSUE THREAD

**Issue by nithinvenny07** [eriklindernoren/PyTorch-YOLOv3#662]
when i run the following command to train the network using imagenet weights iam getting the error
python3 train.py --model config/yolov3-custom.cfg --data config/custom.data --pretrained_weights weights/darknet53.conv.74

ERROR:
File "train.py", line 94, in <module>
    model = load_model(args.model, args.pretrained_weights)
  File "/content/gdrive/My Drive/Project/PyTorch-YOLOv3/models.py", line 284, in load_model
    model.load_state_dict(torch.load(weights_path))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by Flova** [comment]
I am able to reproduce this error

**Comment by Flova** [comment]
Thank you for your issue

**Comment by Flova** [comment]
The issue is fixed. Please pull again.

**Comment by nithinvenny07** [comment]
Thank You so much!! it is working now
