### ISSUE TITLE
Cuda runtime error when training only one class

### ISSUE THREAD

**Issue by alessiocaporali** [eriklindernoren/PyTorch-YOLOv3#664]
> Traceback (most recent call last):
  File "train.py", line 157, in <module>
    loss, loss_components = compute_loss(outputs, targets, model)
  File "/home/lar/DeepLearning/Object_Detection/PyTorch-YOLOv3/utils/loss.py", line 165, in compute_loss
    iou = bbox_iou(pbox.T, tbox[layer_index], x1y1x2y2=False, CIoU=True)  # iou(prediction, target)
  File "/home/lar/DeepLearning/Object_Detection/PyTorch-YOLOv3/utils/loss.py", line 19, in bbox_iou
    b1_x1, b1_x2 = box1[0] - box1[2] / 2, box1[0] + box1[2] / 2
RuntimeError: CUDA error: device-side assert triggered

A Cuda runtime error happens  to me when I tried to train with only one class. I am using a custom dataset. If I change the dataset classes names to include a placeholder for a second "fake" class, and configure yolo with 2 classes, then the same dataset trains without problems. 
Hope my feedback is helpful!

**Comment by Flova** [comment]
Thank you for your issue. I have a look at it later on. Could your run the training without cuda to produce a more detailed trace? You can do this by setting `CUDA_VISIBLE_DEVICES`="" python3 train.py ...`.

**Comment by alessiocaporali** [comment]
>   File "train.py", line 157, in <module>
    loss, loss_components = compute_loss(outputs, targets, model)
  File "/home/lar/DeepLearning/Object_Detection/PyTorch-YOLOv3/utils/loss.py", line 175, in compute_loss
    t[range(num_targets), tcls[layer_index]] = cp
IndexError: index 1 is out of bounds for dimension 1 with size 1

Thank you for your time!

**Comment by Flova** [comment]
Could you test it again? It should be fixed.

**Comment by alessiocaporali** [comment]
yes, i can confirm!

**Comment by Flova** [comment]
Thanks for testing it.
