### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by janismdhanbad** [eriklindernoren/PyTorch-YOLOv3#665]
Hello authors, thank you for the amazing repo. I was trying to train on a custom dataset. I used the format given in the README for training on my data but got the following error in the Evaluating Model stage.

---- Evaluating Model ----
Validating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 230/230 [00:21<00:00, 10.63it/s]
Computing AP: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 16487.04it/s]
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    verbose=args.verbose
  File "/home/datumx/data_science_experiments/traffic_sign_recogntiton/new_proj/eecs442project/PyTorch-YOLOv3/test.py", line 131, in _evaluate
    print_eval_stats(metrics_output, class_names, verbose)
  File "/home/datumx/data_science_experiments/traffic_sign_recogntiton/new_proj/eecs442project/PyTorch-YOLOv3/test.py", line 75, in print_eval_stats
    ap_table += [[c, class_names[c], "%.5f" % AP[i]]]
IndexError: list index out of range

Is this error related to the following line? https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/82e8ea57f2dfe822284733c26b2ba9166a86b296/utils/utils.py#L24

Thanks

**Comment by Flova** [comment]
Yea it seems to be an issue with your class labels. They are defined in a `.names` file in your `.data` file under e.g. `names=data/coco.names`. The file contains all the names for your classes and it seems they do not match the number of predicted classes by your network.

I hope I was able to help you with my answer and good luck with your course. Feel free to ask, if you have any further questions.
