### ISSUE TITLE
device-side assert triggered

### ISSUE THREAD

**Issue by shangrilar** [eriklindernoren/PyTorch-YOLOv3#666]
Hi, I'm trying to train custom dataset.

I got underneath error.

![image](https://user-images.githubusercontent.com/44944445/114714012-a7ab9200-9d6c-11eb-9851-285bea77708f.png)

How can I solve this error??

Thanks

**Comment by Flova** [comment]
Could you run this without cuda to get a better traceback? In Linux you set `CUDA_VISIBLE_DEVICES=""`.
