### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by YoungJaeLim** [eriklindernoren/PyTorch-YOLOv3#667]
![image](https://user-images.githubusercontent.com/41617180/114806723-2c83c380-9de0-11eb-86b3-558cf3b946be.png)

please help me

**Comment by Flova** [comment]
Sorry, but please don't open issues that are related to other YOLO implementations. This is a YOLOv3 implementation and your directory is named yolov5.
