### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker

### ISSUE THREAD

**Issue by zhengqun** [eriklindernoren/PyTorch-YOLOv3#669]
![image](https://user-images.githubusercontent.com/34435100/114993573-85318a00-9ece-11eb-95fd-d28e654a8c92.png)

**Comment by zhengqun** [comment]
when i train the model, i have met the error.

**Comment by Flova** [comment]
Please try and upgrade your pytorch version and see if that helps.

**Comment by zhengqun** [comment]
> Please try and upgrade your pytorch version and see if that helps.

HI ,torch version =1.8.1

**Comment by zhengqun** [comment]
And my computer is MacBookPro 18.

**Comment by Flova** [comment]
Could you try to pull the newest version. It features a new dependency management. Follow the steps in the README.md to install it that way. This should narrow down the dependency versions and isolate this installation.

**Comment by Flova** [comment]
This issue seems to be related https://github.com/pytorch/pytorch/issues/46409 btw. it also occurs on mac os.

**Comment by Flova** [comment]
This issue therefore seems to be in a upstream dependency. You could set `--n_cpu 1` or maybe `--n_cpu 0` to temporarily fix this issue.

**Comment by zhengqun** [comment]
Thanks，it's ok。

发自我的iPhone
