### ISSUE TITLE
model issue

### ISSUE THREAD

**Issue by bobo0810** [eriklindernoren/PyTorch-YOLOv3#68]
Hello,the trained model cannot be predicted. Have you encountered this problem?

**Comment by lianuo** [comment]
@bobo0810 yeah...I have smae problem ,I am looking for some other options

**Comment by bobo0810** [comment]
I found this warehouse
`https://github.com/ultralytics/yolov3`
I am currently porting its model save and load methods.

**Comment by ydixon** [comment]
This one looks promising.

**Comment by LiWentomng** [comment]
@bobo0810  Hello, have you resolved this problem? I also encountered this problem. And can do it  by the method of https://github.com/ultralytics/yolov3 ? Thank you very much.

**Comment by bobo0810** [comment]
> @bobo0810 Hello, have you resolved this problem? I also encountered this problem. And can do it by the method of https://github.com/ultralytics/yolov3 ? Thank you very much.

Yes
