### ISSUE TITLE
poetry install

### ISSUE THREAD

**Issue by mimslim** [eriklindernoren/PyTorch-YOLOv3#682]
I had put together a Yolo3 project in March that I am trying to restart.  I see that you have moved to using "poetry", so I need to change my commands.   I have successfully performed the pip3 install of poetry (after the cloning of your code):
"!sudo pip3 install poetry --user"   (on google drive)
but, the next suggested line "poetry install" dies with "poetry command not found"
My install of poetry ends with a Path warning:
  WARNING: The script virtualenv is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pkginfo is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script keyring is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script poetry is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Can you suggest how to get your Yolov3 code running on Google Drive with other commands?

I've tried 
!set PATH "${PATH}:/root/.local/bin"     but it doesn't seem to have any effect on PATH, which remains:
/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin:/opt/bin

**Comment by Flova** [comment]
Try ``!pip3 install poetry` without the `--user`.

**Comment by Flova** [comment]
Here is an example of a working installation:
https://colab.research.google.com/drive/1Yp0yLLfnYA_pk1b9nq-VZsVOfNWqErnY?usp=sharing
