### ISSUE TITLE
custom dataset json2txt

### ISSUE THREAD

**Issue by caihaunqai** [eriklindernoren/PyTorch-YOLOv3#686]
Hello! I am a new guy in object detection. I follow what said in Readme.md  and it run. Now I want to train using my custom dataset, which is also in coco format, however it's label are in json format. Can you help me to transfer? Have anyone transfer it before? Thank you very much!

**Comment by jaagut** [comment]
Hi,
well, for a custom JSON format, you probably need to write a custom script to convert to convert your format to the darknet txt format. If your JSON format already follows a known format, maybe there already exists a converter.

For a custom script, you could have a look at the following, maybe you could use it as a base: https://github.com/bit-bots/AutoImageLabeler/blob/master/yolo/createYoloLabels.py

**Comment by caihaunqai** [comment]
> Hi,
> well, for a custom JSON format, you probably need to write a custom script to convert to convert your format to the darknet txt format. If your JSON format already follows a known format, maybe there already exists a converter.
> 
> For a custom script, you could have a look at the following, maybe you could use it as a base: https://github.com/bit-bots/AutoImageLabeler/blob/master/yolo/createYoloLabels.py

Thank you very much! I have finished it. The followings are the codes I used.
`from __future__ import print_function
import os, sys, zipfile
import json
 
class_num = 0
def convert(size, box):
    dw = 1. / (size[0])
    dh = 1. / (size[1])
    x = box[0] + box[2] / 2.0
    y = box[1] + box[3] / 2.0
    w = box[2]
    h = box[3]
 
    x = x * dw
    w = w * dw
    y = y * dh
    h = h * dh
    return (x, y, w, h)
 
 
json_file = '/Data/coco/annotations/instances_val2017.json'  # # Object Instance 类型的标注
 
data = json.load(open(json_file, 'r'))
ana_txt_save_path = "/Data/coco/test2017"  # 保存的路径
if not os.path.exists(ana_txt_save_path):
    os.makedirs(ana_txt_save_path)

index = 0
cat_id_map = {}
for img in data['images']:
    filename = img["file_name"]
    img_width = img["width"]
    img_height = img["height"]
    img_id = img["id"]
    ana_txt_name = filename.split(".")[0] + ".txt"  # 对应的txt名字，与jpg一致
    index +=1
    print(str(index) +'   '+str(ana_txt_name))
    f_txt = open(os.path.join(ana_txt_save_path, ana_txt_name), 'w')# 保存的文件



    for ann in data['annotations']:
        if ann['image_id'] == img_id:
            if ann['category_id'] not in cat_id_map:
                cat_id_map[ann['category_id']] = class_num
                class_num += 1
            box = convert((img_width, img_height), ann["bbox"])
            f_txt.write("%s %s %s %s %s\n" % (cat_id_map[ann['category_id']], box[0], box[1], box[2], box[3]))
        
    f_txt.close()
fileObject = open('/Data/coco/val_cat_id_map.txt', 'w') # 类别进行重新映射
for cat_id in cat_id_map:  
    fileObject.write(str(cat_id))
    fileObject.write('\n')
fileObject.close()
`

**Comment by Flova** [comment]
You could also use some existing tool: https://github.com/ssaru/convert2Yolo
