### ISSUE TITLE
yolo-detect gives error " No module named 'ipykernel' "

### ISSUE THREAD

**Issue by AquaSpare** [eriklindernoren/PyTorch-YOLOv3#689]
Hello! 

I am running on a google colab notebook and have followed the guide and have trained a model on my own custom dataset. The training had no problems, but running the "poetry run yolo-detect --images data/samples/" command gives a strange error. 

Error message: ModuleNotFoundError: No module named 'ipykernel'

I have tried to run pip install ipykernel in my notebook, but still get the same ModuleNotFoundError. 
I am really scratching my head on this one.

**Comment by AquaSpare** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/My Drive/DL Grupp 3/PyTorch-YOLOv3/pytorchyolo/detect.py", line 23, in <module>
    import matplotlib.pyplot as plt
  File "/root/.cache/pypoetry/virtualenvs/pytorchyolo-PEzsE0gG-py3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/root/.cache/pypoetry/virtualenvs/pytorchyolo-PEzsE0gG-py3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/root/.cache/pypoetry/virtualenvs/pytorchyolo-PEzsE0gG-py3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'ipykernel'

**Comment by Flova** [comment]
That's weird. It seems to be specific to some monkey patch applied by collab. If you want to add dependencies to poetry try `poetry add ipykernel` (slower but cleaner) or first `poetry shell` and then `pip install ipykernel` (faster but not so nice).

**Comment by AquaSpare** [comment]
> That's weird. It seems to be specific to some monkey patch applied by collab. If you want to add dependencies to poetry try `poetry add ipykernel` (slower but cleaner) or first `poetry shell` and then `pip install ipykernel` (faster but not so nice).

Thanks for the help, `poetry add ipykernel` worked!

**Comment by Gricha1** [comment]
i have the same problem and this solution didnt help me.(maybe i do something wrong)
I have error on  !poetry add ipykernel   command which is 



Using version ^6.0.3 for ipykernel

Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  The current project's Python requirement (>=3.6.2) is not compatible with some of the required packages Python requirement:
    - ipykernel requires Python >=3.7, so it will not be satisfied for Python >=3.6.2,<3.7
  
  Because ipykernel (6.0.3) requires Python >=3.7
   and no versions of ipykernel match >6.0.3,<7.0.0, ipykernel is forbidden.
  So, because pytorchyolo depends on ipykernel (^6.0.3), version solving failed.

  at /usr/local/lib/python3.7/dist-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For ipykernel, a possible solution would be to set the `python` property to ">=3.7"



my python version on google colab is: Python 3.7.11. I've tried to reinstall python but it didnt help.

**Comment by Gricha1** [comment]
@Flova could you help?(

**Comment by Flova** [comment]
Set the minimum python version to 3.7 in the pyproject.toml. This would resolve this error. It states that the needed library only supports python >= 3.7 and older python versions would cause errors and this is relevant because this project here also supports older versions.
