### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-exudgkoy/cryptography/

### ISSUE THREAD

**Issue by superchenyan** [eriklindernoren/PyTorch-YOLOv3#691]

**Comment by superchenyan** [comment]
when pip3 install poetry --user

**Comment by Flova** [comment]
Please provide more context like the complete stack trace, the environment and what you are doing.

Maybe also update pip using `pip3 install pip --upgrade`.

This also seems like an upstream issue so maybe open the issue in the poetry repo.
