### ISSUE TITLE
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 4386616 in yolo custom dataset

### ISSUE THREAD

**Issue by saifullahbhutta** [eriklindernoren/PyTorch-YOLOv3#692]
## What I'm trying to do
i am trying to detect cars with the help of game, i mages taken were screen shots and labelled than in yolo format

## What I've tried
i tried training using google colab but this error is coming and i dont know what should i do

**Comment by Flova** [comment]
The images are padded to a square before they are fed into the network. It seems like your code is missing that feature. (The tensor in the traceback is 16:9 not 1:1). Did you change anything regarding the transforms applyed by the data loader?
You also need to change the number of filters in the layer before the yolo layer when you change the number of classes in the .cfg. 
Please provide the information requested in the template if your question in not covered by my answer as you might have changes or an old version of the software.

**Comment by saifullahbhutta** [comment]
i labelled the images and then used. when i was labeling i used only one class

for one class i did changed the filters just before the yolo layer which is 18

i also tried in yolov3 error are in the same lines 

line 123, in <module>
    model.load_darknet_weights(opt.weights_path)

line 315, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 4386616


i have also attached my cfg file for your review




[yolov4-obj.pdf](https://github.com/eriklindernoren/PyTorch-YOLOv3/files/6541941/yolov4-obj.pdf)

**Comment by Flova** [comment]
Yolov4 may no be compatible with this repo.

**Comment by saifullahbhutta** [comment]
> Yolov4 may no be compatible with this

firstly i try yolo 3 with these weights and similar problem was occuring. http://pjreddie.com/media/files/darknet53.conv.74

than i decided may be their is some problem i should switch to yolo v4 but again changing every thing at the end result is coming the same.

**Comment by Flova** [comment]
Could you share your issue with the V3 weights?

**Comment by saifullahbhutta** [comment]
> Could you share your issue with the V3 weights?

line 123, in <module>
    model.load_darknet_weights(opt.weights_path)

conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[256, 128, 3, 3]' is invalid for input of size 264248

**Comment by Flova** [comment]
Are you sure that your `.cfg` and `weights` match in their topology?

**Comment by saifullahbhutta** [comment]
> Are you sure that your `.cfg` and `weights` match in their topology?

yes, as i shared with you i used exact same .cfg and weights. but in yolo3 and 4 every time problem remains.

**Comment by Flova** [comment]
Sorry, but this doesn't makes sense. You only provided one yolov4 cfg as a pdf file. I know nothing about your code status and the other things requested in the template. It also seems like this error isn't a bug of this implementation, because you also opened a similar issue at the darknet repo: https://github.com/pjreddie/darknet/issues/2428
I am sorry, but this makes trouble shooting quite hard especially if its a problem unrelated to this implementation.

**Comment by yanchujian** [comment]
Same error, do you have salved it?

**Comment by jaagut** [comment]
@yanchujian No, it was not solved, as important information was still missing.
Could you please open a new issue and fill out all the required information in the new issue?
