### ISSUE TITLE
    paths, imgs, bb_targets = list(zip(*batch)) ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by Bicker1** [eriklindernoren/PyTorch-YOLOv3#693]
when running the training .py  ; this error exited with datasets.py

**Comment by Flova** [comment]
Please provide the information from the template.

Using the given error it seems like you got an empty batch. This is the case if 

* You have an error in your dataset format which leads to an empty dataset
* You have an error in the image format, label format, ... leading to many/all images being dropped. This would be indicated by errors/warnings above the given one.

**Comment by Bicker1** [comment]
> Please provide the information from the template.
> 
> Using the given error it seems like you got an empty batch. This is the case if
> 
> * You have an error in your dataset format which leads to an empty dataset
> * You have an error in the image format, label format, ... leading to many/all images being dropped. This would be indicated by errors/warnings above the given one.
