### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorchyolo'

### ISSUE THREAD

**Issue by xiaofeng-c** [eriklindernoren/PyTorch-YOLOv3#700]

**Comment by xiaofeng-c** [comment]
when i run the test.py,i encounter the problem ModuleNotFoundError: No module named 'pytorchyolo',could you please help me?

**Comment by Flova** [comment]
Please provide the requested information. There are multiple installation methods and it's hard to tell with so little information.

You don't need to run the test.py. You can run the command `yolo-test` directly if you installed it correctly. If you use poetry remember running `poetry install` to install the dependencies and the application itself. Afterwards you are able to run `poetry run yolo-test` or just `yolo-test` if you joined the environment via `poetry shell`. This is also described in the readme.

**Comment by xiaofeng-c** [comment]
Thank you!
