### ISSUE TITLE
Why is cls_conf always 0.5? 

### ISSUE THREAD

**Issue by nypzxy** [eriklindernoren/PyTorch-YOLOv3#703]
## What I'm trying to do
Hi I am trying to train a custom model which only has one class. After training based on the code, it is so wired that the cls conf value is always 0.5, not even slightly fluctuated.
![image](https://user-images.githubusercontent.com/22143473/122243057-6499a680-cef6-11eb-9049-7d6a491712db.png)

Can anyone help on this? Many thanks

**Comment by nypzxy** [comment]
And also the conf score are very low too. When I use yolov5, the obj_conf are above 0.5, it should be fine. But in this repos, it is much lower, Also is it possible that obj_conf and cls_conf have some correlation? 

BTW, I am using tiny-yolo.

**Comment by Flova** [comment]
What yolo architecture are you using? tiny v3? tiny v4?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
