### ISSUE TITLE
How to train the pytorch-yolov3 on gpu when using poetry enviornment?

### ISSUE THREAD

**Issue by geetanjalisharma** [eriklindernoren/PyTorch-YOLOv3#704]
## Context

- [x] I have installed this repo manually and the issue occurred on this commit:

- [ ] I have installed this repo via `PIP` and the issue occurred on version: 
- [x] The issue occurred when using the following .cfg model:
    - [ ] `yolov3`
    - [ ] `yolov3-tiny`
    - [x] `CUSTOM`

## Necessary Checks

- [ ] The issue occurred on the newest version

- [x] I couldn't find a similar issue here on this project's github repo
- [ ] If the issue is CUDA related (CUDA error), I have tested and provided the traceback also when CUDA is turned off 
- [ ] I have provided all tracebacks or printouts in ```Text Form``` 
- [ ] In case, the issue occurred on a custom .cfg model, I have provided the model down below

## Steps to Reproduce

1.
2.
3.
...

### Custom `.cfg`

<details><summary>Custom .cfg</summary>
<p>

</p>
</details>

**Comment by Flova** [comment]
Sorry I don't full understandy your issue. 
To train your network in the poetry environment follow the step in the `README.md`.
The mainly consits of the follwing steps:
* Clone the repo
* Install poetry
* Use poetry to install the dependencies
* Run `poetry run yolo-train ......` to train a network with your desired settings

The gpu is used by default if you have an nvida gpu and the correct CUDA drivers

**Comment by Flova** [comment]
I close this for now. If that doesn't answer your question feel free to clarify it.
