### ISSUE TITLE
how to increase the num of classes?

### ISSUE THREAD

**Issue by ziming-liu** [eriklindernoren/PyTorch-YOLOv3#71]
i want to detect objects as much as possible ,could the model can be expand to detect more class?? someone can give some advices about that? thanks

**Comment by fadi212** [comment]
You will have to train the model from scratch for your number of classes. As of now, I don't think there is any model that can modify the weights.

**Comment by Flova** [comment]
You need to adjust the filters before the YOLO layer and set the `classes` in the yolo layer in the cfg file
