### ISSUE TITLE
Amount of data augmentation

### ISSUE THREAD

**Issue by BielStela** [eriklindernoren/PyTorch-YOLOv3#710]
## What I'm trying to do
Hello ! first of all congrats for this terrific implementation! I'm trying to figure out how data augmentation works, actually how many new images it creates or which % of augmentation does.

## What I've tried
Since it is not documented I looked at the source code and the Pytorch DataSet documentation but couldn't find what I need. Looking at the source looks lik the `LIstDataset.__getitem__` applies the transformation to each item? surely it doesn't work like this. I'm not familiar with pytorch DataSet classes so any help will be much appreciated!

Thanks in advance!

**Comment by Flova** [comment]
Hey,

the augmentation is applied using the imgaug library. It is used to apply a set of modifications to each image that is loaded by the dataset class. The dataset class interface defines that a list of PyTorch transforms may be passed to the  `ListDataset.__getitem__`. In the implementation of   `ListDataset.__getitem__` these transforms are called after each image is loaded. The transforms do not only include a wrapper that wraps  `imgaug -> PyTorch transforms` but also non-augmentation transforms used to convert e.g. label coordinate systems, `ndimage -> Tensor` or the padding of the images.

This architecture results in every image being augmented, but the augmentation level and type are randomized as defined in the `augmentations.py`.

Does this answer your question?

**Comment by Flova** [comment]
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

**Comment by BielStela** [comment]
Absolutely! Thank you!
