### ISSUE TITLE
Change YoloV3 backbone with DenseNet

### ISSUE THREAD

**Issue by junaid340** [eriklindernoren/PyTorch-YOLOv3#718]
Can anyone please help me with how to change the backbone of the yoloV3 with DenseNet??

**Comment by Flova** [comment]
I have not tried this, but as long as it uses the standard layers which are also used in yolo v4 and V3 you should be able to use a corresponding cfg file which you will most likely find for e.g. the normal darknet implementation.

**Comment by junaid340** [comment]
@Flova thanks for getting back to me. I have found the cfg file for DenseNet as backbone, I found in the original repo i.e. _https://github.com/pjreddie/darknet/blob/b339a70cbb8f4378b2bc19e560e9db8a6cde3737/cfg/densenet201.cfg_ if I use it in pytroch will it work? Actually, I'm new to pytorch and don't know much so kindly overlook my dumbness !!

**Comment by Flova** [comment]
This is cfg seems to be for classification, so it is only the backbone. You would need to add the YOLO decoder to it or you search for a cfg that already includes the YOLO layers.

**Comment by junaid340** [comment]
here is a yolov3.cfg : _https://github.com/pjreddie/darknet/blob/b339a70cbb8f4378b2bc19e560e9db8a6cde3737/cfg/yolov3.cfg_ 
will it be enough to merge these two into one... or do I have to make some changes in it!

**Comment by Flova** [comment]
You would need to combine both networks in a working way, considering the different layer sizes, .... This is not impossible, but also not easy especially to estimating the hyperparameters for the following training.

**Comment by Flova** [comment]
A good too to visualize the cfg files is [Netron](https://netron.app).

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.

**Comment by ravil9C8** [comment]
> here is a yolov3.cfg : _https://github.com/pjreddie/darknet/blob/b339a70cbb8f4378b2bc19e560e9db8a6cde3737/cfg/yolov3.cfg_ will it be enough to merge these two into one... or do I have to make some changes in it!

Did you implement ?
