### ISSUE TITLE
how does training work?

### ISSUE THREAD

**Issue by Malitem** [eriklindernoren/PyTorch-YOLOv3#72]
So i see there should be some kind of txt files for training and validation, but i don't quite understand what should be written in those files.

**Comment by LalitPradhan** [comment]
You need to write the path to your images.

in train.txt you need to have path to each image in a separate line. Eg:
data/obj/img0001.jpg
data/obj/img0002.jpg
data/obj/img0003.jpg
data/obj/img0004.jpg

**Comment by Malitem** [comment]
Okay, i figured that one out. Thank you. But now why I run train.py file I get the following error:
fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
Any ideas?

**Comment by eriklindernoren** [comment]
@Malitem Did you resolve this issue?

**Comment by eriklindernoren** [comment]
You can follow the steps [here](https://github.com/eriklindernoren/PyTorch-YOLOv3#train-on-custom-dataset) to train on a custom dataset.

**Comment by peterhsu2018** [comment]
Hi, i follow the steps
and custom dataset:
```
images:
data\custom\images\1.jpg
data\custom\images\2.jpg
..
labels:
data\custom\labels\1.txt (format like this e.g. 3 0.475938 0.377917 0.144375 0.189167)
data\custom\labels\2.txt
..
```

return the error message:
```
fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
```

**Comment by kaikaizhu** [comment]
@peterhsu2018
i have the same problem.
AttributeError: 'str' object has no attribute 'seek'  and  AttributeError: 'str' object has no attribute 'read'
How to fit it?

**Comment by Theohhhu** [comment]
same problem and if I debug step by step would got more mistakes looking like this:
KeyError: 'batch_indices'
AttributeError: 'dict' object has no attribute 'batch_indices'
AttributeError: 'dict' object has no attribute 'data_queue'

**Comment by kaikaizhu** [comment]
@Theohhhu  @peterhsu2018  @eriklindernoren
Will it be the reason for the version?
My version is: CUDA 8.0 + cudnn6.0 + tensorflow 1.2.0
I need help ,Thanks a lot!

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
