### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Gricha1** [eriklindernoren/PyTorch-YOLOv3#720]
## What I'm trying to do

When im trying to use poetry run command every time i get PermissionError
## What I've tried

!poetry run ./weights/download_weights.sh

i get: 

PermissionError

  [Errno 13] Permission denied: './weights/download_weights.sh'

  at /usr/lib/python3.7/os.py:597 in _execvpe
       593│         argrest = (args,)
       594│         env = environ
       595│ 
       596│     if path.dirname(file):
    →  597│         exec_func(file, *argrest)
       598│         return
       599│     saved_exc = None
       600│     path_list = get_exec_path(env)
       601│     if name != 'nt':

**Comment by Flova** [comment]
You don't need poetry for the download script, since it is a bash script. Maybe give it a try without it.

**Comment by sumedhgodbole** [comment]
running chmod +x on the .sh files solved it for me

**Comment by Flova** [comment]
They should be executable by default, but you could give it a try nevertheless.

**Comment by Gricha1** [comment]
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/720#issuecomment-883263189
Thanks a lot it helped me. 
I wanted to train model with 3 classes in google colab and next 2 lines helped me create the cfg file
!chmod +x ./config/create_custom_model.sh
!./config/create_custom_model.sh 3
(carefull the cfg file will be created in /content/PyTorch-YOLOv3 path)
