### ISSUE TITLE
A question about resizing gt_box?

### ISSUE THREAD

**Issue by goldentimecoolk** [eriklindernoren/PyTorch-YOLOv3#721]
I saw there was a [resizing operation on images](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/utils/datasets.py#L135) for multi-scale training, but I didn't saw the corresponding operation on its annotations, i.e. gt_box. Is that feasible?
Thx!

**Comment by Flova** [comment]
The annotations should be stored in a relative coordinate system that is independent of the image size at that point. But I can double check that.

**Comment by Flova** [comment]
They are indeed in the relative coordinate system meaning, that 1 stands for the full height or width of the image und 0 for no height or width and the boxes are in-between this regarding their width, height, x Andy coordinates. So you are able to resize the batches without worrying about the labels.

**Comment by goldentimecoolk** [comment]
Thanks for your reply. I see. 
Indeed, you restore the size of gt_box to the sizes of corresponding feature maps via [t = targets * gain](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/utils/loss.py#L212). That's a smart implementation. Then I have several questions in the next few lines of the code.
1. `j, k = ((gxy % 1. < g) & (gxy > 1.)).T`[here](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/utils/loss.py#L222), the `k` is not used in the following. Does that mean only center_x of gt_box is used as filtering condition?
2. `t = t[j]`[here](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/utils/loss.py#L218), `j` indicates the indices of annotation targets satisfying some restrictions. Does that mean we will give up the targets that violate the requirements?
