### ISSUE TITLE
Poetry: command not found 

### ISSUE THREAD

**Issue by MarcAmil30** [eriklindernoren/PyTorch-YOLOv3#729]
I tried to install from source using a poetry virtual environment.

I have successfully conducted these instructions: 
```
 git clone https://github.com/eriklindernoren/PyTorch-YOLOv3
cd PyTorch-YOLOv3/
pip3 install poetry --user
```

However, when running `poetry install` it states on my terminal `-bash: poetry: command not found`. I understand that there was a similar issue to this before and you suggested trying `!pip3 install poetry`, but the same error still occurs and therefore I cannot run `poetry shell`. 

 I want to kindly ask how I can solve this issue. Thanks

**Comment by Flova** [comment]
Is there any warning when you are installing poetry? Pip often installes packages in `~/local/bin` which is not in the `PATH` environment variable in many distros. The shell is therefore not able to find the binary. Try adding it to the path. Modern versions of pip warn you if the location is not in the path.
