### ISSUE TITLE
Why the mAP is 0.08 on coco val2014？It's so lower lower lower！

### ISSUE THREAD

**Issue by sunze992** [eriklindernoren/PyTorch-YOLOv3#733]
I downloaded coco2014 dataset and official yolov3.weights as this repo recommended and  used them.
But I got mAP 0.08 by running test.py.  (img_size:416 , iou_thres:0.5  ,conf_thres:0.01  , nms_thres:0.4)
I just downloaded this repo and ran test.py, the code in this repo was not modified.
I tried to modify conf_thres(0.001) and nms_thres, but it still didn't work.

Do you know how to solve this issue? Many thanks!

**Comment by Flova** [comment]
Hi, thanks for your issue!
The performance with the original weights should match the baseline, so it seems like an issue with the exact environment of yours, which is weird nevertheless.
Could you provide the requested information from the bug template? This makes troubleshooting much easier.
Did you also download the weights again? It could be that the file is somehow corrupted.

**Comment by Flova** [comment]
I just ran the current clean master on my machine using the poetry installation and it resulted in the expected mAP.

**Comment by sunze992** [comment]
> I just ran the current clean master on my machine using the poetry installation and it resulted in the expected mAP.

Thank you very much for your answer! I downloaded the weights and cocodataset again, but the mAP was still 0.08 by running test.py.  Do you think it is an environmental problem? My OS is Windows10 and I didn't use the poetry. I downloaded this repo by "Downlaod Zip" instead of "git clone". Related images are here.

![image](https://user-images.githubusercontent.com/58905939/131446643-e38bcf25-6f0c-4d57-884f-095e93c0d3f5.png)
![image](https://user-images.githubusercontent.com/58905939/131446955-5c5ff264-1fd8-449b-b122-62f6eaa7f8aa.png)

**Comment by Flova** [comment]
This seems to be a version problem. You are using the versions that are installed on your system by other applications. This less isolated way results in a weird version of some dependency being used. I also only test this repo for Ubuntu and Arch Linux so it could also be a Windows related issue although it seems unlikely as I know of some happy Windows users. How did you download and prepare the weights and dataset without the bash scripts on Windows? Maybe something went wrong there.
Please install this repo via poetry or at least directly via pip as this is most likely this issue here.

**Comment by sunze992** [comment]
> This seems to be a version problem. You are using the versions that are installed on your system by other applications. This less isolated way results in a weird version of some dependency being used. I also only test this repo for Ubuntu and Arch Linux so it could also be a Windows related issue although it seems unlikely as I know of some happy Windows users. How did you download and prepare the weights and dataset without the bash scripts on Windows? Maybe something went wrong there.
> Please install this repo via poetry or at least directly via pip as this is most likely this issue here.

OK, I'll do it again as you suggested. Thank you so much for your assistance.

**Comment by dkhanna511** [comment]
Hi, I want to run it on a subset of BDD dataset. So I only have 4 classes. I am getting similar issues of mAP = 0.01. How did you solve this issue?
