### ISSUE TITLE
 negative coordinate

### ISSUE THREAD

**Issue by heeheee888** [eriklindernoren/PyTorch-YOLOv3#736]
## What I'm trying to do

I'm trying to use YOLOv3 for my custom dataset
However, I got negative bounding box coordinates after training and inference.
So, I got bounding box out of image

## What I've tried

I try to find issues, but I couldn't.

How can I solve?

**Comment by heeheee888** [comment]
![giraffe.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/67aac62e-2284-434a-ad21-5c50a882e9bd/giraffe.png)

I did train on COCO Dataset. But like this example, I got bounding boxes out of image.

**Comment by heeheee888** [comment]
Thank you for your response.
Even when I try to train COCO Dataset, I got negative coordinates. 
![giraffe](https://user-images.githubusercontent.com/81950714/136918472-d86ff13d-9bc5-4be1-9046-297f943594be.png)

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
