### ISSUE TITLE
'poetry run' from custom directory

### ISSUE THREAD

**Issue by emoebel** [eriklindernoren/PyTorch-YOLOv3#739]
## What I'm trying to do
Launch my training procedure on a custom dataset. I'm using a GPU cluster (with a passive job)
I would like to launch the job from a directory different from `/.../PyTorch-YOLOv3`

## What I've tried
I have tried running : `poetry run yolo-train -d fish.data -m yolov3-custom.cfg --pretrained_weights /net/serpico-fs2/emoebel/github/PyTorch-YOLOv3/weights/darknet53.conv.7`

from some custom directory. But I get error messages complaining that some file is not found:
```
  ModuleOrPackageNotFound
  No file/folder found for package pytorchyolo
```
So I guess that above command expects that the current directory is `/.../PyTorch-YOLOv3`

How can I launch the job from my own directory ?

**Comment by Flova** [comment]
Yea `poetry run` only works inside the projects folder tree. There is an open upstream issue to add an argument to set the patch https://github.com/python-poetry/poetry/issues/2179.

Why is `cd /net/serpico-fs2/emoebel/github/PyTorch-YOLOv3/; poetry run yolo-train -d fish.data -m yolov3-custom.cfg --pretrained_weights weights/darknet53.conv.7`no option?

You could also install it with pip using `pip install pytorchyolo`. You would lose some benefits of poetry, but it should also work. This enables the `yolo-train command for every folder without further activation of a virtual env.

**Comment by emoebel** [comment]
Hi FLova. It is absolutely an option to work as you suggest. It just does not fit exactly my workflow. I'll look into installing pytorchyolo with pip. Thanks!
