### ISSUE TITLE
How to implement the “transfer learning” using my own data set and different “classes numbers”? 

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [eriklindernoren/PyTorch-YOLOv3#745]
Hi,
    I would like to make YOLO do transfer learning. If I stopped YOLO training after the “dota-yolov3-tiny_300000.weights” has been generated, then how to implement the “transfer learning” using my own data set and different “classes numbers”? Especially, how to design the “the last few layers of the network be unfreezed for transfer learning or finetuning”?
    So, could you pls help to give me some suggestions? Thanks!

**Comment by Flova** [comment]
Hi,
this repo does not support the freezing of certain layers in an easy way. You need to deactivate the auto grad for these layers by writing some custom code. This being said you can load pre-trained weights for the first layers while training the last ones from scratch to get e.g. a different number of classes. This is done if you use e.g. `darknet53.conv.74`. The `74` in the name gets parsed as "this file contains the first 74 layers". You can save the weights in the darknet format as described in #696. The function not only takes the path, but also a cutoff like "74". If you have cut off and saved your weights you can use them like this: `--pretrained_weights weights/darknet53.conv.74` in your train command.
