### ISSUE TITLE
Input size config question

### ISSUE THREAD

**Issue by achel-x** [eriklindernoren/PyTorch-YOLOv3#748]
The homepage readme provides mAP of 640 model. But in the config file, it only set 416. I wonder if I want to change the size of input image. Do the following parameter setting need to be changed either?

**Comment by Flova** [comment]
You can just change the resolution in the `.cfg` file. YOLO is fully convolutional, so the weights aren't affected by this change computational-wise. This being said a training for the specific resolution is recommended.

**Comment by Flova** [comment]
You can use one model for all resolutions as yolo uses exclusively convolutional layers, which are translation invariant. It just produces a higher resolution yolo grid output, if the input resolution is higher. BUT the features themselves may be differently sized in images, with different resolutions, so it could be the case, that a model which is trained from scratch or with multiscale training performs better with its "native" resolution.
