### ISSUE TITLE
I trained using the VOC dataset, but nothing was detected.

### ISSUE THREAD

**Issue by frothmoon** [eriklindernoren/PyTorch-YOLOv3#75]
It trained very fast and completed in about two or three hours. When I run `test.py`, the result is very poor，and nothing is detected in the image.
`Mean Average Precision:0.0343`
I don't know how to solve this problem, I really need your help, thank you in advance.

**Comment by lolongcovas** [comment]
similar issue with coco dataset, I trained for 20 epochs and when I evaluate the model in COCO, no detections are found. how many iterations should we need?

**Comment by nathantsoi** [comment]
I am looking at training this network from VOC & COCO as well. Can you post details on how you did the training @frothmoon and @lolongcovas 

I see in the original paper, you will probably want to train for many more epochs. See section 2.2 https://pjreddie.com/media/files/papers/yolo.pdf

<img width="744" alt="screen shot 2018-10-05 at 8 49 18 pm" src="https://user-images.githubusercontent.com/399770/46567058-37407200-c8e0-11e8-944a-6f7493dc23c4.png">

**Comment by frothmoon** [comment]
My parameters are set as follows：
```
--epochs 100 
--conf_thres 0.5 
```
```
batch=32
subdivisions=4
momentum=0.9
learning_rate=0.001
```
```
[yolo]
ignore_thresh= .5
```

**Comment by mshmoon** [comment]
I want to train the code on pascal voc, so I want to know that is it very diffcult to traing on voc dataset? May be I need to adjust a  lot of codes? Because my device is gtx1060 limited to train code on big dataset such as coco.  Thank you

**Comment by ningxiangyun** [comment]
have you trained the model of yolov3 on pascal voc?

**Comment by zhendong94** [comment]
have you trained the model of yolov3 on pascal voc?

**Comment by eriklindernoren** [comment]
@frothmoon @lolongcovas @nathantsoi There was a bug in `Darknet.save_weights` that was fixed recently. There have also been some other major improvements made to the training support in general. Can you try with the current version?

**Comment by ZzzackChen** [comment]
> @frothmoon @lolongcovas @nathantsoi There was a bug in `Darknet.save_weights` that was fixed recently. There have also been some other major improvements made to the training support in general. Can you try with the current version?

I have tried with the current version, but I didn't know how many epochs should I training.
After training 100 epochs on VOC, the mAP get up to 0.10
So I tried continue training... Could you tell me how many epochs you training?
And on coco data, the result is worse!
after 28 epochs, the mAP is only 0.006 nearly zero.
Anyone have training successfully on voc or coco and get ideal mAP?

**Comment by yyx1107** [comment]
> > @frothmoon @lolongcovas @nathantsoi There was a bug in `Darknet.save_weights` that was fixed recently. There have also been some other major improvements made to the training support in general. Can you try with the current version?
> 
> I have tried with the current version, but I didn't know how many epochs should I training.
> After training 100 epochs on VOC, the mAP get up to 0.10
> So I tried continue training... Could you tell me how many epochs you training?
> And on coco data, the result is worse!
> after 28 epochs, the mAP is only 0.006 nearly zero.
> Anyone have training successfully on voc or coco and get ideal mAP?
I want to train on VOC ,and I modified voc.data,voc.names and yolo.cfg.And I use voc_label.py to get 2007_train.text , 2007_test.text and so on.
When I run "python3 train.py --data_config config/voc.data --pretrained_weights weights/darknet53.conv.74", there are some errors:
![Screenshot from 2019-06-13 14-38-48](https://user-images.githubusercontent.com/50829614/59409585-17efd200-8de9-11e9-8f82-12c3eabf7d15.png)
Is there anything else that needs to be changed? Thank you

**Comment by zc850134557** [comment]
> > > @frothmoon @lolongcovas @nathantsoi There was a bug in `Darknet.save_weights` that was fixed recently. There have also been some other major improvements made to the training support in general. Can you try with the current version?
> > 
> > 
> > I have tried with the current version, but I didn't know how many epochs should I training.
> > After training 100 epochs on VOC, the mAP get up to 0.10
> > So I tried continue training... Could you tell me how many epochs you training?
> > And on coco data, the result is worse!
> > after 28 epochs, the mAP is only 0.006 nearly zero.
> > Anyone have training successfully on voc or coco and get ideal mAP?
> > =========================================================================
> > I want to train on VOC ,and I modified voc.data,voc.names and yolo.cfg.And I use voc_label.py to get 2007_train.text , 2007_test.text and so on.
> > When I run "python3 train.py --data_config config/voc.data --pretrained_weights weights/darknet53.conv.74", there are some errors:
> > ![Screenshot from 2019-06-13 14-38-48](https://user-images.githubusercontent.com/50829614/59409585-17efd200-8de9-11e9-8f82-12c3eabf7d15.png)
> > Is there anything else that needs to be changed? Thank you

You may have the wrong data path

**Comment by summersdog** [comment]
> > @frothmoon @lolongcovas @nathantsoi There was a bug in `Darknet.save_weights` that was fixed recently. There have also been some other major improvements made to the training support in general. Can you try with the current version?
> 
> I have tried with the current version, but I didn't know how many epochs should I training.
> After training 100 epochs on VOC, the mAP get up to 0.10
> So I tried continue training... Could you tell me how many epochs you training?
> And on coco data, the result is worse!
> after 28 epochs, the mAP is only 0.006 nearly zero.
> Anyone have training successfully on voc or coco and get ideal mAP?

Same problem,have u figure it out?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
