### ISSUE TITLE
I can' t install the project

### ISSUE THREAD

**Issue by hongyiWeng** [eriklindernoren/PyTorch-YOLOv3#751]
When I run 'poetry install' to install the environment,I am always pointed that there are 'no poerty'.
I don't know why this question happen,and I install them in Ubuntu18.04.

**Comment by Flova** [comment]
You need to install poetry first as stated in the README.md

**Comment by hongyiWeng** [comment]
> 

Thanks.But I have already installed portry through command 'pip3 install poetry --user'.What should I do, beside it?

**Comment by Flova** [comment]
Okay, it could be that `~/.local/bin` directory is not included in the `$PATH` environment variable of your system, so your shell doesn't pick them up. Pip installs `--user` installs there.

https://unix.stackexchange.com/questions/240037/why-did-pip-install-a-package-into-local-bin

Fix: https://askubuntu.com/questions/402353/how-to-add-home-username-bin-to-path

**Comment by hongyiWeng** [comment]
> Okay, it could be that `~/.local/bin` directory is not included in the `$PATH` environment variable of your system, so your shell doesn't pick them up. Pip installs commands of `--user` installations there.
> 
> https://unix.stackexchange.com/questions/240037/why-did-pip-install-a-package-into-local-bin
> 
> Fix: https://askubuntu.com/questions/402353/how-to-add-home-username-bin-to-path

Thanks very much. I think it's possible and I will try your methods tomorrow.Thanks again.

**Comment by Flova** [comment]
No problem. There is also a warning during the pip installation of poetry (or any other tool) that says that the install dir is not currently in the `PATH` in case this happens again.

**Comment by hongyiWeng** [comment]
> No problem. There is also a warning during the pip installation of poetry (or any other tool) that says that the install dir is not currently in the `PATH` in case this happens again.

I will note the key that u mentioned.Besides,I also try other way to use Yolo_v3,maybe u see,'darknet'.I think 'darknet' is also a good way to utilize it.
