### ISSUE TITLE
tiny-yolo-v3 Rutime error UnityML

### ISSUE THREAD

**Issue by akbarali2019** [eriklindernoren/PyTorch-YOLOv3#752]
Assets\ML\tiny-yolo-v3\Runtime\TinyYOLOv3Predictor.cs(11,23): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'NatSuite.ML' (are you missing an assembly reference?)

**Comment by Flova** [comment]
Are you sure this is the right repo? I have no idea what this error is and what you want to do. Please provide further information.
