### ISSUE TITLE
Does it have support on the Scaled-yolov4 model?

### ISSUE THREAD

**Issue by kadirnar** [eriklindernoren/PyTorch-YOLOv3#765]
parser.add_argument("-m", "--model", type=str, default="cfg/yolov4-csp.cfg")
parser.add_argument("-w", "--weights", type=str, default="weights/yolov4-csp.weights")

Output-1:
<img width="500" alt="teaser" src="https://user-images.githubusercontent.com/36204372/148750340-20644755-bd45-4707-b1b3-bf2fe19da5f6.png">

Output-2:
<img width="500" alt="teaser" src="https://user-images.githubusercontent.com/36204372/148750354-f66d8795-4f2f-4506-9f48-cdb1d16d60d2.png">

Output-3:
<img width="100" alt="teaser" src="https://user-images.githubusercontent.com/36204372/148750388-2166053c-bc9e-4711-912b-5087940ef736.png">

How can i solve this problem?

**Comment by Flova** [comment]
Unitl now I have not tried Scaled-YOLOv4. Could you outline the changes regarding the computation grapth, pre and post-processing?

**Comment by kadirnar** [comment]
I did not understand your question. I changed the file paths in the detection file.
It works on yolov3 and yolov4 models, but not on scaled-yolov4 and yolov4-mish models. 

Scaled Yolov4: https://github.com/AlexeyAB/darknet/issues/7087
Orijinal Repo Scale-Yolov4: https://github.com/WongKinYiu/ScaledYOLOv4
Yolov4-Mish: https://github.com/AlexeyAB/darknet/issues/6987

**Comment by kadirnar** [comment]
Pytorch-Yolov3: https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/master/pytorchyolo/detect.py#L19
Yolov4-Csp: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-csp.cfg#L1276
The nms function is used in the PyTorch-YOLOv3 repo. Used diounms in the scaled-yolov4 repo. Could it be because of this?
