### ISSUE TITLE
How to calculate validation loss

### ISSUE THREAD

**Issue by alexandrefassio** [eriklindernoren/PyTorch-YOLOv3#767]
Hi there, 

I've been trying to compute the validation loss but so far I had no success. What I've tried to do was to modify test.py by adding a call to compute_loss(). I tried different ways to call this function. For example, I tried to mimic what happens on train.py where the images and labels are not modified as they are in the test.py. 

I also tried what has been suggested in this thread #632, but I couldn't make it to work.

So...despite different tries, I always end up with the following error:

```
gain[2:6] = torch.tensor(p[i].shape)[[3, 2, 3, 2]]  # xyxy gain
IndexError: index 3 is out of bounds for dimension 0 with size 2
```

Below is one of my last codes where I tried to call compute_loss() after non_max_suppression(). I also tried to call it before non_max_supression(). Tried to invoke the model to get outputs without modifying images and targets, but had no success as well.

  ```
self.module_.eval()
Tensor = torch.cuda.FloatTensor if torch.cuda.is_available() else torch.FloatTensor

# Extract labels
labels = targets[:, 1].tolist()
# Rescale target
targets[:, 2:] = xywh2xyxy(targets[:, 2:])
targets[:, 2:] *= self.module_.hyperparams['height']

imgs = Variable(imgs.type(Tensor), requires_grad=False)
imgs = imgs.to(self.device)

with torch.no_grad():
    outputs = to_cpu(self.module_(imgs))
    outputs = non_max_suppression(outputs, conf_thres=self.conf_thres, iou_thres=self.nms_thres)

    loss, loss_components = compute_loss(outputs, targets, self.module_)
```

Does someone know what should I do exactly to compute the validation loss?

bests

**Comment by Flova** [comment]
Hey there,

the compute_loss call needs to happen before the non-maximum suppression as it works on the "raw" output tensor and the non_max_suppression function is also non-differentiable.
I think the issue here is this line in the models.py file:

```python
return yolo_outputs if self.training else torch.cat(yolo_outputs, 1)
```

as well as these lines here:

```python
        if not self.training:  # inference
            if self.grid.shape[2:4] != x.shape[2:4]:
                self.grid = self._make_grid(nx, ny).to(x.device)

            x[..., 0:2] = (x[..., 0:2].sigmoid() + self.grid) * stride  # xy
            x[..., 2:4] = torch.exp(x[..., 2:4]) * self.anchor_grid # wh
            x[..., 4:] = x[..., 4:].sigmoid()
            x = x.view(bs, -1, self.no)
```

So the data is returned in a different format if the model is in the training mode. It returns a list containing the output of each yolo output layer in its raw form. If the model is not in the training mode boxes are returned directly (no threshold or nms so the number of boxes is quite large).

Sadly #632 is outdated now due to some structural changes.

A solution would be to also pass through the unmodified `x` in the way it is done in the training, aka return always both, the raw data and the boxes. You would also need to copy the targets before converting them to xyxy as the loss function works on xywh.

Also, your code seems to be modified so make sure these changes are compatible with your modifications.

Cheers

**Comment by alexandrefassio** [comment]
Thanks for the help. Thanks to your suggestions I was finally able to calculate the validation loss.

I'll explain what I did in case someone is also trying to calculate the validation loss as well.

First, I changed models.py to always return the same output format regardless of the training phase. Now it looks like this:

```
def forward(self, x, img_size):
    stride = img_size // x.size(2)
    self.stride = stride
    bs, _, ny, nx = x.shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
    x = x.view(bs, self.num_anchors, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

    if not self.training:
        if self.grid.shape[2:4] != x.shape[2:4]:
            self.grid = self._make_grid(nx, ny).to(x.device)
```

After modifying the output format, I can now call compute_loss():

```
with torch.no_grad():
    outputs = self.module_(imgs)
    loss, loss_components = compute_loss(outputs, targets, self.module_)
```

However, non_max_suppression() expects a concatenated Tensor. So, we still have to modify the output format. To do this, I implemented a post-processing function based on the code in YOLOLayer.forward():

```
def concatenate_outputs(self, outputs):
        yolo_outputs = []
        for module, x in zip(self.module_.yolo_layers, outputs):
            grid = module.grid.to(self.device)
            x[..., 0:2] = (x[..., 0:2].sigmoid() + grid) * module.stride  # xy
            x[..., 2:4] = torch.exp(x[..., 2:4]) * module.anchor_grid  # wh
            x[..., 4:] = x[..., 4:].sigmoid()
            x = x.view(x.shape[0], -1, module.no)
            yolo_outputs.append(x)
        return torch.cat(yolo_outputs, 1)
```

After that, I could finally call non_max_suppression() and execute the rest of the code to calculate mAP.


**The final function that calculates the validation loss and everything else on single batches look like this:**

```
self.module_.eval()
Tensor = torch.cuda.FloatTensor if torch.cuda.is_available() else torch.FloatTensor

imgs = Variable(imgs.type(Tensor), requires_grad=False)
imgs = imgs.to(self.device)
targets = targets.to(self.device)

with torch.no_grad():
    outputs = self.module_(imgs)
    loss, loss_components = compute_loss(outputs, targets, self.module_)

targets = to_cpu(targets)
# Extract labels
labels = targets[:, 1].tolist()
# Rescale target
targets[:, 2:] = xywh2xyxy(targets[:, 2:])
targets[:, 2:] *= self.module_.hyperparams['height']

outputs = self.concatenate_outputs(outputs)
outputs = to_cpu(outputs)
outputs = non_max_suppression(outputs, conf_thres=self.conf_thres, iou_thres=self.nms_thres)

sample_metrics = []
sample_metrics += get_batch_statistics(outputs, targets, iou_threshold=self.iou_thres)

if len(sample_metrics) != 0:
    # Concatenate sample statistics
    true_positives, pred_scores, pred_labels = [
        np.concatenate(x, 0) for x in list(zip(*sample_metrics))]

    precision, recall, AP, f1, ap_class = ap_per_class(true_positives, pred_scores,
                                                       pred_labels, labels)
```

bests
