### ISSUE TITLE
Enumerate dataloader is too slow

### ISSUE THREAD

**Issue by chijan-nh** [eriklindernoren/PyTorch-YOLOv3#77]
Hi, I use train.py code to train COCO dataset or my own dataset.

In line 79 of train.py, dataloader is enumerated and for loop runs.
When I run train.py, the calculation looks stopped in line 79. No epoch is done.
Using print debug, I am sure that the program correctly run until line 78 and `print(enumerate(dataloader))` is also able; producing the enumerate object is ok.
However, the for loop of line 79 does not start.

I use one NVIDIA Tesla P100 GPU on the Compute Engine of GCP.
Would you tell me how to solve?

**Comment by chijan-nh** [comment]
My GCE VM has vCPU x 8 and 52 GB memory, and I use only 10 images to verify the code.
Thus I think that memory error cannot be caused.

**Comment by chijan-nh** [comment]
It is caused by the while loop in the definition of ListDataset.
With attention to `len(img.shape)`, I can avoid this issue.

**Comment by akshay993** [comment]
I am using the same GPU (NVIDIA Tesla P100) on Google Cloud Platform with 8 vCPUs and 29 GB memory. I am not getting the error you have mentioned but the training is pretty slow like (like it takes around 1 day for 1 epoch), batch size is the default (16) and Cuda support is enabled. 
Any suggestions on how this can be improved? Also, could you tell me how much time it takes for you to run 1 epoch?

Thanks

**Comment by yangxu351** [comment]
> I am using the same GPU (NVIDIA Tesla P100) on Google Cloud Platform with 8 vCPUs and 29 GB memory. I am not getting the error you have mentioned but the training is pretty slow like (like it takes around 1 day for 1 epoch), batch size is the default (16) and Cuda support is enabled. I am training it on COCO dataset.
> Any suggestions on how this can be improved? Also, could you tell me how much time it takes for you to run 1 epoch and how big is your training data?
> 
> Thanks

I have the same slow problem, do you have any idea now?
