### ISSUE TITLE
Tiny YOLOv3 vs YOLOv5s

### ISSUE THREAD

**Issue by axlecky** [eriklindernoren/PyTorch-YOLOv3#775]
Hi, I'm trying to compare the 2 models by training them on the same custom dataset. However, after testing I realized that the Tiny YOLOv3 performs at an mAP0.5 of 0.7 but with an extremely high inference speed of 3.1ms while the YOLOv5s performs at an mAP0.5 of 0.89 at a slower inference speed of 6.1ms. Is this normal?

**Comment by jaagut** [comment]
Hi!
This repository does not contain any `YOLOv5s`. To make sure we can understand your question correctly, we need some more information. Could you clarify what `YOLOv3` and `YOLOv5s` implementations you are talking about (provide a link), please?
