### ISSUE TITLE
Having some doubts for build_target

### ISSUE THREAD

**Issue by d5423197** [eriklindernoren/PyTorch-YOLOv3#777]
https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/3f7f04bb4137219e8f0f1bde0af15f08ab6fb746/pytorchyolo/utils/loss.py#L151

Hello author,

Thanks for your contribution and comments on the code. Those are really helpful. 
I am still learning YOLO. I have a question about the transformation from the label (from annotation txt file) to target (that YOLO can use). The question might be silly. 

Based on the code you provided, I realized that one label from annotation txt file might occur in different anchor in the same grid scale. And it may also occur in another grid scale.

Let us say, there is an object A.
In grid 13 x 13, A may also occur in anchor 0 and 1.
In grid 26 x 26, A may also occur in anchor 0 and 1.

Please let me know if my question is unclear. 

Best,

ZD

**Comment by Flova** [comment]
Yes, the described behavior is the case and intended. Was this your question? Was it just the overall concept or something specific that is unclear?

**Comment by d5423197** [comment]
Thanks for your reply. I just wanna confirm that my understanding was correct. Now I will continue learning from your code.

**Comment by Flova** [comment]
Okay :)

**Comment by d5423197** [comment]
Hello there,

After learning your code, I still have some doubts.
If one label has a chance to appear in each layer(13 13, 26 26, 52 52), I am seeing that the loss will be added for each layer. I dont know the reason behind this.

Thanks,
ZD
