### ISSUE TITLE
Poetry install problem

### ISSUE THREAD

**Issue by d5423197** [eriklindernoren/PyTorch-YOLOv3#778]
Hello author,

This might be a potential bug when doing poetry install.

I used python 3.10 and do poetry install, got the error msg below.
Could not build wheels for numpy which use PEP 517 and cannot be installed directly

I have used python 3.8 and retry.  It works fine now.

**Comment by Flova** [comment]
Could you send the exact output from the failing NumPy installation?

**Comment by d5423197** [comment]
Hi there,
 
This was the exact output.

ZD

**Comment by Flova** [comment]
Googling reveals that this issue mainly happens with out of date pip versions. Try to update pip as well as poetry.

**Comment by d5423197** [comment]
Thanks
