### ISSUE TITLE
Train with other dataset

### ISSUE THREAD

**Issue by RickvanHek** [eriklindernoren/PyTorch-YOLOv3#78]
Is it possible to use this implementation to train YoloV3 for a different dataset? Eg: [the CLEVR dataset](https://cs.stanford.edu/people/jcjohns/clevr/)
Because this is using pretrained weights for the COCO dataset, but not for custom detections like in the clevr dataset.

**Comment by suzil** [comment]
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/16 Looks like there's some information here.

**Comment by eriklindernoren** [comment]
Follow the steps [here](https://github.com/eriklindernoren/PyTorch-YOLOv3#train-on-custom-dataset) to train on a custom dataset.

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
