### ISSUE TITLE
Quantization on trained model

### ISSUE THREAD

**Issue by pelmers** [eriklindernoren/PyTorch-YOLOv3#781]
I am training a custom YOLO model for detection on a Raspberry Pi device. To make it run faster I want to try quantizing the weights to 8 bits.

Has this been done before? Should I just try to follow https://pytorch.org/docs/stable/quantization.html, or is there some specific way it should be accomplished for YOLO?

**Comment by Flova** [comment]
I also mainly use YOLO on the edge (we have more resources that the PI, but it is still limited). So I just experimented with quantization a few weeks ago. But I did it on the exported onnx model (see pytorch docs for onnx export) using the normal onnx tool chain.

In case you are interested: After that, we bring our weight into the Apache TVM framework. This does some fancy optimization and compilation stuff and allows deployment on things like integrated graphics, or as a performant processor specific c library.

**Comment by pelmers** [comment]
@Flova thanks, I'll try following that lead. So you basically export the model from pytorch, quantize it in onnx, then run it in TVM? Thus pytorch is not installed on the edge.
To simplify the steps (since this is just a small project for me), do you know if it's possible to run the onnx model directly?
