### ISSUE TITLE
Help with poetry install

### ISSUE THREAD

**Issue by Mike-The-Knight** [eriklindernoren/PyTorch-YOLOv3#793]
I am having an issue where i run poetry install (I am using visual studio and a Jupyter .ipynb file), and this error message is produced: 
"Because pytorchyolo depends on scipy (^1.9) which doesn't match any versions, version solving failed."

I have tried fixing the issue but I have no idea what is going wrong, when I run the same code but in google collab it works fine. Does anyone know what is wrong?

**Comment by Flova** [comment]
What is your setup? Windows, Ubuntu, etc? And what Python version is used?

**Comment by Mike-The-Knight** [comment]
I tried on a Windows machine and Ubuntu machine, Python version 3.10.6 on both machines

**Comment by Mike-The-Knight** [comment]
Ubunutu:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04

For Windows I dont have the machine with me right now so could not say

**Comment by Flova** [comment]
And you used the most recent commit of this repo, right?

**Comment by Mike-The-Knight** [comment]
yes most recent commit, I was trying on my Windows machine, but about 10 mins ago tried on ubuntu

**Comment by Mike-The-Knight** [comment]
![image](https://user-images.githubusercontent.com/105118863/200020716-fe8e4dce-9927-4aa7-af10-28b02c216b8d.png)
Poetry already installed on this machine

**Comment by Mike-The-Knight** [comment]
When this merges it will be all good?

**Comment by Flova** [comment]
I could reproduce this issue on my machine. It is kinda weird, since that exact versions passed the CI a few days ago for Windows and Ubuntu 20/22. But I bumped the versions and on my 22.04 Machine everything seems fine. But I wait for the Windows and 20.04 CI before I merge it.

**Comment by Mike-The-Knight** [comment]
Sounds good

**Comment by Flova** [comment]
It seems like the build is not passing on Windows with the new version, so there is some more work to do.

**Comment by Mike-The-Knight** [comment]
No problem, I will still be active, when the merge is successful I will test it out. Thank you very much

**Comment by Flova** [comment]
How did you install poetry?

**Comment by Flova** [comment]
The dependency issues should be resolved
