### ISSUE TITLE
Could not build wheels for numpy issue

### ISSUE THREAD

**Issue by Mike-The-Knight** [eriklindernoren/PyTorch-YOLOv3#795]
Whilst running poetry install, on my Windows computer (build 10.0.22000) getting this error:
![image](https://user-images.githubusercontent.com/105118863/200119124-dcc6673f-2b43-4dca-9e64-6b676e36516c.png)

## Expected behavior
Expected poetry to install all the dependencies

## Current behavior
Throws a huge error

## Steps to Reproduce
1. ran git clone
2. ran poetry install

**Comment by Flova** [comment]
Could you try again with the most recent version? I changed the versions a bit and dropped the support for python 3.7. This we therefore are able to use the NumPy binaries again.

**Comment by Flova** [comment]
I will close this for now. If #796 did not fix the issue, ping me and I reopen.

**Comment by Mike-The-Knight** [comment]
Hi! finally got time to try this out again, I tried on both versions again, Ubuntu and Windows and with the new implementation I am getting the scipy issue again.
![image](https://user-images.githubusercontent.com/105118863/200881925-402f38be-0e4d-4f71-8b1d-c662c1914879.png)

I am much more free from now so will be more active answering sorry.

Thank you
