### ISSUE TITLE
Replace own `Mish` implementation by torch's

### ISSUE THREAD

**Issue by jaagut** [eriklindernoren/PyTorch-YOLOv3#800]
## Is your feature request related to a problem? Please describe.
In #695 the `mish` activation function is implemented. https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/e54d52e6500b7bbd687769f7abfd8581e9f59fd1/pytorchyolo/models.py#L117
Torch now provides this function itself. 

## Describe the solution you'd like
Use this: https://pytorch.org/docs/1.10/generated/torch.nn.functional.mish.html?highlight=mish#torch.nn.functional.mish

**Comment by mikel-brostrom** [comment]
Did you train any model with this activation @jaagut? What was the oucome?

**Comment by jaagut** [comment]
Did you mean with `mish` at all, or with which implementation?
Yes, I/we (@Flova) trained models using the _own_ `mish` implementation, as can be seen above. We did not yet train using the PyTorch implementation.

**Comment by mikel-brostrom** [comment]
Sorry, but cannot find the training results...

**Comment by jaagut** [comment]
> Sorry, but cannot find the training results

I was not referring to training results, but to the implementation of `mish`:
[PyTorch-YOLOv3/blob/e54d52e6500b7bbd687769f7abfd8581e9f59fd1/pytorchyolo/models.py#L117](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/e54d52e6500b7bbd687769f7abfd8581e9f59fd1/pytorchyolo/models.py#L117)

Apparently, we have not uploaded a model-config containing `mish`, but if I recall correctly, a model like [YOLOv4](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4.cfg) should _just_ work.

We do not regularly test YOLOv4, and therefore, we are interested in your results.
Please open a new issue if you have problems.

**Comment by Flova** [comment]
I am closing this issue as we are now using the official mish implementation.
