### ISSUE TITLE
cannot use yolov3-tiny ?

### ISSUE THREAD

**Issue by zhangming8** [eriklindernoren/PyTorch-YOLOv3#82]
when I use yolov3-tiny: python3 detect.py --image_folder data/samples --config_path config/yolov3-tiny.cfg --weights_path weights/yolov3-tiny.weights
it show this error: RuntimeError: Given groups=1, weight of size [256, 256, 3, 3], expected input[1, 384, 26, 26] to have 256 channels, but got 384 channels instead
Could you tell me the reason?

**Comment by sccbhxc** [comment]
I also encounter the same problem.

**Comment by jingtianyilong** [comment]
same here. Guess there's something wrong when it read the cfg file.

**Comment by Aslizy** [comment]
Same problem here.

**Comment by Aslizy** [comment]
The problem lies in the route part of create_modules function in models.py. The first element of output_filter is 3 (RGB channels), however, the index0 in configuration file is the output channel of the first CNN. You can: 
            filters = 0
            for layer_i in layers:
                if layer_i > 0:
                    layer_i += 1 
                filters += output_filters[layer_i]
                
  instead of:                   
            #filters = sum([output_filters[layer_i] for layer_i in layers])

**Comment by zhangming8** [comment]
@Aslizy solved this problem ,thank you very much.
            filters = 0
            for layer_i in layers:
                if layer_i > 0:
                    layer_i += 1
                filters += output_filters[layer_i]

**Comment by manishravula** [comment]
Indented version: 

`filters = 0
for layer_i in layers:
if layer_i > 0:
    layer_i += 1
    filters += output_filters[layer_i]`

**Comment by packyan** [comment]
> @Aslizy solved this problem ,thank you very much.
> filters = 0
> for layer_i in layers:
> if layer_i > 0:
> layer_i += 1
> filters += output_filters[layer_i]

after edit these lines, I still got some errors in tinyv3:
  File "video.py", line 92, in <module>
    model = Darknet(cfgfile)
  File "/home/pakcy/Desktop/PyTorch-YOLOv3/models.py", line 243, in __init__
    self.hyperparams, self.module_list = create_modules(self.module_defs)
  File "/home/pakcy/Desktop/PyTorch-YOLOv3/models.py", line 42, in create_modules
    bias=not bn,
  File "/usr/local/lib/python3.6/dist-packages/torch-0.4.1-py3.6-linux-x86_64.egg/torch/nn/modules/conv.py", line 297, in __init__
    False, _pair(0), groups, bias)
  File "/usr/local/lib/python3.6/dist-packages/torch-0.4.1-py3.6-linux-x86_64.egg/torch/nn/modules/conv.py", line 33, in __init__
    out_channels, in_channels // groups, *kernel_size))
RuntimeError: sizes must be non-negative

can you tell me why?

**Comment by packyan** [comment]
```py
filters = 0
for layer_i in layers:
        if(layer_i > 0):
            filters += output_filters[layer_i+1]
        else:
            filters += output_filters[layer_i]
```
THIS IS MY SOLUTION..

**Comment by jclevesque** [comment]
Seems to be running that way, but performance appears to be bad. Anyone else?

For instance it's not detecting the dog/bike in the dog.jpg example:

![dog-pytorch-yolov3-tiny](https://user-images.githubusercontent.com/673768/50227856-b2a8b000-0374-11e9-957c-d488d832ba0d.jpg)

Compared with the reference darknet implementation (same weight file): 

![predictions-reference-darknet-yolov3-tiny](https://user-images.githubusercontent.com/673768/50227882-c48a5300-0374-11e9-95b3-6cf8254aee64.jpg)

**Comment by glenn-jocher** [comment]
Hey guys. I ran into the same problem in my own yolov3 repo, and got it fixed with a few changes. Results now match darknet:
https://github.com/ultralytics/yolov3/issues/51

`./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg`
![50227882-c48a5300-0374-11e9-95b3-6cf8254aee64](https://user-images.githubusercontent.com/26833433/50374076-b3497c80-05e8-11e9-8d41-acd42d3fbfc6.jpg)

`detect.py --cfg cfg/yolov3-tiny.cfg --weights weights/yolov3-tiny.pt`
![dog](https://user-images.githubusercontent.com/26833433/50374086-d411d200-05e8-11e9-9987-ee0c81af4bbc.jpg)

**Comment by eriklindernoren** [comment]
That's a serious bug. Thanks! Fixed with the latest commit.
