### ISSUE TITLE
i'm using yolov3.weights to test data/sample/,  i found there are some wrong bboxes which are different from this projects

### ISSUE THREAD

**Issue by J-LINC** [eriklindernoren/PyTorch-YOLOv3#821]
I am testing on/data/sample using the weights trained on the coco dataset, but the results obtained are somewhat different from those shown by the author on the homepage. That is why?
![2023-03-29 12-18-00 的屏幕截图](https://user-images.githubusercontent.com/89594867/228425565-6153e667-8fe2-483a-80ea-9e3359198e16.png)
![2023-03-29 12-18-22 的屏幕截图](https://user-images.githubusercontent.com/89594867/228425606-7534ba60-3217-4dcb-8bf1-a02581610db4.png)
![2023-03-29 12-18-38 的屏幕截图](https://user-images.githubusercontent.com/89594867/228425638-fa50ae7b-0c92-4f53-b07f-dbcc1c3e4e87.png)

**Comment by Flova** [comment]
What weights did you use? Did you train from scratch or did you use the official darknet yolov3 ones?

**Comment by Flova** [comment]
Also make sure that the image size is 608 and not 416 (default).

**Comment by J-LINC** [comment]
> 

I'm not using my own training, it's the official training weight yolov3.weights

**Comment by J-LINC** [comment]
> What weights did you use? Did you train from scratch or did you use the official darknet yolov3 ones?

I'm not using my own training, it's the official training weight yolov3.weights

**Comment by J-LINC** [comment]
> Also make sure that the image size is 608 and not 416 (default).

I really use 416 * 416, and I want to know if the model trained on 416 * 416 predicts that the image of 608 * 608 will work better, just like here.

**Comment by Flova** [comment]
I think the errors are in levels that I expect from the v3 model. But I'm wondering why the boxes are slightly different now. It could be a numerical thing due to newer library versions etc., as I can not think of any significant changes to this part of the code. I also evaluated the weight on coco right now and got an mAP of `0.57653`, which is slightly better compared to the value in the README.
![image](https://user-images.githubusercontent.com/15075613/228655447-c7ba489c-930c-46f0-98e2-bb33caec9152.png)

**Comment by J-LINC** [comment]
> I think the errors are in levels that I expect from the v3 model. But I'm wondering why the boxes are slightly different now. It could be a numerical thing due to newer library versions etc., as I can not think of any significant changes to this part of the code. I also evaluated the weight on coco right now and got an mAP of `0.57653`, which is slightly better compared to the value in the README. ![image](https://user-images.githubusercontent.com/15075613/228655447-c7ba489c-930c-46f0-98e2-bb33caec9152.png)

Okay,Thank you for your timely response！
