### ISSUE TITLE
for Linux？or for windows?

### ISSUE THREAD

**Issue by JiaQiMark** [eriklindernoren/PyTorch-YOLOv3#839]

**Comment by jaagut** [comment]
Both are supported. However, we mainly test and run CI on Ubuntu Linux. We have heard of many people running this software successfully under Windows.

**Comment by JiaQiMark** [comment]
OK, Thank you. This can be run directly on Ubuntu, but it needs to be adapted  if on windows

**Comment by Flova** [comment]
We have some limited testing also for Windows in our CI. So running the core components under Windows should be fine without any adjustments. Some scripts (e.g. the one that downloads the weights) are written in bash and require some Linux tooling (see #714). But if you download the weights or coco by hand you should be fine.

**Comment by JiaQiMark** [comment]
> We have some limited testing also for Windows in our CI. So running the core components under Windows should be fine without any adjustments. Some scripts (e.g. the one that downloads the weights) are written in bash and require some Linux tooling (see #714). But if you download the weights or coco by hand you should be fine.

when I execute the detect.py under windows, nothing happened

**Comment by Flova** [comment]
No printout what so ever?
