### ISSUE TITLE
关于pytorchyolo1.8.0和GPU不兼容的问题

### ISSUE THREAD

**Issue by LauraABCD** [eriklindernoren/PyTorch-YOLOv3#850]
这份源代码最不好的地方在于必须安装pytorchyolo1.8.0，但是顺带安装的torch是cpu版本的，如果单独安装GPU版本的，会显示和pytorchyolo1.8.0不兼容，总之我感觉就是会有许多地方是相互矛盾的，因此我只能用cpu训练，速度慢的可怜哎哎哎

**Comment by Flova** [comment]
Closing because:
- Not in English
- If the DeepL translation is correct, it is a bit rude
- It does not include the needed information requested in the issue template
