### ISSUE TITLE
Has anyone achieved good results with tiny yolov3 on sample images?

### ISSUE THREAD

**Issue by rsirefelt** [eriklindernoren/PyTorch-YOLOv3#87]
Hi
Tried the tiny-yolov3 implementation on the sample images but didn't get any good results. Have anyone else tried this?

On a side note, to be able to run the tiny-yolov3 model I had to change line 
246 in models.py from
layer_outputs = []
to 
layer_outputs = [x]
to fix the filter counting

**Comment by eriklindernoren** [comment]
Hey @rsirefelt . This should be fixed in the current version. Can you pull the latest version and try again?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
