### ISSUE TITLE
bbox_iou wrong?

### ISSUE THREAD

**Issue by Ray-Luo** [eriklindernoren/PyTorch-YOLOv3#90]
In utils.py line 81 - 86. Should it be like?
```
    inter_area = torch.clamp(inter_rect_x2 - inter_rect_x1, min=0) * torch.clamp(
        inter_rect_y2 - inter_rect_y1, min=0
    )
    # Union Area
    b1_area = (b1_x2 - b1_x1) * (b1_y2 - b1_y1)
    b2_area = (b2_x2 - b2_x1) * (b2_y2 - b2_y1)
```

**Comment by perrywu1989** [comment]
no, it is not wrong. When you compute the length of one side, it should be added 1.

**Comment by Ray-Luo** [comment]
> no, it is not wrong. When you compute the length of one side, it should be added 1.

Thanks for your reply. Let consider this, in utils.py line 213 - 225
```
gx = target[b, t, 1] * nG
gy = target[b, t, 2] * nG
gw = target[b, t, 3] * nG
gh = target[b, t, 4] * nG
# Get grid box indices
gi = int(gx)
gj = int(gy)
# Get shape of gt box
gt_box = torch.FloatTensor(np.array([0, 0, gw, gh])).unsqueeze(0)
# Get shape of anchor box
anchor_shapes = torch.FloatTensor(np.concatenate((np.zeros((len(anchors), 2)), np.array(anchors)), 1))
# Calculate iou between gt and anchor shapes
anch_ious = bbox_iou(gt_box, anchor_shapes)
```
Let say:
` gw = 0.3 * 3 = 0.9`
` gh = 0.3 * 3 = 0.9`
then gt would be like
` [0, 0, 0.9, 0.9]`
say, anchor_shapes is like
`[0, 0, 0.2, 0.2]`
When calculating `anch_ious = bbox_iou(gt_box, anchor_shapes)` we would not need to add 1...
The original implementation where this implementation is built upon, `bbox_ious()` does not add 1 either from line 55 - 84.
https://github.com/marvis/pytorch-yolo2/blob/6c7c1561b42804f4d50d34e0df220c913711f064/utils.py

**Comment by perrywu1989** [comment]
Actually, it should be 
```
 inter_area = torch.clamp(inter_rect_x2 - inter_rect_x1+1/stride, min=0) * torch.clamp(
        inter_rect_y2 - inter_rect_y1+1/stride, min=0
    )
```

**Comment by Ray-Luo** [comment]
> Actually, it should be
> 
> ```
>  inter_area = torch.clamp(inter_rect_x2 - inter_rect_x1+1/stride, min=0) * torch.clamp(
>         inter_rect_y2 - inter_rect_y1+1/stride, min=0
>     )
> ```
> when stride is huge , it can be ignored

Thanks for replying. What's the rationale behind adding `1/stride`?

**Comment by perrywu1989** [comment]
I think it is due to how small a value can stand for one pixel. If the image is not changed, value 1 stands for one pixel. When the image is in range (0,1), then value 1 /(height or width) stands for one pixel. @Ray-Luo

**Comment by eriklindernoren** [comment]
The code for `build_targets` has undergone mayor changes lately, so I'll close this and we'll open a new issue if questions arise.
