### ISSUE TITLE
I want to train the code on pascal voc, so I want to know that is it very diffcult to traing on voc dataset? May be I need to adjust a  lot of codes? Because my device is gtx1060 limited to train code on big dataset such as coco.  Thank you

### ISSUE THREAD

**Issue by ningxiangyun** [eriklindernoren/PyTorch-YOLOv3#91]
_Originally posted by @mshmoon in https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/75#issuecomment-432647218_ have you trained the model on pascal voc?

**Comment by Flova** [comment]
I closed this issue due to inactivity. Feel free to reopen for further discussion.
