### ISSUE TITLE
Has anyone trained with own data ?

### ISSUE THREAD

**Issue by Zhefei777** [eriklindernoren/PyTorch-YOLOv3#95]
I want to train Yolov3 with my own data. I make a dataset with 10500 images. After 20 epochs i cannot detect anything. I want to run test.py and got this error. 
 File "test.py", line 112
    for i in tqdm.tqdm(range(len(all_annotations)), desc=f"Computing AP for class '{label}'"):
                                                                                           ^
SyntaxError: invalid syntax

Could someone help me ? Thanks

**Comment by chijan-nh** [comment]
I'd like to recommend using
`for i in tqdm.tqdm(range(len(all_annotations)), desc="Computing AP for class:{}".format(label)):`
instead of
`for i in tqdm.tqdm(range(len(all_annotations)), desc=f"Computing AP for class '{label}'"):` .

`f"strings spam egg '{variable_name}'"` is invalid syntax.

**Comment by zhouyuangan** [comment]
@Zhefei777 I met same issue, have you solved it? I trained model about 10 epoches but nothing detected.

**Comment by chijan-nh** [comment]
@zhouyuangan 
Is there no bounding box ?
Then c. f. https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/86

Some people propose solutions in the above issue.

In my case, with using the default pytorch model weight save and load methods instead of this implementation, something is detected.
